- README.md
The GH Pages website has been re-activated under a new domain - phars.phpcodesniffer.com -.
The PHARs can now be downloaded from that domain and PHIVE should work as well, though a PR to phar.io will be needed to update the PHIVE alias redirect.
The permanent address for PHAR downloads and downloading the PHARs via PHIVE has changed to phars.phpcodesniffer.com
> README: update URL for downloading the PHAR

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillReadonlyTest.inc
- tests/Core/Tokenizer/BackfillReadonlyTest.php
Recreation and further iteration on upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3773 from @fredden:
Includes some minor tweaks to pre-existing tests.
PHP 8.2 introduces disjunctive normal form types, which use parentheses, which invalidates the previous "special casing" for function/method declarations and calls using the `readonly` keyword.
This commit fixes this.
Note: this does not (yet) add support for DNF types to the tokenizer or anywhere else in PHPCS, it only fixes the tokenization of `readonly`.
Includes additional tests.
Ref: https://github.com/php/php-src/commit/08b75395838b4b42a41e3c70684fa6c6b113eee0
Co-authored-by: Dan Wallis <dan@wallis.nz>
Tokenizer/PHP: fixed the tokenization of the `readonly` keyword when used in combination with PHP 8.2 disjunctive …
> Tokenizer/PHP: fix mis-identification of 'readonly' keyword icw PHP 8.2 DNF types

- .gitattributes
- .github/ISSUE_TEMPLATE/bug_report.md
- bin/phpcbf.bat
- bin/phpcs.bat
- scripts/build-phar.php
Follow up after #4
Found another few references which should be removed.
_N/A_ (covered by the original changelog entry)
> More clean up after removal of PEAR installation support

- README.md
* Add some additional badges.
* Wrap the badges in a div which will hide them for screenreaders.
* Add a note at the top of the README about the continuation of the project.
_N/A_ (already covered by note in changelog about the move)
> README: various tweaks

- .github/labeler.yml
Tweak the labelling conditions a little to prevent running into a bug which I've reported to the action runner: srvaroa/labeler#104
The default pull request template contain a categorization section anyway (which is not typically used for maintainer PRs), so let's use that section to auto-label the "Type" for new PRs.
> GH Actions/label new PRs: tweak the conditions a little

- .github/workflows/label-merge-conflicts.yml
- .github/workflows/label-new-prs.yml
- .github/workflows/phpstan.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
... on pull requests as it doesn't play nice with required statuses.
Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any still running builds for the same branch would be stopped in favour of starting the build for the newly pushed version of the branch.
To enable this behaviour in GH Actions, a `concurrency` configuration needs to be added to each workflow for which this should applied to.
More than anything, this is a way to be kind to GitHub by not wasting resources which they so kindly provide to us for free.
Refs:
* https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
* …
> GH Actions: various improvements & tweaks

- .github/labeler.yml
... to comply with Yaml lint.
* Use consistent indentation.
* Use lowercase `false`.
Grr... I do not like Yaml...
Either way, this fixes a syntax error I accidentally introduced in the Yaml file.
Markdown file changes can be auto-labelled as "documentation" changes.
> GH Actions/label new PRs: fix yaml file + other tweaks

- .gitattributes
- .github/workflows/validate.yml
- .yamllint.yml
Add Yamllint to Validate workflow to loosely safeguard valid and consistent yaml files and prevent issues like seen in PR #68.
Includes adding a configuration file which loosens up the `default` ruleset to a degree I'm comfortable with.
Ref: https://yamllint.readthedocs.io/
_N/A_
> GH Actions: add Yamllint to `validate` workflow

- .github/workflows/label-new-prs.yml
The `srvaroa/labeler` action runner will use the `labeler.yml` from the repo's default branch by default, which is good from a security perspective, but that means that PRs changing the `labeler.yml` file will not be tested until they have been merged and a _next_ PR is opened.
As the `srvaroa/labeler` action runner will silently fail, this also means that the labeling will stop working without any indication (other than labels no longer being added).
I'd like to prevent getting into that situation (again). The `yamllint` workflow I introduced earlier is already a big step in the right direction.
This commit introduces a second safeguard:
* It adds a second job to the workflow which will only run when the files relevant for the workflow are being changed in a PR.
* In that case, this …
> GH Actions: safeguard the PR label workflow some more

- .github/labeler.yml
Only mark a PR as touching one of the standards when the sniff/docs files are touched. Test changes can also relate to the Tokenizer or other parts of PHPCS, so don't necessarily mean that the PR should be marked with the standard name.
_N/A_
> GH Actions/label new PRs: tweak label criteria

- .github/workflows/label-new-prs.yml
Using `master` for action runners is bad practice (as it opens you up to unexpectedly moving to a new major containing breaking changes), but so far, the `srvaroa/labeler` action did not have a floating/moving `v1` tag.
This tag has now been added, so updating the workflow to use it.
The action has also tagged version `v1.7.2`, which should fix an issue I previously reported where tags were being removed, even though the config forbids this.
_N/A_
Refs:
* srvaroa/labeler#104
* srvaroa/labeler#110
* https://github.com/srvaroa/labeler/releases/tag/v1.7.2
> GH Actions/label new PRs: use v1 floating tag

- CHANGELOG.md
- src/Files/File.php
- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
- src/Standards/PSR12/Sniffs/Functions/NullableTypeDeclarationSniff.php
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.php
- src/Tokenizers/PHP.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
- tests/Core/Tokenizer/BitwiseOrTest.inc
- tests/Core/Tokenizer/BitwiseOrTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3662:
> ### PHP 8.2 | Tokenizer/PHP: allow for true in union types
> 
> Previously, `false` and `null` were already allowed in union types. As of PHP 8.2, `true` has been added to the supported types in PHP and can also be used in union types.
> Also see: https://3v4l.org/ZpfID
> 
> This commit adjusts the Tokenizer to correctly retokenize the `T_BITWISE_OR` character to `T_UNION_TYPE` when `true` is included in a union type.
> 
> Includes unit tests.
> 
> Refs:
> * https://wiki.php.net/rfc/true-type
> 
> ### PHP 8.2 | File::getMethodProperties(): allow for true in types
> 
> As of PHP 8.2, `true`, `false` and `null` will be allowed as stand-alone types. `true` can now also be used in union types (was already …
> PHP 8.2 | Tokenizer, File, sniffs: account for new `true` type

- src/Ruleset.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3876:
> On PHP 8.3, using the `-e` (explain) command would show a `Deprecated: Increment on non-alphanumeric string is deprecated in path/to/src/Ruleset.php on line 297` notice after the very first sniff being listed.
> 
> As the `$lastCount` variable is used as a counter, it should have an integer default (start) value, not a text string.
> 
> Fixed now.
> 
> Testable via the command-line using the following command:
> ```bash
> phpcs -e --standard=PSR1
> ```
> 
> Output without this fix:
> ```
> The PSR1 standard contains 8 sniffs
> 
> Generic (4 sniffs)
> ------------------
>   Generic.Files.ByteOrderMark
> 
> Deprecated: Increment on non-alphanumeric string is deprecated in …
```
> PHP 8.3 | Ruleset::explain(): fix deprecation notice

- CHANGELOG.md
- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.17.inc
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3772:
> As it was, the sniff would respect PHPCS disable annotations, but only when either unqualified or qualified up to a sniff name. It would not respect a disable annotation using a sniffname with errorcode, i.e. `PSR1.Files.SideEffects.FoundWithSymbols`.
> 
> While the `FoundWithSymbols` errorcode is the only error code for this sniff and using `// phpcs:disable PSR1.Files.SideEffects.FoundWithSymbols` is effectively the same as using `// phpcs:disable PSR1.Files.SideEffects`, I do believe end-users should not need to be aware of whether or not a sniff has multiple error codes when using disable annotations.
> 
> This updates the sniff to also respect disable annotations which include the error code.
> 
> …
> PSR1/SideEffects: improve recognition of disable/enable annotations

- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3871:
> The `SpaceBeforeBrace` error code is about the space before the scope opener, but was being thrown on the parenthesis closer preceding it, which could be confusing when there is a type declaration between the two.
> 
> Fixed now.
> 
> I haven't added a test as no meaningful test _can_ be added as the error "column" is not part of the test logic.
> 
> To see the issue run the following command over the below code snippet:
> ```bash
> phpcs test.php --standard=Generic --sniffs=Generic.Functions.OpeningFunctionBraceKernighanRitchie --report=code
> ```
> 
> ```php
> function foo( $param_a, $param_b ): Type       {}
> //                       The space here   ^   was originally flagged on the close parens, not …
```
> Generic/OpeningFunctionBraceKernighanRitchie: fix error position

- phpcs.xml.dist
- src/Sniffs/AbstractScopeSniff.php
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.php
- src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.php
- src/Standards/Generic/Tests/Files/LineLengthUnitTest.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.php
- src/Standards/Generic/Tests/PHP/CharacterBeforePHPOpeningTagUnitTest.php
- src/Standards/Generic/Tests/PHP/ClosingPHPTagUnitTest.php
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.php
- src/Standards/Generic/Tests/PHP/RequireStrictTypesUnitTest.php
- src/Standards/Generic/Tests/PHP/SyntaxUnitTest.php
- src/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.php
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.php
- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/Commenting/LongConditionClosingCommentUnitTest.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.php
- src/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.php
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.php
- src/Standards/Squiz/Tests/PHP/DisallowInlineIfUnitTest.php
- src/Standards/Squiz/Tests/PHP/DisallowSizeFunctionsInLoopsUnitTest.php
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionClosingBraceSpaceUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.php
- tests/Standards/AbstractSniffUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3912:
> 
> ### Tests: remove unreachable code
> `break` after a `return` statement is redundant.
> 
> As a side-note: I did have to chuckle when I saw that the `NonExecutableCode` test file also included this :joy:
> 
> ### Various: remove some redundant return statements
> 
> ... when the `return` is at the end of the function without a value, and therefore not needed.
> 
> ### PHPCS: add the `Squiz.PHP.NonExecutableCode` sniff to the ruleset
> 
> ... which is used for PHPCS itself.
_N/A_
> QA: remove unreachable code

- src/Standards/PSR12/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR2/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3872:
> No functional changes.
> 
> These sniffs only concerns themselves with control structures which take parentheses, so listening for `T_ELSE` is unnecessary as the sniffs will never do anything for that token (they each bow out on no 'parenthesis_opener'/'parenthesis_closer' found).
_N/A_
> PSR2/PSR12/ControlStructureSpacing: don't listen for `T_ELSE`

- src/Files/File.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3800:
> Improve documentation of the `getMethodParameters()`, `getMethodProperties()`, `getMemberProperties()` and the `getClassProperties()` methods.
> 
> Ensuring that the return value format documentation is consistent and correct regarding the type and availability of each index in the returned arrays.
_N/A_
> File: improve documentation

- README.md
Corrects spelling issues in `README.md`
Corrects the spelling to `GitHub` (as the brand name is with capital `H`)  and wraps the directory name `tools` with backticks to clarify the directory is referenced. 
Correct spelling issues in `README.md`
**N/A**
> Correct spelling issues in readme

- .github/CONTRIBUTING.md
Corrects spelling issues in `.github/CONTRIBUTING.md`
Corrects spelling issues in `.github/CONTRIBUTING.md` related to punctuation and redundant phrasing.
Correct spelling issues in .github/CONTRIBUTING.md
**N/A**
> Correct spelling issues in contributing

- src/Standards/Generic/Sniffs/Debug/CSSLintSniff.php
- src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php
- src/Standards/Generic/Sniffs/Debug/ESLintSniff.php
- src/Standards/Generic/Sniffs/Debug/JSHintSniff.php
- src/Standards/Generic/Sniffs/Files/LineEndingsSniff.php
- src/Standards/Generic/Sniffs/Files/LowercasedFilenameSniff.php
- src/Standards/PSR12/Sniffs/Files/OpenTagSniff.php
- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3911:
> Always return EOF pointer for files scanning the complete file in one go as if any of the error conditions are hit, it is useless to try again for the same file.
_N/A_
> Various sniffs: always return EOF pointer

- CHANGELOG.md
- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3739:
> ### PEAR/FunctionDeclaration: bug fix - prevent fixer from creating a parse error
> 
> Issue as described in squizlabs/PHP_CodeSniffer#3736.
> 
> The fixer would try to remove superfluous whitespace remaining after the move of the opening brace to the previous line, but did not take into account that there may not be any whitespace to remove, i.e. that the `$opener +1` token could be the same as the `$next` token.
> 
> Fixed now.
> 
> Includes unit test.
> 
> Fixes squizlabs/PHP_CodeSniffer#3736
> 
> ### PEAR/FunctionDeclaration: prevent fixer conflict
> 
> **_This commit was originally pulled as part of PR squizlabs/PHP_CodeSniffer#3661._**
> 
> If a return type declaration was not confined to one line, …
> PEAR/FunctionDeclaration: bug fix x 2 - prevent fixer creating a parse error + prevent fixer conflict

- CHANGELOG.md
- src/Standards/PSR12/Sniffs/Classes/AnonClassDeclarationSniff.php
- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3791:
> This fix prevents the fixer from removing the opening brace when there is no whitespace between the last character of the name of an interface and the open brace.
> 
> With this fix in place, all other symptoms reported are also gone as they were a side-effect of the parse error being created.
> 
> Includes unit test.
> 
> Fixes squizlabs/PHP_CodeSniffer#3790
PSR12/AnonClassDeclaration: prevent fixer creating parse error
> PSR12/AnonClassDeclaration: prevent fixer creating parse error

- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.js
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.js.fixed
PR squizlabs/PHP_CodeSniffer#2515 introduced a new public property to the sniff, including tests, but the property was not reset after that particular test, which means it could affect all tests added after it.
Fixed now.
_N/A_ (test only change)
> Squiz/OperatorSpacing: minor tweak to the tests

- CHANGELOG.md
- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3833:
> The `Generic.PHP.LowerCaseType` sniff calls the `File::getMemberProperties()` method to get information about potential properties.
> 
> That method throws an exception when the `T_VARIABLE` token passed is not a property, but will create an `Internal.ParseError.InterfaceHasMemberVar` warning and return an empty array when the `T_VARIABLE` passed is an _illegal_ property, i.e. a property in a context in which it is not allowed (interface/enum).
> 
> As things were, the sniff did not take a potential return value of an empty array into account, which could result in an `Undefined array key "type"` PHP notice.
> 
> Fixed now.
> 
> Includes unit test.
---
Other relevant notes from the original PR:
> This PR …
> Generic/LowerCaseType: fix potential PHP notice

- phpcs.xml.dist
This is a re-creation of https://github.com/squizlabs/PHP_CodeSniffer/pull/3914
While working on another task, I noticed that warnings are ignored by default. This seems unintentional. Some discussion regarding this has taken place in https://github.com/squizlabs/PHP_CodeSniffer/pull/3914
Respect warnings as well as errors from sniffs within the coding standard for PHP_CodeSniffer itself.
- Bug fix _(non-breaking change which fixes an issue)_
> Respect all sniffs when reviewing PHP_CodeSniffer itself

- CHANGELOG.md
- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3905:
> The `Squiz.WhiteSpace.FunctionSpacing` sniff demands # lines above and below a function declaration, but when determining the number of lines above or below, it does not care for additional code on the same line as the function declaration. I.e.: it does not demand that a function declaration starts on its own line or that the close brace is on its own line (there are other sniffs for that).
> 
> The sniff also tries to prevent "double" errors for the same issue, i.e. when two functions are each on their own line without blank lines between them, the sniff will only throw one error for "spacing after" the first function and will not throw an error for "spacing before" for the second function.
> 
> To …
> Squiz/FunctionSpacing: bug fix - prevent fixer conflict with itself

- CHANGELOG.md
- src/Config.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3913:
> These arguments should be stored in the `unknown` property. There is no `values` property.
> 
> Note: the read/write logic is to prevent a `Indirect modification of overloaded property PHP_CodeSniffer\Config::$unknown has no effect` PHP notice.
_N/A_ (I don't think this bug had any impact on end-users)
> Config::processLongArgument(): fix storing of unknown arguments

- CHANGELOG.md
- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceBsdAllmanSniff.php
- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3869:
> Basically this is the same fix for both sniffs. The sniffs would `return`, instead of _skip over_ a particular check, which meant that other checks _after_ the check which needed to be skipped were not being run.
> 
> 
> ### Generic/OpeningFunctionBraceKernighanRitchie: check spacing before brace for empty functions
> 
> As things were, when an empty function was detected, the sniff would bow out and not execute the "SpaceBeforeBrace" check.
> 
> Fixed now.
> 
> Includes tests.
> 
> ### Generic/OpeningFunctionBraceBsdAllman: check spacing before brace for empty functions
> 
> As things were, when an empty function was detected, the sniff would bow out and not execute the "BraceIndent" check.
> 
> Fixed …
> Generic/OpeningFunctionBrace*: check spacing before brace for empty functions

- CHANGELOG.md
- src/Standards/Generic/Sniffs/WhiteSpace/IncrementDecrementSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3626:
> The `Generic.WhiteSpace.IncrementDecrementSpacing` sniff, so far, only handled incrementors/decrementors when they were directly before/after the variable they apply to.
> 
> This commit enhances the sniff to also allow for finding superfluous whitespace when incrementing/decrementing a property or an array item.
> 
> Includes unit tests.
> 
> Note: I've only made this change for PHP files as JS support will be dropped anyway, so it didn't feel like a good use of my time to work on that.
Generic/IncrementDecrementSpacing: detect spacing issues for more complex variables
---
From the conversation in the original issue:
> For pre-increment, I can think of a further/future iteration for the sniff - checking …
> Generic/IncrementDecrementSpacing: handle more situations

- CHANGELOG.md
- src/Standards/PSR12/Sniffs/Traits/UseDeclarationSniff.php
- src/Standards/PSR12/Tests/Traits/UseDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Traits/UseDeclarationUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3856:
> ### PSR12.Traits.UseDeclaration: fix typo in error code
> 
> The `processUseStatement()` method checking single-line trait `use` statements checks the spacing after the `use` keyword, but the error did not have the correct error code.
> 
> ### PSR12.Traits.UseDeclaration: check spacing after use keyword for multi-line statements
> 
> While the `processUseStatement()` method checking single-line trait `use` statements would check the spacing after the `use` keyword, the `processUseGroup()` method checking multi-line trait `use` statements did not execute that same check, while the rule applies to both single- as well as multi-line `use` statements.
> 
> By moving the check for the spacing after the `use` …
> PSR12.Traits.UseDeclaration: check spacing after use keyword for multi-line statements + fix typo

- CHANGELOG.md
- src/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3715:
> ### Generic/UnusedFunctionParameter: ignore class context for closures/arrow functions
> 
> As things were, if a closure or arrow function declared within a class which extends or implements would have an unused function parameter, it would get the `InExtendedClass` or `InImplementedInterface` addition in the error code.
> 
> Those additions were only intended for function declarations where the declaration would potentially be overloading a method from a parent and would have to comply with the method signature of the method in the parent class/interface.
> 
> This could lead to underreporting if a standard explicitly excludes the error codes contain `InExtendedClass` and/or `InImplementedInterface`.
> 
> …
> Generic/UnusedFunctionParameter: bug fix x 2 (magic methods and error codes)

- src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3667:
> Minor defensive coding and documentation improvements + an additional unit test.
The original PR was bigger and contained a bug fix, but was fixed in parallel via another commit.
> Fixed by commit https://github.com/squizlabs/PHP_CodeSniffer/commit/9445108a57b46f4e84a890788de5d2388346460a in response to issue https://github.com/squizlabs/PHP_CodeSniffer/issues/3666, though this PR still contains some minimal differences (defensive coding, comment + minor difference in the fix) which may be worth having a look at.
_N/A_
> PEAR/FunctionCallSignature: minor tweaks

- CHANGELOG.md
- src/Config.php
- src/Files/File.php
- src/Reports/Performance.php
- src/Util/Timing.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3810:
> ~~**_This PR depends on PR squizlabs/PHP_CodeSniffer#3804 to allow for automated testing of the new report._**~~
> ~~Either PR squizlabs/PHP_CodeSniffer#3804 should be merged first and this PR rebased to remove that commit after the merge or the EndToEnd test included in this PR should be removed from the last commit and (after this PR has been merged), the test can be added to PR squizlabs/PHP_CodeSniffer#3804.~~
> 
> ~~☝🏻 The above is the only reason to open this PR in draft. The actual change in the PR is ready for review.~~
> 
> ---
> 
> ### Util\Timing: split `printRunTime()` method
> 
> ... into logical parts to allow the Performance report access to the total run time information (at the point of …
> New `Performance` report to measure sniff run time performance

- CHANGELOG.md
- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3839:
> Someone reported a performance issue with the `Generic.PHP.LowerCaseType` sniff to me.
> 
> Running the Performance report (PR squizlabs/PHP_CodeSniffer#3810/PR #60) over a number of codebases, confirmed that the sniff ranked in the top 10 of "slow" sniffs.
> 
> As it was, the sniff would examine all variables it comes across and disregard them if they are not properties or not typed. The "disregard when not a property" was done by catching an exception thrown by the `File::getMemberProperties()` method.
> 
> As the majority of `T_VARIABLE` tokens in the average file are not property declarations, the `File::getMemberProperties()` method would be triggered lots and lots of times, with the majority of those …
> Generic/LowerCaseType: improve performance

- CHANGELOG.md
- src/Standards/PSR12/Sniffs/Files/OpenTagSniff.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3840:
> No functional changes at all, just improving performance of the sniff by changing the order of certain checks.
> 
> Some benchmarks for this change run using the Performance report (PR squizlabs/PHP_CodeSniffer#3810/PR #60):
> 
> Command: `phpcs -ps . --extensions=php --ignore=/vendor/ --report=performance --standard=psr12`
> 
> Output for the `PSR12.Files.OpenTag` sniff:
> 
> Result | PHPCS itself       | Set of Projects A  | Set of Projects B  | Set of Projects C |
> ------ | ------------------ | ------------------ | ------------------ | ----------------- |
> Nr of Files Scanned | 614   | 4115               | 25546              | 2250              |
> Before | 0.077045 (  2.3 %) | 0.982014 (  1.9 %) | …
> PSR12/OpenTag: improve performance

- CHANGELOG.md
- README.md
- composer.json
:warning: **_To be merged once the Packagist edit has been made._** :warning:
This reverts commit f6dc841498ab8b056ba0bb8f6785ed634700b34e and updates the information in the changelog for the 3.8.0 release.
**Users who already changed the package name in _their_ `composer.json` dependencies, should switch back to the original package name.**
Refs:
* See [the conversation from this comment down](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1841873639).
Closes #113, #114, #116
> Composer: revert package name change

- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
`requiredSpacesBeforeColon` wasn't being reset after the tests it applies to
> Squiz/ControlSignature: add missing property reset

- src/Standards/Generic/Sniffs/Arrays/ArrayIndentSniff.php
- src/Standards/Generic/Sniffs/Formatting/SpaceAfterCastSniff.php
- src/Standards/Generic/Sniffs/Formatting/SpaceAfterNotSniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.php
- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.php
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.php
This PR fixes more occurences of the word `space(s)` to be either `space` or `spaces` depending on the spacing value. 
This PR is a port of https://github.com/squizlabs/PHP_CodeSniffer/pull/3881 to this repo which was created after some brief discussion with @jrfnl in https://github.com/squizlabs/PHP_CodeSniffer/pull/3647 and addressing the Sniff I've pointed out in https://github.com/squizlabs/PHP_CodeSniffer/pull/3647#pullrequestreview-1593431719
Correct pluralization of the word space/spaces depending on the spacing value
**N/A**
> Correct pluralization of the word space/spaces depending on the spacing value

- CHANGELOG.md
- src/Standards/Generic/Sniffs/PHP/LowerCaseConstantSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.php
I noticed a PHPCS run on a particular code base being quite slow. Running the Performance report from PR suizlabs/PHP_CodeSniffer#3810 / #60 showed the `Generic.PHP.LowerCaseConstant` sniff being the slowest sniff taking 27 seconds on a total sniff run time of 87 seconds (with a few hundred sniffs being run).
A closer look at the sniff pointed to the "skip type declarations for typed properties" part of the sniff as the culprit - in combination with the code base in question having a lot of array properties containing large arrays with mostly `true/false/null` values.
Every single one of those `true/false/null` values would trigger a condition check and then a check whether the token was in the property value, causing lots of token walking for those long arrays.
This PR should fix that by …
> Generic/LowerCaseConstant: improve performance

- phpstan.neon.dist
When I run the test-suite locally, I get errors unless I apply the proposed fixes. Curiously these errors don't seem to be showing up in GitHub - eg https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/runs/7141889620/job/19450040728.
A changelog entry should not be necessary for this change.
- Bug fix _(non-breaking change which fixes an issue)_
> Fix testsuite

- composer.json
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=space --indent-size=4`.
Ref: https://github.com/ergebnis/composer-normalize
_N/A_
> Composer: sort of "normalize" the file

- .github/workflows/label-merge-conflicts.yml
- .github/workflows/label-remove-outdated.yml
Some more label management tweaks, trying to get it balanced out right.
... as a PR wouldn't have been merged if the merge conflict still existed.
(Adding the "merge conflict" labels works really well, but they don't always seem to get removed quickly enough)
... in an attempt to get the action runner to remove the "has conflict" label when a PR is updated (which hopefully would have resolved the conflict).
_N/A_
> GH Actions/label mngmnt: various tweaks

- .github/workflows/build-phar.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
While it is still a good idea to make sure the PHAR building script works on all supported PHP versions, it is not necessary to run this task against all PHP versions on all pushes, nor to have the test runs wait until all PHAR building builds are done, as for the tests we only need the PHARs generated on PHP 8.0, which are the ones used in a release.
This commit splits the PHAR building job off to its own script, only keeping the PHAR build against PHP 8.0 in the `test` workflow.
While this does mean there is now some duplication in the scripts, I find it more relevant to make the builds faster.
... which runs only against low/medium/high PHP versions and does not run:
- the tests using custom PHP ini settings
- the tests related to sniffs using external JS/CSS tooling
- test CS check …
> GH Actions: test workflow improvements

- .github/workflows/test.yml
* Remove some information from a step name which is already in a comment above it.
* Fold two steps into one (Composer install).
* Add a missing condition to prevent a step from running when it is not needed.
_N/A_
> GH Actions: few small workflow tweaks

- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.1.inc
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.4.inc
> Squiz/NonExecutableCode: move parse error test to its own file

- src/Reports/Full.php
This is a re-creation of https://github.com/squizlabs/PHP_CodeSniffer/pull/3925:
> The first is that the ANSI escape codes applied to bold the message when `-s` is used were not being taken into account when wrapping the lines for width, causing some lines to be wrapped unnecessarily.
> 
> The second is that when lines were wrapped in the middle of a long message, the `|` characters making up the table were being bolded along with the message.
* Avoid unnecessarily wrapping lines in the full report when `-s` is used.
* Fix incorrect bolding of pipes in the full report tables when `-s` is used and messages wrap.
Fixes #124
Fixes squizlabs/PHP_CodeSniffer#3924
Closes squizlabs/PHP_CodeSniffer#3925
- I see no existing tests for any of the reporting formats.
> Report Full: fix two line wrapping bugs

- src/Reports/Full.php
When determining the max message length, the calculation did not take potential explicit multi-line messages into account and would base the delimiter line length on the length of the complete message, not on the length of the individual lines.
Fixed now.
* Report Full: fixed bug in delimiter line calculation
Discovered while reviewing #125
Related to squizlabs/PHP_CodeSniffer#2093
Testing this fix manually is not that easy and there are no unit/integration tests for the reports yet either.
How I tested this myself is by taking the test code from squizlabs/PHP_CodeSniffer#2093 and adding it (temporarily) to a random sniff:
```php
$message = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nAenean felis urna, dictum vitae lobortis vitae, maximus nec enim. Etiam euismod placerat …
```
> Report Full: fix delimiter line bug

- README.md
The signing key used for the phars is mentioned in the README.  This can serve as a "trust anchor" for consumers.
Fixes #157
> Doc: mention the signing key for phars

- src/Standards/Generic/Docs/Formatting/SpaceBeforeCastStandard.xml
This PR adds documentation for the SpaceBeforeCast sniff.
I opted to use a single `<standard>` block as this sniff generates a single warning message but with different error codes. Let me know if I should use one `<standard>` block per error code.
Add documentation for the SpaceBeforeCast sniff
Part of #148
> Add documentation for the SpaceBeforeCast sniff

- src/Standards/Generic/Tests/PHP/NoSilencedErrorsUnitTest.inc
- src/Standards/Generic/Tests/PHP/NoSilencedErrorsUnitTest.php
This PR adds two new tests to cover lines of the Generic.PHP.NoSilencedErrors that were not covered previously. One has to do with a sniff property that allows users to set this sniff as an error instead of a warning (default value), and the other with calculating `$contextLength` when its value should be smaller than the default value of 4.
Part of #146
> Generic/NoSilencedErrors: improve test coverage

- .github/workflows/label-merge-conflicts.yml
Follow up on #141 which added the `pull_request_target` trigger with types to the merge conflict check.
The `edited` type seems to include changes to the PR labels, which means that the workflow keeps getting cancelled and retriggered on new PRs due to the label workflow running and adding labels, so let's remove the `edited` type.
_N/A_
> GH Actions: minor tweak to merge conflict workflow

- src/Standards/PSR12/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
No need to create a new instance of the PSR2 sniff every single time the sniff is triggered. Re-using the same object, just like is done with sniffs in general, will work just as well. This will have a (tiny) positive impact on performance, though the impact is so small, it can be considered negligible.
_N/A_
> PSR12/ControlStructureSpacing: small tweak

- src/Config.php
- src/Reports/Performance.php
- src/Ruleset.php
- src/Util/Timing.php
Fix some types/improve type specificity.
_N/A_
> Docs: various minor fixes

- src/Runner.php
The `Reporter::cacheFileReport()` method only takes one parameter.
_N/A_
> Runner::processFile(): remove stray passed params

- src/Files/File.php
Found when reviewing some code using this function. The difference in wording is significant as the original wording gave the impression that the `$start` token would be excluded from the search, while in reality, it is included in the search.
Note: there are no tests for this function!
_N/A_
> File::findFirstOnLine(): minor correction to the docs

- src/Filters/GitModified.php
- src/Filters/GitStaged.php
- tests/Core/Filters/AbstractFilterTestCase.php
- tests/Core/Filters/Filter/AcceptTest.php
- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
Prelim PR to allow for safely making the changes proposed in #198.
... to contain some basic utilities and logic for use in Filter related tests.
Includes switching the `Filter/AcceptTest` to use the new abstract and to use the available utilities.
Includes making the …
> Filters: add tests for GitModified and GitStaged filters + improve existing Filter test

- src/Filters/ExactMatch.php
- src/Filters/GitModified.php
- src/Filters/GitStaged.php
Remove the needless use of culturally insensitive blacklist/whitelist terminology used in the property names and the documentation.
As these properties are `private`, this is a change which doesn't affect the API and is therefore non-breaking.
_N/A_
Related to #198
> Filters/ExactMatch: rename some private properties

- .github/workflows/test.yml
I'm getting sick and tired of having to restart builds due to artifacts not downloading correctly.
This bug has been reported to the action runner and upgrading to v4 should not be re-attempted until the issue has been resolved.
Effectively reverts Dependabot PR #172 (and #173).
_N/A_
Related issue: actions/download-artifact#249
> GH Actions: downgrade actions/[upload|download]-artifact back from 4 to 3

- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
If one uses a union type for an object property, the doc-type-hint could not be related to the variable type.
Fixed now.
Includes unit test.
This is a continuation of [#3757](https://github.com/squizlabs/PHP_CodeSniffer/pull/3757)
Closes #178
Closes squizlabs/PHP_CodeSniffer#3757
> Squiz/VariableComment: allow union and intersection types to be detected

- tests/Core/AbstractMethodUnitTest.php
- tests/Core/File/GetClassPropertiesTest.php
- tests/Core/File/GetMemberPropertiesTest.php
This commit introduces a new `expectRunTimeException()` test helper method to allow for expecting a PHPCS native `PHP_CodeSniffer\Exceptions\RuntimeException` in a PHPUnit cross-version compatible manner.
Includes implementation of the new method in the few test classes which currently need it (and which extend the `AbstractMethodUnitTest` class).
_N/A_
> Tests/AbstractMethodUnitTest: new `expectRunTimeException()` helper method

- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindExtendedClassNameTest.php
Make the test marker names more descriptive
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight forward to update and add tests as it will be more obvious what each …
> File::findExtendedClassName(): improve tests

- tests/Core/File/FindImplementedInterfaceNamesTest.inc
- tests/Core/File/FindImplementedInterfaceNamesTest.php
Make the test marker names more descriptive
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight forward to update and add tests as it will be more obvious what each …
> File::findImplementedInterfaceNames() improve tests

- tests/Core/File/FindStartOfStatementTest.inc
- tests/Core/File/FindStartOfStatementTest.php
This adds some extra tests which were already in use in PHPCSUtils.
_N/A_
> Tests/FindStartOfStatementTest: add extra tests

- src/Files/File.php
- tests/Core/File/GetConditionTest.inc
- tests/Core/File/GetConditionTest.php
This imports the tests which were already in use in PHPCSUtils into PHP_CodeSniffer.
Includes a minor efficiency fix as the `isset()` check on the `'conditions'` key in the tokens array is non-effective as the `'conditions'` key is always set, but may be empty. The minor adjustment now made will allow the method to bow out early correctly.
_N/A_
> File::[get|has]Conditions(): add tests

- tests/Core/File/GetDeclarationNameJSTest.js
- tests/Core/File/GetDeclarationNameJSTest.php
- tests/Core/File/GetDeclarationNameTest.inc
- tests/Core/File/GetDeclarationNameTest.php
This imports the tests which were already in use in PHPCSUtils into PHP_CodeSniffer.
_N/A_
> File::getDeclarationName(): add tests

- .github/workflows/label-merge-conflicts.yml
When this workflow is triggered on the `pull_request_target` event, the branch will identify as `master` (`github.ref`), which means that any push to `master` AND any other PR being opened will cancel the workflow.
That is not the intention, jobs for PRs triggering this workflow should always run to completion.
However, as the `push` event and the `pull_request_target` events don't really have much overlap in available info, it is not straight forward to set a group name which will prevent the above from happening.
With that in mind, I'm removing the concurrency cancellation from this workflow.
_N/A_
> GH Actions/merge conflict check: don't cancel on higher prio

- tests/Core/AbstractMethodUnitTest.php
- tests/Core/File/GetTokensAsStringTest.inc
- tests/Core/File/GetTokensAsStringTest.php
An individual test can set the `$tabWidth` property in the test file to overwrite the default value.
This imports the tests which were already in use in PHPCSUtils into PHP_CodeSniffer.
_N/A_
> File::getTokensAsString(): add tests

- src/Standards/Generic/Docs/PHP/SyntaxStandard.xml
This PR adds documentation for the Generic.PHP.Syntax sniff.
I'm unsure about what to use in the `title` attribute. I followed the convention and used the sniff name, but just `Syntax` is not very clear. Happy to leave it as is if that is ok. An alternative that I considered using is `PHP Syntax`.
Add documentation for the Generic.PHP.Syntax sniff
Part of #148
> Generic/PHP/Syntax: add XML documentation

- tests/Core/File/GetMethodParametersParseError1Test.inc
- tests/Core/File/GetMethodParametersParseError1Test.php
- tests/Core/File/GetMethodParametersParseError2Test.inc
- tests/Core/File/GetMethodParametersParseError2Test.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
This adds testing of various `*_token` return value indexes to the pre-existing tests, same as was already being tested in PHPCSUtils.
:point_right: the diff will be easiest to review while ignoring whitespace differences due to the array alignment changes to comply with CS.
This adds some extra tests which were already in use in PHPCSUtils.
_N/A_
> File::getMethodParameters(): improve tests

- src/Standards/PSR12/Docs/Classes/ClosingBraceStandard.xml
The PR contains the documentation for the PSR12/Classes/ClosingBrace sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#4-classes-properties-and-methods).
Add documentation for the PSR12 ClosingBrace sniff
Part of #148
> [Documentation] PSR12 - Closing Brace

- src/Standards/Generic/Docs/WhiteSpace/LanguageConstructSpacingStandard.xml
This PR adds documentation for the Generic.WhiteSpace.LanguageConstructSpacing sniff.
Despite the sniff using multiple error messages, I used a single `<code_comparison>` block as the valid code examples are essentially the same (per the conversation here https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/159#discussion_r1424492090).
I opted to add the list of language constructs that this sniff supports to the description as I was worried some users might get the impression that this sniff works for all language constructs, which is not the case.
On a side note (I'm happy to move this to its own issue if that is preferable), I wonder if this sniff should remove spaces after language constructs without content? So, for example, should this sniff be triggered when it finds `return ;` …
> Generic/LanguageConstructSpacing: add XML documentation

- src/Standards/PSR12/Docs/Classes/OpeningBraceSpaceStandard.xml
The PR contains the documentation for the PSR12/Classes/OpeningBraceSpace sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#41-extends-and-implements).
Add documentation for the PSR12 OpeningBraceSpace sniff
Part of #148
> [Documentation] PSR12 - Opening Brace Space

- src/Reports/Performance.php
- tests/Core/Ruleset/ExplainTest.php
Follow up on #1.
Some PRs which were ported over from the Squizlabs repo introduced new files in which the old license link was still included.
Fixed now.
_N/A_
> QA: fix up license links in newly merged files

- src/Standards/Generic/Docs/CodeAnalysis/EmptyPHPStatementStandard.xml
This PR adds documentation for the Generic/EmptyPHPStatement sniff.
I added one `<standard>` block per warning generated by this sniff. I considered adding another `<standard>` block to the beginning of the file summarizing what this sniff does. Something like:
```xml
<documentation title="Empty PHP Statement">
<standard>
<![CDATA[
Empty PHP tags and superfluous semi-colons are not allowed.
]]>
</standard>
(...)
</documentation>
```
It does duplicate the content of the other `<standard>` blocks, but it provides a nice summary at the top of the documentation. Without the summary, there is a chance that someone skimming through the documentation might assume that this sniff is only about empty PHP tags and doesn't cover superfluous semi-colons.
I ended up not including the "summary" …
> Generic/EmptyPHPStatement: add XML documentation

- src/Standards/PSR12/Docs/Files/OpenTagStandard.xml
The PR contains the documentation for the PSR12/Files/OpenTag sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements).
Add documentation for the PSR12 OpenTag sniff
Part of #148
> [Documentation] PSR12 - Open Tag

- src/Standards/PSR12/Docs/ControlStructures/BooleanOperatorPlacementStandard.xml
The PR contains the documentation for the PSR12/CotrolStructures/BooleanOperatorPlacement sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#51-if-elseif-else).
Add documentation for the PSR12 BooleanOperatorPlacement sniff
Part of #148
> [Documentation] PSR12 - Boolean Operator Placement

- phpcs.xml.dist
Test files often use data providers (or should).
Data providers are provided as arrays (as `yield` is not supported in the minimum supported PHP version of PHPCS).
As things were, single item arrays would be forced to be single-line, while multi-item arrays would be forced to be multi-line.
For large data provider arrays which have a mix of single item and multi-item sub-arrays, this decreases the scannability of the test cases.
For that reason, I'm disabling the enforcement of "single item arrays should be single line" for all test files.
In practice this means that multi-item arrays still need to be multi-line, but that single item arrays can be either single line or multi-line, whichever is best for readability of the test data.
_N/A_
Related to #155
> CS rules: tweak array rules for test files

- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
Since PHP 8.2, stand-alone use of `true`, `false` and `null` is allowed.
However, if these were used as the type for a property, the docblock would not be found.
Fixed now.
There were some more allowed types missing from the list of tokens to skip over to find a docblock.
Fixed now.
* Squiz.Commenting.VariableComment : docblocks were incorrectly being flagged as missing when a property declaration used PHP 8.2+ stand-alone `true`/`false`/`null` type declarations
* Squiz.Commenting.VariableComment : docblocks were incorrectly being flagged as missing when a property declaration used PHP native `parent`, `self` or a namespace relative class name type declaration
Related to #178 and #209
> PHP 8.2 | Squiz/VariableComment: allow for stand-alone null/true/false types and more

- .github/workflows/test.yml
- composer.json
As of PHPUnit 9.3, PHPUnit started using PHP-Parser as a basis to calculate code coverage. PHP Parser also polyfills tokens and that can interfere with the sniffs, but only in code coverage runs.
In PHPUnit 9.3.4 a new feature was added to warm the code cache ahead of running tests recording code coverage. Using that feature should prevent the token interference.
So far, I've not seen problems with this for this codebase, but better safe than sorry, so I'm going to enable cache warming now anyway.
Notes regarding cache-warming:
* The `--coverage-cache` and `--warm-coverage-cache` options are available since PHPUnit 9.3.4 and if these are used on older PHPUnit versions, PHPUnit will error out with an "unrecognized CLI argument" error.
* In other words: these options can only be used with …
> GH Actions: warm PHPUnit cache on PHPUnit 9.3+

- tests/Core/Util/SuggestTypeTest.php
The `Common::suggestType()` method did not have dedicated unit tests.
The tests now added are based upon work previously done for squizlabs/PHP_CodeSniffer#2189 / squizlabs/PHP_CodeSniffer#2456
_N/A_
> Util/Common: add tests for the suggestType() method

- src/Standards/PSR12/Docs/Functions/ReturnTypeDeclarationStandard.xml
The PR contains the documentation for the PSR12/Functions/ReturnTypeDeclaration sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#45-method-and-function-arguments).
Add documentation for the PSR12 ReturnTypeDeclaration sniff
Part of #148
> [Documentation] PSR12 - Return Type Declaration

- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
Test are failing badly
```
............................................................. 1708 / 2115 ( 80%)
............................................................. 1769 / 2115 ( 83%)
....................................fatal: not a git repository (or any parent up to mount point /dev)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
.fatal: not a git repository (or any parent up to mount point /dev)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
F........error: unknown option `cached'
usage: git diff --no-index [<options>] <path> <path>
Diff output format options
-p, --patch           generate patch
-s, --no-patch        suppress diff output
-u                    generate patch
-U, --unified[=<n>]   generate diffs with <n> lines …
```
> skip tests requiring git repository

- src/Filters/ExactMatch.php
Follow up on PR #202.
There has been some discussion in ticket #198 about the future names of the methods which are associated with the properties and as one of the methods will get a rename, this commit anticipates on that by renaming the property which will capture the return value of the method to be in line with that change.
As the property is `private`, this is a change which doesn't affect the API and is therefore non-breaking.
_N/A_
The method renames will be handled in separate PRs as those are in the public API. See #198, #199 and #203.
> Filter/ExactMatch: rename a private property

- src/Standards/PSR12/Docs/Files/ImportStatementStandard.xml
The PR contains the documentation for the PSR12/Files/ImportStatement sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements).
Add documentation for the PSR12 ImportStatement sniff
Part of #148
> [Documentation] PSR12 - Import Statement

- src/Standards/PSR12/Docs/Properties/ConstantVisibilityStandard.xml
The PR contains the documentation for the PSR12/Properties/ConstantVisiblity sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#43-properties-and-constants).
Add documentation for the PSR12 ConstantVisiblity sniff
Part of #148
> [Documentation] PSR12 - Constant Visiblity

- tests/Core/Ruleset/ExplainCustomRulesetTest.xml
- tests/Core/Ruleset/ExplainSingleSniffTest.xml
- tests/Core/Ruleset/ExplainTest.php
These additional tests test different aspects of the explain command functionality, as well as document the behaviour of the command.
_N/A_
> Tests/ExplainTest: expand the tests

- tests/Core/ErrorSuppressionTest.php
... to improve scannability of the test cases covered.
See #225
_N/A_
> Tests/ErrorSuppressionTest: various improvements

- tests/Core/Ruleset/Fixtures/Sniffs/SetProperty/AllowedAsDeclaredSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/SetProperty/AllowedViaMagicMethodSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/SetProperty/AllowedViaStdClassSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/SetProperty/NotAllowedViaAttributeSniff.php
- tests/Core/Ruleset/SetPropertyAllowedAsDeclaredTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaMagicMethodTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaStdClassTest.xml
- tests/Core/Ruleset/SetPropertyNotAllowedViaAttributeTest.xml
- tests/Core/Ruleset/SetSniffPropertyTest.php
With an eye on adding additional tests for the Ruleset class, which would require additional test fixtures, this commit renames the `Category` subdirectory to `SetProperty` to directly link the fixtures in that folder to the `SetSniffPropertyTest`.
It also removes the `SetProperty` prefix from the dummy sniffs in that folder as it is not necessary anymore what with the folder being renamed.
Includes making the necessary updates to the dummy sniffs and the tests to allow for the rename.
This commit adds the parameter name for each item in the data set in an effort to make it more straight forward to update and add tests as it will be more obvious what each key in the data set signifies.
Includes minor array normalization.
Includes making the data type in the docblock more specific.
_N/A_
> Tests/SetSniffPropertyTest: various improvements

- tests/Core/Tokenizer/BackfillReadonlyTest.inc
- tests/Core/Tokenizer/BackfillReadonlyTest.php
The token content for the "target token" of these tests is the same in most cases, but was explicitly provided in all cases.
This simplifies the data provider arrays by making the `$testContent` test parameters optional with a `'readonly'` default value, allowing for removing a significant number of the `$testContent` parameter values from the data providers.
Using named data sets makes debugging failing tests more straight forward as PHPUnit will display the data set name instead …
> Tests/BackfillReadonlyTest: use named data sets and other tweaks

- tests/Core/Tokenizer/AttributesTest.php
... to improve scannability of the test cases covered.
See #225
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight forward to update and add tests as it will be more …
> Tests/AttributesTest: use named data sets + activate a test

- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
The data for each set was previously passed as an array instead of as values, even though the number of array items was known and stable.
Fixed now.
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in …
> Tests/BackfillNumericSeparatorTest: simplify data sets + use named data sets

- tests/Core/Tokenizer/HeredocNowdocCloserTest.php
Follow up on #220 / commit 5aa4362 .
As the `tabWidth` setting is now available via the `AbstractMethodUnitTest`, the `initializeFile()` method no longer needs to be overloaded for this test.
Includes making the data type in the docblock more specific.
Includes fixing up …
> Tests/HeredocNowdocCloserTest: clean up + use named data sets

- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.inc
- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.php
Make the test marker names more descriptive.
... to improve scannability of the test cases covered.
See #225
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight …
> Tests/NamedFunctionCallArgumentsTest: various improvements

- tests/Core/Tokenizer/EnumCaseTest.php
These test cases already existed in the test case file, but were not being run as tests.
Fixed now.
Includes making the data type in the docblock more specific.
_N/A_
> Tests/EnumCaseTest: use named data sets + activate three extra tests

- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.inc
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.php
Make the test marker names more descriptive.
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight forward to update and add tests as it will be more obvious what each …
> Tests/UndoNamespacedNameSingleTokenTest: use named data sets

- tests/Core/Ruleset/RuleInclusionTest.php
This commit adds the parameter name for each item in the data set in an effort to make it more straight forward to update and add tests as it will be more obvious what each key in the data set signifies.
Includes making the data type in the docblock more specific.
_N/A_
> Tests/RuleInclusionTest: use named data within data sets

- tests/Core/Tokenizer/AnonClassParenthesisOwnerTest.php
- tests/Core/Tokenizer/ArrayKeywordTest.php
- tests/Core/Tokenizer/BackfillEnumTest.inc
- tests/Core/Tokenizer/BackfillEnumTest.php
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
- tests/Core/Tokenizer/BackfillFnTokenTest.php
- tests/Core/Tokenizer/BackfillMatchTokenTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/DefaultKeywordTest.php
- tests/Core/Tokenizer/DoubleQuotedStringTest.php
- tests/Core/Tokenizer/FinallyTest.php
- tests/Core/Tokenizer/GotoLabelTest.php
- tests/Core/Tokenizer/HeredocStringTest.php
- tests/Core/Tokenizer/NullsafeObjectOperatorTest.php
- tests/Core/Tokenizer/ScopeSettingWithNamespaceOperatorTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.php
Aside from adding the data set name, this commit also adds the parameter name for each item in the data set, this time in an effort to make it more straight forward to update and add tests as it will be more obvious what each key in the data set signifies.
Includes …
> Tests/Tokenizer/various: use named data sets

- CHANGELOG.md
This PR adds links to all issues in the 3.7.1 and 3.7.0 sections of the changelog. I also fixed a typo in a changelog entry.
Part of #244
> Add links to all issues in the 3.7.1 and 3.7.0 sections of the changelog

- CHANGELOG.md
Per https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/279#issuecomment-1894500366, this PR fixes some GitHub links that were using `issues` when they are actually PRs. The links were working due to a redirect, but it is preferable to use the canonical URLs.
Issue raised in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/279#issuecomment-1894500366
> Fix some links in the 3.7.2 changelog

- CHANGELOG.md
This PR adds links to all issues in the 3.6.2 and 3.6.1 sections of the changelog. Three typos were also fixed in a separate commit.
Part of #244
> Add links to all issues in the 3.6.2 and 3.6.1 sections of the changelog

- .github/community-cc-list.md
This adds the initial wider PHP_CodeSniffer community cc list file as proposed in #227.
_N/A_
Closes #227
> Add `community-cc-list.md` file

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
When a docblock comment is provided for a function parameter, but no valid type information is supplied\*, the error message (and code) from PHP_CodeSniffer is misleading. This pull request aims to fix this by introducing a new error code for these cases. This could be considered a breaking change as rulesets may need to be adjusted to accommodate this new error code.
\* Some editors will create boiler-plate docblocks like this, expecting the developer to write the correct information.
Additionally, while working on the above change, I noticed that in some cases an invalid suggestion of adding a type hint for this specific case was being provided. I have included a fix for this in this pull request.
Before this change, the following code would be annotated as 
2 | ERROR | Doc comment for …
> New error code for `Squiz.Commenting.FunctionComment`: `MissingParamType`

- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
See #58.
This commit _soft_ deprecates the sniffs with a `@deprecated` annotation. This will get a mention in the changelog.
Hard deprecation will follow in a future 3.x minor as per #188.
* The `Zend.Debug.CodeAnalyzer` sniff. The sniff will be removed in PHP_CodeSniffer 4.0.
> Zend.Debug.CodeAnalyzer: soft deprecate the sniff

- CHANGELOG.md
This PR adds links to all issues in the 3.6.0 section of the changelog. Three typos were also fixed in a separate commit.
Part of #244
> Add links to all issues in the 3.6.0 section of the changelog

- src/Standards/Generic/Sniffs/WhiteSpace/IncrementDecrementSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.php
This PR fixes the post-decrement error message when there is one or more newlines between the variable and the post-decrement operator.
The wrong variable was used to check whether the post-decrement and the variable were not on the same line, resulting in an incorrect error message. The error message should explicitly say that a newline was found.
Before this commit, the error message was:
```
Expected no spaces between $i and the decrement operator; 0 found
```
Now it is:
```
Expected no spaces between the decrement operator and $i; newline found
```
(`newline` instead of `0`)
Generic/IncrementDecrementSpacing: fix error message when one or more newlines are found between the variable and the post-decrement operator
Fixes #288
> Generic/IncrementDecrementSpacing: fix post-decrement error message

- CHANGELOG.md
This PR adds links to all issues in the 3.5.7 and 3.5.6 sections of the changelog. A few typos were also fixed.
Part of #244
> Add links to all issues in the 3.5.7 and 3.5.6 sections of the changelog

- phpunit.xml.dist
- src/Ruleset.php
- src/Runner.php
- src/Sniffs/DeprecatedSniff.php
- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Ruleset/Fixtures/Sniffs/Deprecated/WithLongReplacementSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Deprecated/WithReplacementContainingLinuxNewlinesSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Deprecated/WithReplacementContainingNewlinesSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Deprecated/WithReplacementSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Deprecated/WithoutReplacementSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/DeprecatedInvalid/EmptyDeprecationVersionSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/DeprecatedInvalid/EmptyRemovalVersionSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/DeprecatedInvalid/InvalidDeprecationMessageSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/DeprecatedInvalid/InvalidDeprecationVersionSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/DeprecatedInvalid/InvalidRemovalVersionSniff.php
- tests/Core/Ruleset/Fixtures/ruleset.xml
- tests/Core/Ruleset/ShowSniffDeprecationsEmptyDeprecationVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsEmptyRemovalVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidDeprecationMessageTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidDeprecationVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidRemovalVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsOrderTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsReportWidthTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.xml
There are quite a few sniffs slated for removal in PHPCS 4.0 - 45 so far, to be exact - and save for two sniffs which have received a deprecation mention in the changelogs, this has only been announced in issues (squizlabs/PHP_CodeSniffer#2448 + squizlabs/PHP_CodeSniffer#2471) in the Squizlabs repo and should therefore only be considered "known" to a very small group of people.
Increasing awareness of the upcoming sniff removals should allow for a smoother upgrade experience to PHPCS 4.0 for end-users.
Aside from use by PHPCS itself, this feature can also be used by external standards to signal sniff deprecations to _their_ end-users.
All in all, this feature should hopefully improve the end-user experience.
As per the notes in #188, the intention is for PHPCS itself to use this feature …
> ✨ Native handling of sniff deprecations

- src/Filters/ExactMatch.php
- src/Filters/GitModified.php
- src/Filters/GitStaged.php
Deprecate the `getBlacklist()` and `getWhitelist()` methods and introduce the ~~`getBlockedFiles()`~~ ++`getDisallowedFiles()`++ and `getAllowedFiles()` replacement methods.
When available in child classes, the ~~`getBlockedFiles()`~~ ++`getDisallowedFiles()`++ and `getAllowedFiles()` methods will take precedence over the deprecated `getBlacklist()` and `getWhitelist()` methods.
* Issue 198: The abstract `ExactMatch::getBlacklist()` and `ExactMatch::getWhitelist()` methods are deprecated and will be removed in the 4.0 release.
- In version 4.0, these methods will be replaced with abstract `ExactMatch::getDisallowedFiles()` and `ExactMatch::getAllowedFiles()` methods
- To make Filters extending `ExactMatch` cross-version compatible with both PHP_CodeSniffer 3.9.0+ as well as 4.0+, …
> Filters/ExactMatch: deprecate the `getBlacklist()` and `getWhitelist()` methods

- src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.1.inc
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.1.inc.fixed
Follow up on squizlabs/PHP_CodeSniffer#2826 which was fixed via squizlabs/PHP_CodeSniffer#2876.
The sniff explicitly only intends to handle _arbitrary_ parentheses and tries to avoid clashes with sniffs handling the parentheses spacing of function calls and language construct invocations.
This is done by the sniff bowing out early when the token before the open parenthesis is a token which can be used in a (variable) function call or one of a select list of reserved keywords.
The previous PR tweaked the "bowing out" to allow the sniff to operate on arbitrary parentheses which directly follow the close curly brace of a a previous scope.
The additional condition added was, however, not limited to `T_CLOSE_CURLY_BRACKET` tokens.
This has led to a new false positive: When a `die()`/`exit()` …
> Generic/ArbitraryParenthesesSpacing: improve handling of switch-case scope closers

- src/Standards/Generic/Docs/WhiteSpace/IncrementDecrementSpacingStandard.xml
This PR adds the XML documentation for the Generic.WhiteSpace.IncrementDecrementSpacing sniff.
Add XML documentation for the Generic.WhiteSpace.IncrementDecrementSpacing sniff.
Part of #148
> Generic/IncrementDecrementSpacing: add XML documentation

- src/Standards/PSR12/Docs/ControlStructures/ControlStructureSpacingStandard.xml
The PR contains the documentation for the PSR12/ControlStructures/ControlStructureSpacing sniff.
This PR will add the documentation for the above-mentioned sniff, according to the [official standard definitions](https://www.php-fig.org/psr/psr-12/#5-control-structures).
Note that some rules mentioned in the above definitions are covered by other rulesets. So they were not added to the documentation, as they are not a part of the Control Structure Spacing sniff.
Add documentation for the PSR12 ControlStructureSpacing sniff
Part of #148
> [Documentation] PSR12 - Control Structure Spacing

- .github/workflows/test.yml
The upstream issue appears to have been fixed. Let's try this again.
Re-does PR #172+ #173 and reverts PR #204.
_N/A_
Ref: actions/download-artifact#249
Fixes #208
> GH Actions: re-attempt upgrade actions/[upload|download]-artifact from 3 to 4

- tests/Core/Tokenizer/BackfillEnumTest.php
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
- tests/Core/Tokenizer/BackfillReadonlyTest.php
- tests/Core/Tokenizer/BitwiseOrTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/EnumCaseTest.php
- tests/Core/Tokenizer/FinallyTest.php
- tests/Core/Tokenizer/GotoLabelTest.php
- tests/Core/Tokenizer/ShortArrayTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.php
- tests/Core/Tokenizer/TypeIntersectionTest.php
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.php
Most Tokenizer tests first assert that the token `'code'` is correct and after that, that the token `'type'` is correct. When the first assertion fails, an error message like this will be displayed:
`Failed asserting that 357 is identical to 313.`
That's because the PHP native token constants are integers. And even if someone would memorize all token constant integers, the integer values are different depending on the PHP version being used. All in all, that makes error messages like the above hard to decipher.
To mitigate this, a number of the Tokenizer tests already used the `$msg` parameter for the `assertSame()` call.
This commit adds this `$msg` parameter to more assertions to make the failure messages actually useful.
Includes introducing an interim `$tokenArray` variable in a lot …
> Tests/Tokenizer: make failure messages more descriptive

- tests/Core/AbstractMethodUnitTest.php
The Core test suite is going to get at least one more test case and this new test case class will also need a `getTargetToken()` method.
To prevent having to duplicate the logic and needing to maintain it in multiple places, this commit introduces a `getTargetTokenFromFile()` method which takes a `$phpcsFile` parameter, which allows for the method to become `static`, which in turn allows for the method to be used by other test case classes.
The original `getTargetToken()` method still has the same functionality as before, it now just calls the `getTargetTokenFromFile()` method under the hood.
_N/A_
> AbstractMethodUnitTest: move getTargetToken() logic to static method

- tests/Core/Tokenizer/AbstractTokenizerTestCase.php
- tests/Core/Tokenizer/AnonClassParenthesisOwnerTest.php
- tests/Core/Tokenizer/ArrayKeywordTest.php
- tests/Core/Tokenizer/AttributesTest.php
- tests/Core/Tokenizer/BackfillEnumTest.php
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
- tests/Core/Tokenizer/BackfillFnTokenTest.php
- tests/Core/Tokenizer/BackfillMatchTokenTest.php
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
- tests/Core/Tokenizer/BackfillReadonlyTest.php
- tests/Core/Tokenizer/BitwiseOrTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/DefaultKeywordTest.php
- tests/Core/Tokenizer/DoubleArrowTest.php
- tests/Core/Tokenizer/DoubleQuotedStringTest.php
- tests/Core/Tokenizer/EnumCaseTest.php
- tests/Core/Tokenizer/FinallyTest.php
- tests/Core/Tokenizer/GotoLabelTest.php
- tests/Core/Tokenizer/HeredocNowdocCloserTest.php
- tests/Core/Tokenizer/HeredocStringTest.php
- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.php
- tests/Core/Tokenizer/NullsafeObjectOperatorTest.php
- tests/Core/Tokenizer/ScopeSettingWithNamespaceOperatorTest.php
- tests/Core/Tokenizer/ShortArrayTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.php
- tests/Core/Tokenizer/TypeIntersectionTest.php
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.php
Until now, code coverage was not being recorded for the Tokenizer tests due to the way the tests were set up.
This new `AbstractTokenizerTestCase` class is intended to fix this.
**Background info:**
* Code run in a `setUpBeforeClass()` method does not cause code coverage to be recorded.
* Code run in a `setUp()` method _does_ cause code coverage to be recorded.
Now, the `AbstractMethodUnitTest` test case class was originally set up to allow for testing the utility methods in the `File` class.
To do so in the most efficient way and to allow the tests to be fast, the file containing the code being used in the tests, is only tokenized once in a `setUpBeforeClass()` method.
Over time, when Tokenizer tests were being introduced, the `AbstractMethodUnitTest` class also started to be used by …
> Tests: fix recording code coverage for Tokenizer tests

- tests/Core/Tokenizer/AbstractTokenizerTestCase.php
- tests/Core/Tokenizer/ResolveSimpleTokenTest.inc
- tests/Core/Tokenizer/ResolveSimpleTokenTest.php
This adds a set of dedicated tests for the tokens handled via the `PHP::resolveSimpleToken()` method.
_N/A_
> Tokenizer/PHP::resolveSimpleToken(): add dedicated tests

- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.php
Split `ContextSensitiveKeywordsTest` as one part of these tests is about the PHP native context sensitive keywords and the other part is about PHPCS native tokens for certain keyword.
These things are handled in different parts of the `Tokenizer\PHP` class and, in part, need different `@covers` tags.
_N/A_
> Tests/Tokenizer: split `ContextSensitiveKeywordsTest`

- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.php
* If there would be a newline + indentation between a modifier keyword and the "class" keyword, the space between them would not be flagged as incorrect (should be one space).
* Along the same lines, if there would be a comment between the modifier keyword and the "class" keyword, the space between them would not be checked, let alone flagged.
Fixed now.
Includes additional tests.
* PSR2.Classes.ClassDeclaration : incorrect space between the last class modifier and the `class` keyword was not always flagged.
> PSR2/ClassDeclaration: bug fix - space before class keyword is not checked correctly

- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
PR squizlabs/PHP_CodeSniffer#3581 introduced support for PHP 8.1 intersection types.
_Note: the sniff, or PHPCS itself for that matter, currently does not (yet) support PHP 8.2 DNF types. Once support for DNF types has been added, this sniff will need a further update/fix._
For now, for the purpose of this sniff, intersection types should be skipped as they cannot contain the simple types for which the case is being checked by this sniff.
However, the check for whether a type is an intersection type or not was wrong. The `'*type_token'` key for each of these checks contains the stack pointer to the _first_ token in the type declaration, so the comparison with `T_TYPE_INTERSECTION` will always yield `false`.
This did not lead to false positives due to how the type is handled after that, …
> Generic/LowerCaseType: bug fix in intersection type ignore code

- src/Runner.php
As things were, a `phpcbf` run overruled the `Config::$reports` setting / `--report=...` CLI arguments to always only show the `Cbf` report.
As running the Performance report can also be useful for `phpcbf` (to find particularly slow fixers), I'm proposing to change the logic which overrules the reports setting for `phpcbf` to allow for displaying the `Performance` report as well (if requested).
* Performance report can now be used for a `phpcbf` run.
Related to #60
> Runner: allow the Performance report when running `phpcbf`

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/AnonClassParenthesisOwnerTest.inc
- tests/Core/Tokenizer/AnonClassParenthesisOwnerTest.php
- tests/Core/Tokenizer/BackfillReadonlyTest.inc
- tests/Core/Tokenizer/BackfillReadonlyTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
PHP 8.3 introduced readonly anonymous classes, fixing an oversight in the PHP 8.2 introduction of readonly classes.
As things were, for PHP 8.1+, the tokenizer would change the token code for the `readonly` keyword from `T_READONLY` to `T_STRING` in the "context sensitive keyword" layer, thinking it to be a class name.
And for PHP < 8.1, the readonly polyfill would ignore the token as it being preceded by the `new` keyword would be seen as conflicting with the "context sensitive keyword" layer, which meant it would not be re-tokenized from `T_STRING` to `T_READONLY`.
This commit fixes both.
Includes adding tests in a number of pre-existing test classes to cover this change.
* Added
* Support for PHP 8.3 readonly anonymous classes.
Related to #106
> PHP 8.3 | Tokenizer/PHP: add support for readonly anonymous classes

- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Classes/AnonClassDeclarationUnitTest.php
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
Sniff already handles this and handles it correctly.
Adds test for both plain readonly classes (PHP 8.2) as well as anonymous readonly classes (PHP 8.3).
Sniff already handles this and handles it correctly.
The underlying `PSR2.Classes.ClassDeclaration` sniff, which does the actual checking of the space between a potential modifier keyword and the `class` keyword, already handles this correctly (after squizlabs/PHP_CodeSniffer#3826 and #307).
Note: tests were only added to the PSR12 sniffs as that sniffs registers the `T_ANON_CLASS` token.
The `PEAR.Classes.ClassDeclaration` sniff and the `PSR2` and `Squiz` versions, which both extend the `PEAR` class, don't need tests as none of those listen for the `T_ANON_CLASS` token.
_N/A_
Related to #106
> PHP 8.3 | Add tests with readonly anonymous classes to various sniffs

- phpcs.xml.dist
- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Tokenizers/PHP.php
This commit adds the new sniff as introduced in #197 by @TimWolla to the PHPCS native ruleset and fixes the few conditions which were ambiguous in this codebase.
_N/A_
Also see #197
> CS: add the RequireExplicitBooleanOperatorPrecedence sniff to PHPCS native ruleset

- src/Config.php
Fixes an error in the documentation for the -s option, which says 'sniff codes' when the command actually outputs error codes.
Fixes #319.
> Fixed documentation for -s option.

- src/Standards/PSR12/Sniffs/Classes/ClassInstantiationSniff.php
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc.fixed
The sniff is supposed to ignore anonymous class instantiations completely as otherwise it could create a conflict between this sniff and the PSR12 sniff checking anonymous class declarations.
As things were, however, the sniff would add parentheses after the `new` keyword or after an attribute if an anonymous class was declared as `readonly`, as allowed since PHP 8.3.
Fixed now.
Includes minor simplification - the sniff would previously _jump over_ attributes attached to anonymous classes to get to the `class` keyword only to bow out later for anonymous classes anyway. Now, the sniff will bow out straight away when either an attribute, the `readonly` keyword or the `class` keyword for an anonymous class declaration is encountered.
As `readonly` cannot be used as class name and attributes …
> PHP 8.3 | PSR12/ClassInstantiation: allow for readonly anonymous classes

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/ArrayKeywordTest.inc
- tests/Core/Tokenizer/ArrayKeywordTest.php
- tests/Core/Tokenizer/BitwiseOrTest.inc
- tests/Core/Tokenizer/BitwiseOrTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.php
- tests/Core/Tokenizer/TypeIntersectionTest.inc
- tests/Core/Tokenizer/TypeIntersectionTest.php
- tests/Core/Tokenizer/TypedConstantsTest.inc
- tests/Core/Tokenizer/TypedConstantsTest.php
PHP 8.3 introduced typed OO constants, where the type is between the `const` keyword and the constant name.
All type variations are supported, including nullable types, union types, intersection types, with the exception of `callable`, `void` and `never`. `self` and `static` types are only allowed in Enum constants.
This PR adds support for typed OO constants in the Tokenizer layer of PHPCS.
The following issues had to be fixed to support typed constants:
1. Consistently tokenizing the constant _name_ as `T_STRING`, even if the name mirrors a reserved keyword, like `foreach` or a special keyword, like `self` or `true`.
2. Tokenizing a `?` at the start of a constant type declaration as `T_NULLABLE`.
3. Tokenizing a `|` and `&` operators within a constant type declaration as `T_TYPE_UNION` …
> PHP 8.3 | Tokenizer/PHP: add support for typed OO constants

- src/Standards/Squiz/Sniffs/Operators/IncrementDecrementUsageSniff.php
- src/Standards/Squiz/Tests/Operators/IncrementDecrementUsageUnitTest.inc
- src/Standards/Squiz/Tests/Operators/IncrementDecrementUsageUnitTest.php
As the Squiz/IncrementDecrementUsage sniff is looking for certain functional code patterns, the sniff should disregard whitespace and comments when looking for the relevant tokens to determine whether the code under scan contains the code pattern the sniff is looking for.
The sniff, however, does not do this correctly (in multiple places).
This commit fixes just one of these issues, as reported in #325.
For this particular issue, the `$startPtr` for the `findNext()` is incremented for each `while` loop, but the initial `$startPtr` was also incremented, which meant that if there was no whitespace after an equals sign, the first relevant token was being skipped over.
Fixed now.
This commit fixes the same issue as fixed in the previous commit, but now specifically for the …
> Squiz/IncrementDecrementUsage: various bug fixes - whitespace/comment tolerance

- tests/Standards/AbstractSniffUnitTest.php
This is one step closer to #300. The changes proposed in #300 are breaking as the test suite will start failing for cases where it currently does not. This pull request gives users of the test suite some information that there is a problem, before the breaking change gets introduced into 4.x.
Test-suite - Show warning when ".fixed" file not found
> Test-suite - Show warning when ".fixed" file not found

- src/Standards/Generic/Sniffs/PHP/LowerCaseConstantSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.php
Type declarations are explicitly not checked by this sniff.
PHP 8.3 introduces typed constants. This means that the sniff now also needs to ensure that it doesn't flag non-lowercase `true`/`false`/`null` in the type declaration for a constant.
Fixed now. Includes tests.
* Generic.PHP.LowerCaseConstant : support for typed class constants
Related to #106
> PHP 8.3 | Generic/LowerCaseConstant: add support for typed constants

- src/Standards/Generic/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.inc
- src/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.php
This sniff is specifically targeted at constant names.
PHP 8.3 introduces typed constants. This means that the sniff now needs to jump over a potentially declared constant type to get at the constant name.
Fixed now.
* Generic.NamingConventions.UpperCaseConstantName : support for typed class constants
Related to #106
Fixes squizlabs/PHP_CodeSniffer#3927
Closes squizlabs/PHP_CodeSniffer#3936
> PHP 8.3 | Generic/UpperCaseConstantName: add support for typed constants

- .github/CONTRIBUTING.md
- CHANGELOG.md
- README.md
- tests/Core/Config/ReportWidthTest.php
- tests/Core/Filters/AbstractFilterTestCase.php
- tests/Core/Tokenizer/DoubleArrowTest.php
- tests/Core/Tokenizer/ShortArrayTest.php
* Fix class description.
* Improve type specificity in docblocks.
* Add missing contributor link
Follow up on #243, just noticed I missed one which could be a link.
* Minor syntax fix.
Follow up on original import.
_N/A_
> Various small docs tweaks

- src/Standards/Generic/Tests/WhiteSpace/DisallowTabIndentUnitTest.php
- src/Standards/PSR12/Sniffs/Classes/AnonClassDeclarationSniff.php
- src/Standards/Squiz/Sniffs/PHP/InnerFunctionsSniff.php
- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Tokenizers/PHP.php
- tests/Core/AbstractMethodUnitTest.php
- tests/Core/File/GetClassPropertiesTest.php
- tests/Core/Filters/AbstractFilterTestCase.php
- tests/Core/Filters/Filter/AcceptTest.php
Minor CS fixes for things which have sneaked in.
_N/A_
> CS: various minor fixes

- src/Standards/Squiz/Sniffs/Commenting/ClosingDeclarationCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.inc.fixed
This pull request adds a missing `.fixed` file for an existing test for `Squiz.Commenting.ClosingDeclarationComment`.
While I was reviewing the automatically-created ".fixed" file (from `phpcbf`), I noticed a bug. I'm fixing that bug in this same pull request, but am happy to move that elsewhere if desired.
- `Squiz.Commenting.ClosingDeclarationComment` - no longer add extra newline when adding a missing comment
Related to #299
> `Squiz.Commenting.ClosingDeclarationComment` - add missing `.fixed` file for test-suite, and fix a bug found during

- tests/Core/Config/ReportWidthTest.php
- tests/Core/ErrorSuppressionTest.php
- tests/Core/File/IsReferenceTest.php
Initially to prevent issues with a few PHPUnit versions which were around in the early days of PHP 8.0, where these would accidentally be seen as parameter names.
So, as a best practice, when using keys in data sets, the keys should match the parameter names of the receiving test method.
An ulterior reason to make this change is that PHPUnit 11 will always treat the keys as parameter names, so this can be seen as a preparation step for allowing for PHPUnit 11 support in PHPCS 4.0.
_N/A_
Loosely related to #25
> Tests: data set keys should match parameter names

- bin/phpcbf
- bin/phpcs
- tests/bootstrap.php
Follow up after #4 and #39
The alternative path referred to in the bin scripts and the test bootstrap was specific for running via a PEAR install. This should no longer be needed (nor will this work).
_N/A_
> Remove more remnants of PEAR installation support

- autoload.php
- scripts/build-phar.php
... instead of using fully qualified global/PHP native classes inline.
And when there is no namespace, don't use fully qualified global class names.
Follow up on #347
_N/A_
> CS: always import all used classes [3]

- tests/Core/AbstractMethodUnitTest.php
- tests/Core/Tokenizer/AbstractTokenizerTestCase.php
For tests using the `AbstractMethodUnitTest` or `AbstractTokenizerTestCase` base classes the test case files only need to be parsed (tokenized), not processed (tokenized + sniffs being called).
While not a huge difference, changing the function call from `File::process()` to `File::parse()`, still shaves about 1/7 of the run time off the Core tests without this change having a detrimental effect on any of the tests.
_N/A_
> Tests/Core: performance improvement

- tests/Core/AbstractMethodUnitTest.php
- tests/Core/Tokenizer/AbstractTokenizerTestCase.php
Follow up on #275
While tests should always clean up after themselves, this little tweak at least prevents tests which set the `$_SERVER` global (and don't reset it after the test is finished) from influencing tests which use these abstract test cases.
_Explanation: the `$_SERVER` global is not automatically reset between tests by PHPUnit and the `Config` class _will_ read it out when it is set, so if one tests set the global and doesn't reset it, the next test with get a `Config` instance which will use the args set in the `$_SERVER['argv']` from the previous test._
_N/A_
> Tests: minor stability tweak

- CHANGELOG.md
This PR adds links to all issues in the 3.5.5 and 3.5.4 sections of the changelog. A few typos were also fixed.
Part of #244
> Add links to all issues in the 3.5.5 and 3.5.4 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 3.5.3 and 3.5.2 sections of the changelog. A few typos were also fixed.
Part of #244
> Add links to all issues in the 3.5.3 and 3.5.2 sections of the changelog

- src/Standards/Generic/Docs/PHP/RequireStrictTypesStandard.xml
This PR adds documentation for the Generic.PHP.RequireStrictTypes sniff.
Add XML documentation for the Generic.PHP.RequireStrictTypes sniff.
Part of #148
> Generic/RequireStrictTypes: add XML documentation

- src/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php
The BOM character must be the first character of the file. This means that this sniff only needs to check the file once, but its code was executed for each occurrence of the T_INLINE_HTML token.
As discussed in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/278#issuecomment-1911143720, this PR changes the sniff code to return the number of tokens in all of its exit points to ensure that PHPCS executes it just a single time per file.
I noticed that some sniffs return `$phpcsFile->numTokens` while others return `($phpcsFile->numTokens + 1)` to ignore the rest of the file. As far as I could check, returning the number of tokens is enough as the [code](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/8b83793a5ce336464b71859192691789fa2331ae/src/Files/File.php#L449) checks if the …
> Generic/ByteOrderMark: small performance improvement

- src/Standards/Squiz/Docs/Arrays/ArrayBracketSpacingStandard.xml
- src/Standards/Squiz/Docs/Classes/LowercaseClassKeywordsStandard.xml
- src/Standards/Squiz/Docs/Classes/SelfMemberReferenceStandard.xml
- src/Standards/Squiz/Docs/Commenting/DocCommentAlignmentStandard.xml
- src/Standards/Squiz/Docs/Commenting/FunctionCommentThrowTagStandard.xml
- src/Standards/Squiz/Docs/ControlStructures/ForEachLoopDeclarationStandard.xml
- src/Standards/Squiz/Docs/ControlStructures/ForLoopDeclarationStandard.xml
- src/Standards/Squiz/Docs/ControlStructures/LowercaseDeclarationStandard.xml
- src/Standards/Squiz/Docs/Functions/FunctionDuplicateArgumentStandard.xml
- src/Standards/Squiz/Docs/Functions/LowercaseFunctionKeywordsStandard.xml
- src/Standards/Squiz/Docs/Scope/StaticThisUsageStandard.xml
- src/Standards/Squiz/Docs/Strings/EchoedStringsStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/CastSpacingStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/FunctionOpeningBraceStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/LanguageConstructSpacingStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/ObjectOperatorSpacingStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/ScopeKeywordSpacingStandard.xml
- src/Standards/Squiz/Docs/WhiteSpace/SemicolonSpacingStandard.xml
This PR updates the documentation for the Squiz standard, correcting the indentation of the closing CDATA tags.
Normalise indentation of CDATA tags in documentation for Squiz standard
Per discussion in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/352#issuecomment-1961039186
> [Documentation] Squiz: normalise indentation of closing CDATA tags

- CHANGELOG.md
This PR adds links to all issues in the 3.5.1 and 3.5.0 sections of the changelog. A few typos were also fixed.
> Add links to all issues in the 3.5.1 and 3.5.0 sections of the changelog

- tests/Standards/AbstractSniffUnitTest.php
The `Fixer::generateDiff()` method uses `shell_exec()` with the `diff` command to generate a file diff.
Using this command is slow, in particular on Windows.
This commit introduces a preliminary check in the test logic to see if a diff is even needed and skips generating the diff if no differences are expected.
I don't know whether and if so, how much this will make a difference for *nix users, but on Windows, it makes a significant difference when running the sniff tests.
A run of just the sniff tests (`vendor/bin/phpunit tests/AllTests.php --filter Standards --no-coverage`) for PHPCS without this fix takes > 1 minute (~01.03.701 last time I ran it).
With this fix, the run time of the sniff tests is brought down to ~8 seconds.
So let's call this a quality of life improvement for all devs …
> Tests: improve performance of the sniff tests

- .gitattributes
- src/Fixer.php
- tests/Core/Fixer/Fixtures/GenerateDiffTest-BlankLinesAtEnd.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-BlankLinesAtEnd.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-BlankLinesAtStart.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-BlankLinesAtStart.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-LineAdded.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-LineAdded.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-LineRemoved.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-LineRemoved.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-NoDiff.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-NoTrailingWhitespace.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-NoTrailingWhitespace.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-TabsToSpaces.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-TabsToSpaces.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-VarNameChanged.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-VarNameChanged.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-WhiteSpaceAtEnd.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-WhiteSpaceAtEnd.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-WhiteSpaceAtStart.diff
- tests/Core/Fixer/Fixtures/GenerateDiffTest-WhiteSpaceAtStart.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest-WindowsLineEndings.inc
- tests/Core/Fixer/Fixtures/GenerateDiffTest.inc
- tests/Core/Fixer/GenerateDiffTest.php
These tests test the functionality and document the behaviour of the `Fixer::generateDiff()` method, with a particular focus on (trailing) whitespace handling in the diff as this was noted in the method itself as a potential point of failure.
Similar to #351 and #354, this is a change intended to make the test suite faster, in particular when running on Windows, as a quality of life improvement for contributing developers.
However, this change has the added benefit that the performance improvement will also be noticeable for users running PHPCS with the `diff` report, which also uses the `Fixer::generateDiff()` method.
On its own, this change makes running the test suite ~50% faster on Windows.
In combination with the other two changes, the difference is smaller, but still …
> Fixer: improve performance of generateDiff()

- src/Standards/Generic/Docs/PHP/DisallowRequestSuperglobalStandard.xml
- src/Standards/PSR12/Docs/Functions/NullableTypeDeclarationStandard.xml
This PR normalises CDATA tag indentation in sniff documentation.  
The original intention was to open separate PRs for changes to every standard, but it was primarily `Squiz` that was affected, which was addressed in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/361. These are the last few instances of incorrect indentation that I found across all other standards.
Normalise indentation of CDATA tags in sniff documentation.
Per discussion https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/352#issuecomment-1961039186
> [Documentation]: normalise indentation of CDATA tags in sniff documentation

- src/Standards/Squiz/Docs/WhiteSpace/SuperfluousWhitespaceStandard.xml
This PR adds documentation for the `Squiz.WhiteSpace.SuperfluousWhitespace` sniff.
Add documentation for the Squiz Superfluous Whitespace sniff
Part of #148
> [Documentation] Squiz: Superfluous Whitespace

- CHANGELOG.md
This PR adds links to all issues in the 3.4.2, 3.4.1, and 3.4.0 sections of the changelog. A few typos were also fixed.
> Add links to all issues in the 3.4.2, 3.4.1 and 3.4.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 3.3.2, 3.3.1, 3.3.0, and 2.9.2 sections of the changelog. A typo was also fixed.
> Add links to all issues in the 3.3.2, 3.3.1, 3.3.0 and 2.9.2 sections of the changelog

- src/Sniffs/AbstractScopeSniff.php
- src/Sniffs/AbstractVariableSniff.php
- src/Sniffs/Sniff.php
- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- src/Standards/Generic/Sniffs/Debug/CSSLintSniff.php
- src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php
- src/Standards/Generic/Sniffs/Debug/ESLintSniff.php
- src/Standards/Generic/Sniffs/Debug/JSHintSniff.php
- src/Standards/Generic/Sniffs/Files/EndFileNewlineSniff.php
- src/Standards/Generic/Sniffs/Files/EndFileNoNewlineSniff.php
- src/Standards/Generic/Sniffs/Files/ExecutableFileSniff.php
- src/Standards/Generic/Sniffs/Files/LineEndingsSniff.php
- src/Standards/Generic/Sniffs/Files/LineLengthSniff.php
- src/Standards/Generic/Sniffs/Files/LowercasedFilenameSniff.php
- src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
- src/Standards/Generic/Sniffs/VersionControl/GitMergeConflictSniff.php
- src/Standards/Generic/Sniffs/VersionControl/SubversionPropertiesSniff.php
- src/Standards/Generic/Sniffs/WhiteSpace/DisallowSpaceIndentSniff.php
- src/Standards/Generic/Sniffs/WhiteSpace/DisallowTabIndentSniff.php
- src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR2/Sniffs/Files/EndFileNewlineSniff.php
- src/Standards/Squiz/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Squiz/Sniffs/Files/FileExtensionSniff.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
- src/Standards/Zend/Sniffs/Files/ClosingTagSniff.php
Inspired by #360
As the tokens stack indexes are 0-based and a token count is 1-based, it is sufficient to return the token count to skip the rest of the file.
This commit updates various sniffs to use `return $phpcsFile->numTokens` instead of `return ($phpcsFile->numTokens + 1)`.
If a sniff file contains 50 tokens, the last `$stackPtr` will be 49, so returning `50` will already get us passed the end of the token stack and the `+ 1` is redundant.
_N/A_
> Various sniffs: simplify skipping the rest of the file + update docs about skipping rest of file

- src/Standards/Squiz/Docs/WhiteSpace/ScopeClosingBraceStandard.xml
This PR adds documentation for the `Squiz.WhiteSpace.ScopeClosingBrace` sniff.
Add documentation for the Squiz Scope Closing Brace sniff
Part of #148
> [Documentation] Squiz: Scope Closing Brace

- src/Standards/Squiz/Docs/WhiteSpace/MemberVarSpacingStandard.xml
This PR adds documentation for the `Squiz.WhiteSpace.MemberVarSpacing` sniff.
Add documentation for the Squiz Member Var Spacing sniff
Part of #148
> [Documentation] Squiz: Member Var Spacing

- src/Standards/Generic/Sniffs/CodeAnalysis/UselessOverridingMethodSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UselessOverridingMethodUnitTest.1.inc
- src/Standards/Generic/Tests/CodeAnalysis/UselessOverridingMethodUnitTest.6.inc
- src/Standards/Generic/Tests/CodeAnalysis/UselessOverridingMethodUnitTest.php
This PR implements the following improvements to the Generic.CodeAnalysis.UselessOverridingMethod sniff, which were suggested by @jrfnl in [this comment](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/250#pullrequestreview-1897345369) in another PR:
> 3. The "Skip for ... other method." block is now covered via the `differentParentMethod()` code snippet.
>     I can see a bug in the condition though - function/method names in PHP are case-insensitive.
>     There is currently no test where the function declaration name is not in the same case as the name used in the function call.
>     Such a test should be added and the code should be flagged as potentially useless override, which would need a small fix in the condition of that code block.
> 4. I'm missing a test where the …
> Generic/UselessOverridingMethod: small improvements to the sniff code

- CHANGELOG.md
This PR adds links to all issues in the 3.2.3, 3.2.1, and 3.2.0 sections of the changelog. There were no links in the 3.2.2 section of the changelog. Two typos were fixed. 
Versions 3.2.1 and 3.2.0 contained references to GitHub links outside of the `Fixed` section and I added links for those. Highlighting this in case I should not have added those links for whatever reason.
On a somewhat related note, I wonder if it was ever considered to add links to the GitHub issue/PR for all the changelog entries (when appropriate) and not only for bug fixes? I mean this for future versions of PHPCS. I personally find that it can be useful in some circumstances to have links to the discussion that originated a new feature for example.
Part of …
> Add links to all issues in the 3.2.3, 3.2.1 and 3.2.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 3.1.1 and 3.1.0 sections of the changelog.
> Add links to all issues in the 3.1.1 and 3.1.0 sections of the changelog

- src/Standards/Generic/Docs/Formatting/NoSpaceAfterCastStandard.xml
- src/Standards/Generic/Docs/Formatting/SpaceAfterCastStandard.xml
The aim of this PR is to fix the title of the XML documentation for the Sniff Generic.Formatting.NoSpaceAfterCastStandard. The current title states "Space After Casts" which seems different to the file name and the standard description.
Fixes #383
> Fixing the title of the Generic.Docs.NoSpaceAfterCastStandard docs

- CHANGELOG.md
This PR adds links to all issues in the 3.0.2, 3.0.1, 3.0.0, and 2.9.1 sections of the changelog. It also fixes a few typos and three links in other changelog sections that were modified in previous PRs.
> Add links to all issues in the 3.0.2, 3.0.1, 3.0.0 and 2.9.1 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 3.0.0RC4, 3.0.0RC3, 3.0.0RC2, 3.0.0RC1, and 3.0.0a1 sections of the changelog. It also fixes a few typos.
> Add links to issues in the 3.0.0RC4, 3.0.0RC3, 3.0.0RC2, 3.0.0RC1 and 3.0.0a1 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 2.9.0, 2.8.1, and 2.8.0 sections of the changelog. It also fixes a few typos.
> Add links to all issues in the 2.9.0, 2.8.1 and 2.8.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 2.7.1 and 2.7.0 sections of the changelog and fixes one typo.
Besides that, on a separate commit, I fixed all the issue links in the rest of the changelog that were not ordered by issue number.
> Add links to all issues in the 2.7.1 and 2.7.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 2.6.2, 2.6.1 and 2.6.0 sections of the changelog and fixes a typo.
Version 2.6.2 includes a link to the PEAR issue tracker. It seems that PHPCS issues reported in PEAR start with the ID 8834 (https://pear.php.net/bugs/search.php?cmd=display&package_name[]=PHP_CodeSniffer&status=All), and the greatest issue ID in the old GitHub repository up until now is 3942. So, it seems that the issue number can be used to determine whether a given issue in the changelog is a GitHub or PEAR issue.
> Add links to all issues in the 2.6.2, 2.6.1 and 2.6.0 sections of the changelog

- tests/TestSuite7.php
This should work for now. PHPCS 4.0 will remove the whole outdated TestSuite setup as per #25, so by that time, the problem is gone completely.
Ref: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
**Note**: the tests won't pass on PHP 8.4 yet as PHPUnit itself (and its dependencies) still need to release a version which fixes similar issues in PHPUnit itself.
Test framework: fix PHP 8.4 deprecation
> Tests: fix for PHP 8.4 deprecation of implicitly nullable types

- CHANGELOG.md
This PR adds links to all issues in the 2.5.1 and 2.5.0 sections of the changelog and fixes a typo.
> Add links to all issues in the 2.5.1 and 2.5.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 2.4.0 sectios of the changelog.
> Add links to all issues in the 2.4.0 section of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 2.3.4, 2.3.3, 2.3.2, 2.3.1, and 2.3.0 sections of the changelog and fixes a typo.
> Add links to all issues in the 2.3.4, 2.3.3, 2.3.2, 2.3.1 and 2.3.0 sections of the changelog

- CHANGELOG.md
Links in the link lists have to be unique and as all issue/PR sources (this repo, Squizlabs repo, PEAR repo) use numeric issue references, there will be duplicate/overlapping numbers at some point.
To prevent this, I'm proposing the following change:
* Links to _this repo_ will continue to use simple issue number links, i.e. `[#123]`. This will keep things most straight forward for new content being added to the changelog.
* Links to the _Squizlabs repo_ will get a `sq` prefix in the link reference. This means the link reference will need to be added where the link is used, i.e `[#123][sq-123]`.
* Links to the _PEAR repo_ will get a `pear` prefix in the link reference. Again, this means the link reference will need to be added where the link is used, i.e `[#123][pear-123]`.
This commit …
> Changelog: update link lists to prevent duplicate link definitions

- CHANGELOG.md
This PR adds links to all issues in the 2.2.0, 2.1.0, and 2.0.0 sections of the changelog
> Add links to all issues in the 2.2.0, 2.1.0, and 2.0.0 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 1.5.6, 2.0.0RC4, 2.0.0RC3 and 2.0.0RC2 sections of the changelog. It also fixes a typo.
> Add links to all issues in the 1.5.6, 2.0.0RC4, 2.0.0RC3 and 2.0.0RC2 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 1.5.5, 2.0.0RC1, 1.5.4, and 2.0.0a2 sections of the changelog and fixes a few typos.
> Add links to all issues in the 1.5.5, 2.0.0RC1, 1.5.4 and 2.0.0a2 sections of the changelog

- CHANGELOG.md
This PR adds links to all issues in the 1.5.3, 1.5.2, 1.5.1, and 1.5.0 sections of the changelog and fixes a typo. There were no issues mentioned in the 2.0.0a1 section.
> Add links to all issues in the 1.5.3, 1.5.2, 1.5.1 and 1.5.0 sections of the changelog

- .github/CONTRIBUTING.md
... to make navigating through the document more straight forward.
Refs: #227, #228
_N/A_
> CONTRIBUTING: add table of contents + note about cc list

- tests/Core/File/IsReferenceTest.inc
Closures use clauses only take plain variables, not complex variables, like properties or array keys.
In other words, this test case as-is, was a parse error.
For the purposes of this test, it makes no difference what type of variable is passed, so let's fix the test.
Related to #152
_N/A_
> IsReferenceTest: fix invalid test case

- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.php
Follow-up #369 - per @jrfnl  - see: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/369#issuecomment-1977425911
Fixes #
> Follow-up #369 - Squiz.Arrays.ArrayDeclaration for static

- CHANGELOG.md
This PR adds links to all issues in the remaining sections of the changelog. It also fixes a few typos. Contrary to what I did in previous PRs related to #244, here I did not read through all the text looking for typos. I only fixed the typos highlighted by my IDE as it would take a long time to read everything. I also opted to fix the typos in a separate commit that can be squashed before merging as the number of changes in this PR is much bigger than in previous PRs. I'm hoping that this will make the review process easier.
> Add links to all issues in the remaining sections of the changelog

- src/Standards/PEAR/Sniffs/WhiteSpace/ScopeClosingBraceSniff.php
- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc
- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc.fixed
- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.php
The `PEAR.WhiteSpace.ScopeClosingBrace` sniff could get into a conflict with itself when the scope closer was preceded by a PHP open tag and before that non-empty (i.e. non-indent) inline HTML.
In that case, the sniff would not recognize that the close brace was not on a line by itself, as the search for the last content before would disregard the non-empty HTML and would continue searching, which meant that the "last relevant content before" token would point to a token on a previous line.
This, in turn, then led to the sniff continuing on to the next error "Closing brace indented incorrectly", where the indent would now be incorrectly determined as `-1`, which in the fixer would lead to the original content and the replacement content being exactly the same, which created a fixer …
> PEAR/ScopeClosingBrace: prevent fixer conflict with itself

- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
While the `PSR2.Classes.ClassDeclaration` sniff did take partially/fully qualified names into account for interfaces being extended, it did not take _namespace relative_ interface name into account.
This led to a fixer conflict within the sniff, where the sniff would first add a space between the `namespace` keyword and the namespace separator (`SpaceBeforeName` fixer) and in a subsequent loop would remove that same space again as it would think it was a space before a comma (`SpaceBeforeComma` fixer).
Fixed now by adding support for namespace relative interface names in the `extends` checks.
Includes unit test.
While the `PSR2.Classes.ClassDeclaration` sniff did take partially/fully qualified names into account for interfaces being implemented, it did not take _namespace relative_ …
> PSR2/ClassDeclaration: support namespace relative names / prevent fixer conflict

- src/Files/File.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
This PR improves performance of the `File::getMethodProperties()` method and prevents incorrect return type information for closure `use` clauses containing invalid variable imports in the `use` clause (defensive coding).
Closure `use` statements can only import plain variables, not properties or other more complex variables.
As things were, when such "illegal" variables were imported in a closure `use`, the information for the return type could get mangled.
While this would be a parse error, for the purposes of static analysis, the `File::getMethodProperties()` method should still handle this correctly.
This commit updates the `File::getMethodProperties()` method to always skip over the complete `use` clause, which prevents the issue and improves performance as the same time (less token …
> File::getMethodProperties(): skip over closure use statements

- src/Standards/Generic/Tests/Debug/ESLintUnitTest.php
ESLint has released a new major which no longer supports the `.eslintrc.json` config format by default.
To still allow for that format, an `ESLINT_USE_FLAT_CONFIG` environment variable has to be set to `false`.
This change is causing the tests for the `Generic.Debug.ESLint` sniff to fail.
Setting the environment variable fixes this.
This is a test-only change for the following reasons:
* If end-users use this sniff, they are responsible for using the correct configuration for the version of ESLint they are using.
* The sniff is deprecated and preferably end-users should move away from using the sniff and run the tool directly.
* As the sniff is deprecated, no time has been spend to add support for the new ESLint configuration format to the sniff. A simple patch to add this support would …
> Tests - Generic/ESLint: fix test

- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.php
Yet another one in the fixer conflict series.
When running the `Squiz` standard over all test case files, a fixer conflict between the `Squiz.Classes.ClassDeclaration`, which extends the `PSR2.Classes.ClassDeclaration` sniff, and the `Squiz.Commenting.InlineComment` sniff was discovered via the tests in the `tests\Core\Tokenizer\UndoNamespacedNameSingleTokenTest.inc` file for a code sample like this:
```php
class MyClass
/* testExtendedFQN */
extends \Vendor\Level\FQN
/* testImplementsRelative */
implements namespace\Name,
/* testImplementsFQN */
\Fully\Qualified,
/* testImplementsUnqualified */
Unqualified,
/* testImplementsPartiallyQualified */
Sub\Level\Name
{}
```
The conflict essentially comes down to the `PSR2.Classes.ClassDeclaration` sniff adding a new line between an inline …
> PSR2/ClassDeclaration: bug fix - prevent fixer conflict

- src/Standards/Generic/Sniffs/CodeAnalysis/JumbledIncrementerSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
The `join()` function in PHP is an alias of `implode()`, so let's use the proper function name.
_N/A_
> CS: use `implode()` not `join()`

- src/Standards/Generic/Sniffs/CodeAnalysis/JumbledIncrementerSniff.php
The name of the sniff uses "Incrementer", while the error message uses "Incrementor". This feels inconsistent.
Based on some light research, both terms can be used interchangable, so I'm proposing to make the error message consistent with the sniff name, as changing the sniff name would be a breaking change.
Generic.CodeAnalysis.JumbledIncrementer: fix typo in warning message.
Seen while reviewing #385
> Generic/JumbledIncrementer: fix inconsistency

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/community-cc-list.md
- .github/pull_request_template.md
- CHANGELOG.md
- README.md
* Always use the `atx` style headers (`# ...`).
* Use consistent blank lines around headers.
* No trailing punctuation in headers.
* Every file should have a header.
* First header in a file should be an H1.
Note: the issue templates do not trigger this error as they use frontmatter with a `title` attribute. However, frontmatter is not supported for pull request templates.
* Use the same list markers throughout each document.
* Use consistent sublist indentation: each level should be indented by four spaces.
> Rationale: Some Markdown parsers will treat two blockquotes separated by one or more blank lines as the same blockquote, while others will treat them as separate blockquotes.
* No long lines within code blocks.
Rationale: to prevent a horizontal scrollbar.
* All codeblocks should …
> Docs: clean up markdown files

- .gitattributes
- .github/workflows/validate.yml
- .gitignore
- .markdownlint-cli2.yaml
- .remarkignore
- .remarkrc
Follow up on and depends on #449: this PR adds two markdown specific jobs to the `validate` workflow to ensure code style consistency and execute various QA checks, like a broken link and check and duplicate link check. 
This new check uses the NPM MarkdownLint-CLI2 package via the `DavidAnson/markdownlint-cli2-action` action runner from the same maintainer.
It executes a loose check for consistency and some common errors.
Some of the more annoying rules/rules which could impact display of markdown files on GitHub have been disabled.
All necessary configuration is contained in the `.markdownlint-cli2.yaml` file.
To run locally, install via:
```bash
npm install -g markdownlint-cli2
```
... and then run via:
```bash
markdownlint-cli2
```
Includes a problem matcher which _should_ allow for …
> GH Actions: add markdown lint + QA jobs

- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.php
Add silly number of extra tests to safeguard that the `true`/`false`/`null`/`self`/`parent` keywords, when used in type declarations, are correctly tokenized.
_N/A_
> OtherContextSensitiveKeywordsTest: add silly number of extra tests

- src/Standards/Generic/Sniffs/ControlStructures/DisallowYodaConditionsSniff.php
- src/Standards/Generic/Tests/ControlStructures/DisallowYodaConditionsUnitTest.inc
This PR changes the Generic.ControlStructures.DisallowYodaConditions sniff so that the null coalescing operator (`??`) does not trigger it.
Generic.ControlStructures.DisallowYodaConditions: null coalescing operator (`??`) should not trigger the sniff
> Generic/DisallowYodaConditions: `??` should not trigger the sniff

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
These two tests were testing multiple test cases, but not using a data provider, which means that if one of the test cases would fail, the ones after the failing test case wouldn't even be tested.
By using a data provider, that issue is avoided.
It also allows for simplifying some of the test code for the `testKeywordReturnTypes()` test which duplicated the logic for the `scopePositionTestHelper()` just to allow for custom error messages mentioning the test marker. This is no longer needed when each marker is tested individually via the data provider.
Since PHP 8.0, `false` and `null` can be included in a union return type.
As of PHP 8.2, both `true`, `false` and `null` can be used as a stand-alone return type.
The tokenizer layer handling arrow functions did not take this into account …
> Tokenizer/PHP: arrow function tokenization broken when true/false used in return type

- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
This was already handled correctly by the Tokenizer, but not safeguarded via tests.
_N/A_
> Tokenizer/PHP: add tests for arrow functions with intersection types

- CHANGELOG.md
To be released tomorrow or Wednesday, whenever I find the time.
> Changelog for the 3.9.2 release

- src/Standards/Squiz/Sniffs/Commenting/ClosingDeclarationCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.1.inc
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.php
As suggested by @jrfnl in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/340#issuecomment-1946387893, this PR changes the Squiz.Commenting.ClosingDeclarationComment sniff to require a closing declaration comment for traits as well.
Squiz.Commenting.ClosingDeclarationComment: closing declaration comments are now required for traits.
Suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/340#issuecomment-1946387893
> Squiz/ClosingDeclarationComment: add trait support

- src/Reporter.php
- src/Ruleset.php
- src/Util/Common.php
- tests/Core/Util/StripColorsTest.php
This commit introduces a new static `Common::stripColors()` method to allow for stripping CLI color codes from an arbitrary text.
Includes starting to use the function in a few places.
_N/A_ This method is intended for internal use.
> New Common::stripColors() method

- .github/workflows/validate.yml
Okay, so apparently, there is a long-standing bug in the Microsoft package deploy process which caused `apt-get update` to fail in the first half hour after Microsoft has deployed a package.
The failure looks like this:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```
As this only happens intermittently (after a MS package deploy), the chance of running into this bug are slim, but guess what: today I ran into it.
This change to the workflow is intended to prevent the next person running into this issue from having to waste time on figuring this out.
By splitting the "Install xmllint" step into two steps: one doing the `apt-get update` and one doing the …
> GH Actions: work around intermittent apt-get errors

- src/Config.php
- src/Util/Help.php
- tests/Core/Util/HelpTest.php
👉🏻 This PR depends on PR #445 .
This PR attempts to make the help information more informative and to improve the readability and findability of options.
This should be seen as a first step to address user concerns about difficulty in finding the options they are looking for and understanding how certain options work, like seen in the recent months in tickets #10/#294/#419, #248, #322, #415 and #434.
The format for the new screens is inspired by similar help screens as currently in use in various other typical CLI tools, like PHPUnit and PHPStan.
This includes the choice for the use of colours and which colours to use.
The option descriptions are based on the previously available option descriptions with some improvements where I deemed those appropriate.
I've elected to keep the …
> Config: revamp the help screen(s)

- tests/Core/File/IsReferenceTest.inc
- tests/Core/File/IsReferenceTest.php
> IsReferenceTest: add extra tests with intersection/DNF types

- CHANGELOG.md
- src/Files/File.php
- src/Standards/Generic/Docs/CodeAnalysis/EmptyPHPStatementStandard.xml
- src/Standards/Generic/Sniffs/CodeAnalysis/EmptyPHPStatementSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc.fixed
- src/Standards/PSR12/ruleset.xml
- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/Squiz/Sniffs/CSS/SemicolonSpacingSniff.php
- src/Standards/Squiz/Sniffs/Commenting/LongConditionClosingCommentSniff.php
- src/Standards/Squiz/Sniffs/Strings/EchoedStringsSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.1.inc
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.js
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.js.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc.fixed
Semicolon is the correct spelling based on the Oxford Dictionary and dictionary.com. This PR changes all occurrences found into `semicolon`
This PR is a split on changes proposed earlier in #457 but limiting to only fixing typos of the word `semicolon`. 
Sources for the correct spelling are:
- https://www.oed.com/dictionary/semicolon_n?tab=factsheet#23549945
- https://www.dictionary.com/browse/semicolon
- https://en.bab.la/dictionary/english/semicolon
- https://en.wikipedia.org/wiki/Semicolon
Also Google trends show a difference between `semicolon` and `semi-colon`
Correct semi-colon with semicolon
**N/A**
> docs: Correct semi-colon for semicolon (without dash)

- src/Files/File.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
Add support for PHP 8.2 DNF types to the `File::getMethodParameters()` method.
The `File::getMethodParameters()` method now supports DNF types.
Related #387, #461
> PHP 8.2 | File::getMethodParameters(): add support for DNF types

- src/Files/File.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
Add support for PHP 8.2 DNF types to the `File::getMethodProperties()` method.
The `File::getMethodProperties()` method now supports DNF types.
Related #387, #461
> PHP 8.2 | File::getMethodProperties(): add support for DNF types

- src/Files/File.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
Add support for PHP 8.2 DNF types to the `File::getMemberProperties()` method.
The `File::getMemberProperties()` method now supports DNF types.
Related #387, #461
> PHP 8.2 | File::getMemberProperties(): add support for DNF types

- src/Standards/Generic/Sniffs/Functions/CallTimePassByReferenceSniff.php
- src/Standards/Generic/Tests/Functions/CallTimePassByReferenceUnitTest.1.inc
- src/Standards/Generic/Tests/Functions/CallTimePassByReferenceUnitTest.php
This PR changes the Generic.Functions.CallTimePassByReference sniff to trigger an error when the parent, self, or static tokens are used to instantiate a class containing a variable passed by reference. In a separate commit, it also sorts alphabetically the list of tokens this sniff listens to.
Generic.Functions.CallTimePassByReference: flag call-time pass-by-reference when instantiating a class using parent, self, or static.
Suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/394#pullrequestreview-2015022891
> Generic/CallTimePassByReference: add support for self, parent and static

- autoload.php
An autoloader should always return a boolean value to indicate whether or not it has loaded a file. This allows for chaining autoloaders.
In most cases, the `return` statement in the autoloader already returned a boolean, this was the only exception.
_N/A_
> Autoloader: fix missing return value

- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
The `Generic.PHP.LowerCaseType` sniff needs to be updated to also handle non-lowercase types which are part of a DNF type declaration.
This commit updates the `processUnionType()` method to not only examine union types, but to examine all multi-token types and to do so in a slightly more performant manner and calls that method now for all multi-token type declarations.
Note: The method name now doesn't properly cover the functionality anymore, however, renaming the method would be a breaking change as the class is not `final` and the method not `private`.
The Generic.PHP.LowerCaseType sniff will now enforce lowercase keyword based types for types used in PHP 8.2+ DNF types.
Related #105, #387, #461, #471, #472, #473
Closes #105
> Generic/LowerCaseType: add support for examining DNF types

- src/Standards/PEAR/Tests/WhiteSpace/ScopeIndentUnitTest.inc.fixed
As mentioned in #299 there was a missing `.fixed` file for the unit test in  `src/Standards/PEAR/Tests/WhiteSpace/ScopeIndentUnitTest`. This PR adds the missing file.
Add missing `.fixed` file
Fixes #299
> fix: Add missing '.fixed' file for src/Standards/PEAR/Tests/WhiteSpace/ScopeIndentUnitTest

- src/Standards/Generic/Sniffs/ControlStructures/DisallowYodaConditionsSniff.php
- src/Standards/Generic/Tests/ControlStructures/DisallowYodaConditionsUnitTest.inc
- src/Standards/Generic/Tests/ControlStructures/DisallowYodaConditionsUnitTest.php
This PR improves code coverage for the Generic.ControlStructures.DisallowYodaConditions sniff. It adds a few tests for uncovered lines and documents using tests a few comparison operators that this sniff listens for that were not part of the tests before.
Besides that, this PR removes an unused variable, fixes a typo in a code comment, removes two unreachable variables, and renames a variable to make it more clear what it contains.
It is impossible to add code coverage for the line below using the current test framework and we should not remove it as external sniffs could be using the `DisallowYodaConditionsSniff::isArrayStatic()` and relying on the current behavior (returning `true` if the passed token index is not an array):
https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/30b3148b …
> Generic/DisallowYodaConditions: improve code coverage

- src/Standards/Generic/Sniffs/Arrays/ArrayIndentSniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
This PR improves the code coverage of the `Generic.Arrays.ArrayIndent` sniff and also implements the following minor improvements to the sniff code:
- ~~Use two different variables to hold the values of the expected indentation for array elements and array closing brace. Before, the same variable was being used, and its value modified, which can be confusing.~~
- Avoid unnecessary extra calls to ArrayIndent::processMultiLineArray() when fixing an array closing brace that is not placed on its own line.
- Remove `T_COMMA` from the list of tokens to ignore when looking for a token before the array opening brace. This was necessary in the past due to a bug `File::findStartOfStatement()` that has since been fixed.
I believe `T_DOUBLE_ARROW` can be removed from the …
> Generic/ArrayIndent: improve code coverage and implement a few small improvements to the sniff code

- src/Standards/Generic/Sniffs/Arrays/DisallowLongArraySyntaxSniff.php
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.1.inc
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.3.inc
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.php
This PR improves code coverage for the Generic.Arrays.DisallowLongArraySyntax sniff. It doesn't add any new tests as I couldn't think of any relevant missing tests. But it does remove an unreachable condition.
There are a few tests that I'm not sure if they belong to the sniff or not:
https://github.com/rodrigoprimo/PHP_CodeSniffer/blob/8f31c91c4a520d52ec97d819a7ce9d7da5b3fb40/src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.1.inc#L16-L22
They were added in ee0f59c and it seems this commit is about a change in the PHP Tokenizer, so I wonder if those tests should be moved to the PHP Tokenizer tests?
Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/146
> Generic/DisallowLongArraySyntax: improve code coverage

- src/Standards/Squiz/Docs/WhiteSpace/FunctionClosingBraceSpaceStandard.xml
This PR adds documentation for the `Squiz.WhiteSpace.FunctionClosingBraceSpace` [sniff](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/WhiteSpace/FunctionClosingBraceSpaceSniff.php).
- `bin/phpcs --standard=Squiz --generator=text --sniffs=Squiz.WhiteSpace.FunctionClosingBraceSpace`
- `bin/phpcs --standard=Squiz --generator=html --sniffs=Squiz.WhiteSpace.FunctionClosingBraceSpace`
Add documentation for the `Squiz.WhiteSpace.FunctionClosingBraceSpace` sniff.
Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/148
> [Documentation] Squiz.WhiteSpace.FunctionClosingBraceSpace

- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.js
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.js.fixed
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.php
This PR fixes a bug in the Generic.ControlStructures.InlineControlStructure sniff where it would not handle correctly `else if` statements when there is a comment between the `else` and `if` tokens.
The affected code was added in https://github.com/squizlabs/PHP_CodeSniffer/commit/18f98cc9a48bacf026c1a61208d03f6b88c2f69e to fix a similar bug when there is more than one whitespace between `else` and `if`, but it failed to consider that there might be comment tokens between `else` and `if`.
This change was originally part of PR #482, but it was decided to split it into multiple smaller PRs.
Generic.ControlStructures.InlineControlStructure: properly handle else if statements where there is a comment between else and if
> Generic/InlineControlStructure: fix error when handling `else if`

- src/Tokenizers/Comment.php
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/Comment/CommentTestCase.php
- tests/Core/Tokenizer/Comment/LiveCoding1Test.inc
- tests/Core/Tokenizer/Comment/LiveCoding1Test.php
- tests/Core/Tokenizer/Comment/LiveCoding2Test.inc
- tests/Core/Tokenizer/Comment/LiveCoding2Test.php
- tests/Core/Tokenizer/Comment/LiveCoding3Test.inc
- tests/Core/Tokenizer/Comment/LiveCoding3Test.php
- tests/Core/Tokenizer/Comment/LiveCoding4Test.inc
- tests/Core/Tokenizer/Comment/LiveCoding4Test.php
- tests/Core/Tokenizer/Comment/MultiLineDocBlockTest.inc
- tests/Core/Tokenizer/Comment/MultiLineDocBlockTest.php
- tests/Core/Tokenizer/Comment/PhpcsAnnotationsInDocBlockTest.inc
- tests/Core/Tokenizer/Comment/PhpcsAnnotationsInDocBlockTest.php
- tests/Core/Tokenizer/Comment/SingleLineDocBlockTest.inc
- tests/Core/Tokenizer/Comment/SingleLineDocBlockTest.php
The `Tokenizers\Comment` class did not have any tests associated with it. This commit fixes that and documents the existing behaviour.
Note: code coverage is as high as it can go, but not 100%. The reason for this, is the tokenizer debug statements, which are conditional on a verbosity flag, which is turned off for the tests.
Loosely related to #484.
This commit fixes an edge case tokenizer bug, where a - completely empty, not even whitespace - _block comment_, would be tokenized as a docblock.
Without this commit, the `/**/` code snippet was tokenized as:
```
8 | L07 | C  1 | CC 0 | ( 0) | T_DOC_COMMENT_OPEN_TAG     | [  4]: /**/
9 | L07 | C  5 | CC 0 | ( 0) | T_DOC_COMMENT_CLOSE_TAG    | [  0]:
```
With the fix applied, it will be tokenized as:
```
8 | L07 | C  1 | CC 0 | ( 0) | …
```
> Tokenizers/Comment: add tests + fix two edge case bugs

- CHANGELOG.md
> Changelog for the 3.10.0 release

- tests/Core/Tokenizer/PHP/DNFTypesTest.inc
- tests/Core/Tokenizer/Tokenizer/CreateParenthesisNestingMapDNFTypesTest.inc
This fixes a few unintentional parse/fatal errors in the test cases, which have no influence on the tests.
The file still also contains a number of _intentional_ parse/fatal errors, but those are deliberate to test specific syntax combinations.
> Tests/DNFTypesTest: fix a few unintentional errors

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/PHP/DNFTypesTest.inc
- tests/Core/Tokenizer/PHP/DNFTypesTest.php
The last parameter in a function call using named arguments could be confused with a return type by the tokenizer layer handling type declarations.
The net effect of this was that the close parenthesis of the function call would be retokenized to `T_TYPE_CLOSE_PARENTHESIS`, which is incorrect and would lead to sniffs incorrectly acting on that information.
Fixed now.
* The tokenizer could inadvertently mistake the last parameter in a function call using named arguments for a DNF type.
Fixes #504
Fixes #505
> Tokenizer/PHP: fix handling of "DNF look-a-likes" in named parameters

- src/Files/File.php
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
- tests/Core/File/FindStartOfStatementTest.inc
- tests/Core/File/FindStartOfStatementTest.php
The only "scopes" which can be nested within a `match` expression are closures, anonymous classes and other `match` expressions.
The `File::findStartOfStatement()` method has special handling for `match` expressions to find the start of a statement, but that special handling would also kick in when the `$start` token is within another scope nested within the `match`, while, in that case, the special handling is not needed and ends up resulting in an incorrect "start" pointer being returned, in most cases, even a "start pointer" which is _after_ the token for which the start of statement is requested, which should never be possible.
Fixed now by changing the special handling for `match` expressions to only kick in when the `match` expression is the _deepest_ nested scope.
Includes unit …
> File::findStartOfStatement(): 3 bug fixes related to `match` expressions

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/PHP/DNFTypesParseError1Test.inc
- tests/Core/Tokenizer/PHP/DNFTypesParseError1Test.php
- tests/Core/Tokenizer/PHP/DNFTypesParseError2Test.inc
- tests/Core/Tokenizer/PHP/DNFTypesParseError2Test.php
Follow up on PR #507. 
The `PHP::processAdditional()` method walks _back_ from the end of the file to the beginning.
With that in mind, and knowing that a type can never end on an open parenthesis, and an open parenthesis can never be seen in a type before the close parenthesis has been seen (at least for valid/non-parse error types), it makes no sense to trigger the type handling logic for open parentheses.
This should make the tokenizer slightly more efficient as (open) parentheses are used a lot in code ;-)
It also prevents the type handling layer from acting on these type of invalid/parse error types, while it previously would.
Includes tests safeguarding the behaviour of the type handling layer for this type of invalid/parse error types.
Of these tests, the type for the OO constant …
> Tokenizer/PHP: add extra hardening to the (DNF) type handling + efficiency improvement

- tests/Core/File/FindEndOfStatementTest.php
- tests/Core/File/FindStartOfStatementTest.inc
- tests/Core/File/FindStartOfStatementTest.php
Follow up on #502
This commit adds two QA tests to find potential bugs in the `File::find[Start|End]OfStatement()` methods.
1. It adds a test to ensure that the return value of `File::findStartOfStatement()` is never _after_ the passed `$start` stack pointer.
2. It adds a test to ensure that the return value of `File::findEndOfStatement()` is never _before_ the passed `$start` stack pointer.
The tests use the existing test code, but tests all non-empty tokens within the file.
Note: this test doesn't test that the stack pointer returned is _correct_, only that it _could_ be correct.
_N/A_
> File::find[Start|End]OfStatement(): add QA tests

- CHANGELOG.md
> Changelog for the 3.10.1 release

- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.1.inc
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
Follow up on #497, see https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/497#pullrequestreview-2063014326
PHP 7.4 introduced arrow functions.
While arrow functions being passed as an argument in a function call will not lead to false positives for this sniff - at least, I haven't been able to come up with a code sample in which it would [^1] -, skipping over them is still beneficial as it prevents unnecessary token walking.
Mind: the `scope_closer` of the arrow function _may_ be the comma separating the arrow function argument from the next function call argument, so we need to step one token back to prevent false negatives on those comma's.
Either way, this is now handled.
[^1]: comma's in arrow functions will always be nested within parentheses, within a short …
> Generic/FunctionCallArgumentSpacing: bug fix - ignore commas in nested match structures + minor efficiency tweak

- .github/workflows/label-merge-conflicts.yml
The `mschilde/auto-label-merge-conflicts` action runner is not actively maintained and is currently failing due to an unhandled deprecation notice. [Example](https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/runs/9380398878/job/25827454084)
I've evaluated the action runners available for this kind of thing and am proposing to switch to the `eps1lon/actions-label-merge-conflict` action runner, which should be a one-on-one replacement for the currently used functionality.
Additionally, that action has an option to post a comment when a conflict is detected as well as when the conflict has been resolved. While not currently used, this feature might be useful in the future.
Note: unfortunately, I won't be able to test the change until merged into the `master` branch, so this may need …
> GH Actions: update merge conflict check workflow

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
The issue tracker is for bug reports, feature requests and structural improvement proposals only. Not for support requests.
As per the contributing guide, those belong on StackOverflow or in the discussion forum, not in the issue tracker.
Let's see if this helps to reduce the noise of people posting support requests as "bugs".
This configuration file:
* Continues to allow blank issues to be opened.
* Adds an extra item to the issue template chooser pointing people with support questions to Discussions.
Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
_N/A_
> Issue templates: add extra checkbox + config file

- tests/Core/Util/Common/IsCamelCapsTest.php
- tests/Core/Util/Common/StripColorsTest.php
- tests/Core/Util/Common/SuggestTypeTest.php
- tests/Core/Util/Help/HelpTest.php
Move test classes into subdirectories mirroring the name of the class holding the code being tested.
Having the tests for each class in their own subdirectory should make it more straight forward to see what code is covered by tests.
_N/A_
> Tests/Util: move test classes into subdirectories

- src/Reporter.php
- src/Reports/Cbf.php
- src/Reports/Checkstyle.php
- src/Reports/Code.php
- src/Reports/Csv.php
- src/Reports/Diff.php
- src/Reports/Emacs.php
- src/Reports/Full.php
- src/Reports/Info.php
- src/Reports/Json.php
- src/Reports/Junit.php
- src/Reports/Notifysend.php
- src/Reports/Performance.php
- src/Reports/Report.php
- src/Reports/Source.php
- src/Reports/Summary.php
- src/Reports/VersionControl.php
- src/Reports/Xml.php
Follow up on PR #446
This commit adds detailed information about the array format `Report` classes receive in the `generateFileReport()` method to the `Report` interface and to the `Reporter::prepareFileReport()` method which prepares the data.
It also makes the parameter specification in the individual reports a little more specific and references the `Report` interface for further details.
As the array format is now documented, these unused variables are no longer needed for documentation purposes.
_N/A_
Related to https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/446#discussion_r1573936634
> Documentation: improve information about Report data format + remove unused foreach keys

- tests/Core/AbstractMethodUnitTest.php
These changes are similar to changes previously made in the same method in PHPCSUtils.
As things were, there could be a situation where the `getTargetTokenFromFile()` method did not find the delimiter comment. In that case, the method would search for the target token starting at token 0, which would generally lead to an incorrect token being identified as the target token.
This has now been fixed by verifying the outcome of the `findPrevious()` call and throwing an exception (causing the test to fail) when the delimiter comment was not found.
Along the same lines, when the target token would not be found, an exception will now be thrown as well.
_N/A_ (this is an internal use class, if external standards want to use a base class for testing utility methods, they should use the PHPCSUtils …
> AbstractMethodUnitTest: improve finding of target token

- src/Standards/Generic/Sniffs/WhiteSpace/DisallowSpaceIndentSniff.php
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.4.inc
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.php
This is the same fix for the `Generic.WhiteSpace.DisallowSpaceIndent` sniff as was previously made in squizlabs/PHP_CodeSniffer#3640 and #533 for the sister-sniff `Generic.WhiteSpace.DisallowTabIndent`.
---
Since PHP 7.3, heredoc/nowdoc closers may be indented. This indent can use either tabs or spaces and the indent is included in the `T_END_HEREDOC`/`T_END_NOWDOC` token contents as received from the PHP native tokenizer.
However, these tokens were not included in the tokens to look at for the `Generic.WhiteSpace.DisallowSpaceIndent` sniff, which could lead to false negatives.
Fixed now, includes tests.
And along the same lines as per #533:
* The error for space indentation of heredoc/nowdoc closers is not auto-fixable to prevent the fixer creating parse errors as the indentation of the …
> Generic/DisallowSpaceIndent: flag heredoc/nowdoc closer using space indent

- src/Standards/Squiz/Tests/Objects/ObjectInstantiationUnitTest.inc
Originally, this test was added in
[squizlabs/PHP_CodeSniffer#836](https://github.com/squizlabs/PHP_CodeSniffer/pull/836)
as part of testing for allowing keywords to be used in other contexts (like
function names). This has been superseded in [squizlabs/PHP_CodeSniffer#3484](https://github.com/squizlabs/PHP_CodeSniffer/pull/3484) to cover keywords used in different contexts in the core Tokenizer tests.
Live coding scenarios would not trigger this sniff as it only looks for
context before the 'new' keyword.
Remove an unneeded test from `Squiz/Objects/ObjectInstantiation` that is no longer needed.
The original check for `new` keyword used in other contexts is covered elsewhere in the core tokenizer tests.
It is not needed as a parse error test for live coding either, as this sniff only …
> Squiz/ObjectInstantiation: remove keyword context test

- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.3.inc
The PSR12.Operators.OperatorSpacing sniff has specific logic to avoid an out-of-bounds array offset access. Before now, there were no tests which covered this logic. This commit adds such a test. The sniff already handles this, so there are no changes required there.
This particular omission was detected by [infection/infection](https://github.com/infection/infection).
```diff
src/Standards/PSR12/Sniffs/Operators/OperatorSpacingSniff.php:104    [M] FalseValue
@@ @@
}
} else {
// Skip partial files.
-            $checkAfter = false;
+            $checkAfter = true;
}
if ($checkBefore === true && $tokens[$stackPtr - 1]['code'] !== T_WHITESPACE) {
$error = 'Expected at least 1 space before "%s"; 0 found';
```
No special remarks required in the changelog for this change. Perhaps a generic …
> Add test file for PSR12.Operators.OperatorSpacing

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.inc
The sniff did not recognize that when it would encounter a PHP close tag, it had reached a previous statement, leading to false positives for list assignments.
Fixed now. Includes tests.
Squiz.PHP.DisallowMultipleAssignments false positive for list assignments at the start of a new PHP block after an embedded PHP statement.
Fixes #537
> Squiz/DisallowMultipleAssignments: fix sniff walking back too far when going in/out of PHP

- src/Standards/Generic/Sniffs/CodeAnalysis/UselessOverridingMethodSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UselessOverridingMethodUnitTest.1.inc
- src/Standards/Generic/Tests/CodeAnalysis/UselessOverridingMethodUnitTest.php
This change prevents an edge-case false negative where a `parent::method()` function call statement ended by a PHP close tag without any "function content" of note after it, would not be reported as a useless overriding method.
Generic.CodeAnalysis.UselessOverridingMethod: prevent edge case false negative when the call to the parent method would end on a PHP close tag.
Related to #552
> Generic/UselessOverridingMethod: improve handling of PHP open/close tags between statements

- src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.php
This change prevents an edge-case false negative for a namespaced self reference, when the namespace declaration would be ended by a PHP close tag instead of the expected `T_SEMICOLON` or `T_OPEN_CURLY_BRACE`.
Includes unit test.
Squiz.Classes.SelfMemberReference: prevent edge case false negative when the namespace declaration would end on a PHP close tag.
Related to #552
> Squiz/SelfMemberReference: handle namespace declaration ending on PHP close tag

- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.php
Previously, there were no dedicated tests for the `CloseBraceSameLine` error.
Issue squizlabs/PHP_CodeSniffer#2621 added the `T_COMMA` token to the `$ignoreTokens` (without adding a test) to prevent a false positive for a anonymous class declaration nested within a function call.
That fix was later superseded by another fix for basically the same issue via squizlabs/PHP_CodeSniffer#2678, which excluded anonymous classes completely from the `CloseBraceSameLine` check.
This commit adds the test case from squizlabs/PHP_CodeSniffer#2621 and removed the redundant `T_COMMA` token as the test now confirms it is no longer needed.
In the original version of the sniff, only comments tokens after the close brace were ignored for the `CloseBraceSameLine` check.
Since then the sniff has received …
> PSR2/ClassDeclaration: add tests and remove some redundant code

- src/Reporter.php
- src/Standards/Generic/Sniffs/WhiteSpace/LanguageConstructSpacingSniff.php
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
- src/Standards/Zend/Tests/NamingConventions/ValidVariableNameUnitTest.php
- tests/Core/Util/Common/StripColorsTest.php
- tests/Core/Util/Common/SuggestTypeTest.php
Small doc fixes collected along the way.
_N/A_
> Documentation: various minor improvements

- .github/CONTRIBUTING.md
While for non-code contributions there were guidelines already about how to find issues to contribute to, for code contributions, this wasn't yet all that clear.
Hopefully the newly added section will help people to find an issues to work on in a more straight forward manner.
_N/A_
> CONTRIBUTING GUIDE: add section about finding issues to work on for code contributions

- tests/ConfigDouble.php
- tests/Core/AbstractMethodUnitTest.php
- tests/Core/Filters/AbstractFilterTestCase.php
... to prevent changes to the values of these for one test, influencing another test.
This is only a stability tweak, there are no existing tests affected by this issue at this time.
The `Config` class uses a number of static properties, which may be updated during tests. These were previously - prior to #275 - reset to their default values in the `AbstractMethodUnitTest::resetTestFile()` method, but this reset was inadvertently removed with the reasoning that, if all tests use the `ConfigDouble`, the reset would no longer be needed as the `ConfigDouble` resets on being initialized.
The flaw in this logic is that not all tests are guaranteed to use the `ConfigDouble`, which means that without the reset, the `Config` class may be left "dirty" after tests using the `ConfigDouble`, which …
> Tests: stability tweaks for the non-sniff tests

- tests/Core/Tokenizer/PHP/HeredocNowdocTest.inc
- tests/Core/Tokenizer/PHP/HeredocNowdocTest.php
- tests/Core/Tokenizer/PHP/HeredocParseErrorTest.inc
- tests/Core/Tokenizer/PHP/HeredocParseErrorTest.php
The PHP tokenizer contains logic to:
* Retokenize the start/end tokens for nowdocs from `T_(START|END)_HEREDOC` to `T_(START|END)_NOWDOC`;
* Retokenize the _contents_ of a heredoc/nowdoc to `T_HEREDOC`/`T_NOWDOC` tokens.
* Retokenize the start token from `T_START_(HERE|NOW)DOC` to `T_STRING` if the heredoc/nowdoc is unclosed;
* Ensure that each line in the contents has its own token.
This commit adds tests safeguarding and documenting this part of the tokenizer.
_N/A_
> Tokenizer/PHP: add tests for heredoc/nowdoc tokenization

- src/Tokenizers/Tokenizer.php
- tests/Core/Tokenizer/Tokenizer/HeredocNowdocOpenerTest.inc
- tests/Core/Tokenizer/Tokenizer/HeredocNowdocOpenerTest.php
_You learn something new every day :wink:_
While probably exceedingly rare to be found in actual codebases, the PHP tokenizer apparently allows for whitespace between the `<<<` and the heredoc/nowdoc identifier. See: https://3v4l.org/NUHZd
Both spaces as well as tabs are allowed. New lines are not allowed. Comments are also not allowed. See: https://3v4l.org/7PIEK
The PHPCS `Tokenizer` did not execute tab replacement on these tokens leading to unexpected `'content'` and incorrect `'length'` values in the `File::$tokens` array, which in turn could lead to incorrect sniff results and incorrect fixes.
This commit adds the `T_START_HEREDOC`/`T_START_NOWDOC` tokens to the array of tokens for which to do tab replacement to make them more consistent with the rest of PHPCS.
Includes unit tests …
> Tokenizer: apply tab replacement to heredoc/nowdoc opener

- src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.php
> The `namespace` keyword can both be used for namespace declarations as well as as an operator - "magic keyword" - to resolve to the current namespace.
> See: https://www.php.net/manual/en/language.namespaces.nsconstants.php#example-298
> This last case is not correctly taken into account when determining the current namespace, which leads to false negatives.
Fixed now.
Includes test.
Fixed: Squiz.Classes.SelfMemberReference: false negatives when namespace keyword used as operator was encountered between the namespace declaration and the OO declaration.
Fixes #553
> Squiz/SelfMemberReference: bug fix - false negative with namespace keyword as operator

- CHANGELOG.md
This PR fixes a small typo in the chagenlog.
> Fix small typo in the changelog file

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
Generic.PHP.LowerCaseKeyword: require lowercase anonymous class keyword
Generic.PHP.LowerCaseKeyword: require lowercase anonymous class keyword
> Generic.PHP.LowerCaseKeyword: require lowercase anonymous class keyword

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
The `Tokens::$contextSensitiveKeywords` token array was introduced in PHPCS 3.7.0 via PR squizlabs/PHP_CodeSniffer#3484.
PR squizlabs/PHP_CodeSniffer#3574 build onto that by removing the bulk of the target tokens from the `register()` method for the Generic/LowerCaseKeyword sniff in favour of using the predefined `Tokens::$contextSensitiveKeywords` token array.
The `T_EMPTY`, `T_EVAL`, `T_ISSET` and `T_UNSET` tokens were initially missing from the `Tokens::$contextSensitiveKeywords` array. This was fixed in PHPCS 3.7.1 via PRs squizlabs/PHP_CodeSniffer#3608 and squizlabs/PHP_CodeSniffer#3610.
This means those tokens no longer need to be explicitly added as targets for the Generic/LowerCaseKeyword sniff as they are now (and have been since PHPCS 3.7.1) inherited via the …
> Generic/LowerCaseKeyword: remove some redundant code

- src/Standards/Squiz/Sniffs/Functions/MultiLineFunctionDeclarationSniff.php
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.php
The sniff looks for `T_COMMA` tokens to find the start of the next parameter and skips over parenthesis sets and square brackets sets (like short arrays) to prevent mismatching on a `T_COMMA` which is not a parameter separator.
This logic did not take parameter attributes into account, which can contain multiple comma-separated attributes, so should also be skipped over.
Fixed now. Includes plenty of tests.
Also includes minor stability fix for the parentheses/square brackets skipping.
Notes:
* It could be argued that the sniff should use the `File::getMethodParameters()` method to do the parameter parsing instead. This could be done in a future iteration, but will need to be evaluated carefully for side-effects.
* This sniff extends the PEAR `FunctionDeclaration` sniff. It has been …
> Squiz/MultiLineFunctionDeclaration: bug fix - skip over attributes

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.1.inc
The sniff would try to find whether the first "relevant" variable found matches the start of the statement and if not, throw an error, but in the case of dynamic property access on objects stored in an array, the first "relevant" variable determination was off and would get stuck on the `]` close bracket of the array access.
Fixed now. Includes ample tests.
This should also make the sniff slightly more efficient for property access code snippets which the sniff already handled correctly.
Fixed `Squiz.PHP.DisallowMultipleAssignments false positive on assignments to variable property on object stored in array
Fixes #598
> Squiz/DisallowMultipleAssignments: bug fix - dynamic property assignment on object stored in array

- CHANGELOG.md
- README.md
> Changelog for the 3.10.3 release

- scripts/build-phar.php
The `E_STRICT` constant is deprecated as of PHP 8.4 and will be removed in PHP 9.0.
The error level hasn't been in use since PHP 8.0 anyway, so removing the exclusion from the `error_reporting()` setting in the `build-phar` script should make no difference in practice.
Ref:
* https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
_N/A_
> PHP 8.4 | build-phar: remove use of `E_STRICT`

- src/Standards/Squiz/Sniffs/ControlStructures/ForEachLoopDeclarationSniff.php
From what we can determine, this is a typographical error / mistake. It seems that the intention here was to use the same error code for both sides of this if/else block.
This inconsistency was detected as part of reviewing a fixer conflict with the PSR12 standard and the `src/Standards/Squiz/Tests/ControlStructures/ForEachLoopDeclarationUnitTest.inc` test file. See https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/152#issuecomment-2227504202 for full details on this conflict and https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/152#issuecomment-2255751041 for a decision on how to move forward / resolve the inconsistency.
Note that we are not fixing other inconsistencies in this sniff as doing so would have little return on investment. …
> Correct error code in Squiz.ControlStructures.ForEachLoopDeclaration

- src/Standards/Generic/Docs/WhiteSpace/HereNowdocIdentifierSpacingStandard.xml
- src/Standards/Generic/Sniffs/WhiteSpace/HereNowdocIdentifierSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/HereNowdocIdentifierSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/HereNowdocIdentifierSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/HereNowdocIdentifierSpacingUnitTest.php
New `Generic.WhiteSpace.HereNowdocIdentifierSpacing` sniff which forbids whitespace between the `<<<` and the identifier string in heredoc/nowdoc start tokens.
Includes fixer.
Includes XML docs.
New `Generic.WhiteSpace.HereNowdocIdentifierSpacing` sniff which forbids whitespace between the `<<<` and the identifier string in heredoc/nowdoc start tokens.
#585
> :sparkles: New `Generic.WhiteSpace.HereNowdocIdentifierSpacing` sniff

- .remarkrc
- CHANGELOG.md
- README.md
Fix a few URLs which were being redirected.
Includes:
* Replacing badges from poser.pugx.org with badges using img.shields.io.
* Adding PHP 8.4 to the "tested on" badge.
Looks like PEAR has added some type of rate limiting/DDOS protected which causes the check against dead URLs to fail due to time-outs.
Let's skip the typical user and bug report URLs for now to allow the builds to pass.
_N/A_
> README/Changelog: fix a few URLs which have changed

- src/Files/File.php
- src/Util/Common.php
- tests/Core/Util/Common/GetSniffCodeTest.php
Add initial set of tests for the `Common::getSniffCode()` method.
Related to [review comment in PR 446](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/446#discussion_r1573947430).
Previously, if an empty string was passed, the `Common::getSniffCode()` method would return `..`, which is just confusing.
This commit changes the behaviour to throw an `InvalidArgumentException` instead.
Includes making a potentially superfluous function call to the method conditionally (as it could hit the new exception).
Includes test.
Previously, if an invalid (incomplete) class name was passed, the `Common::getSniffCode()` method would return a garbled name, like `.Qualified.C`, which is just confusing.
This commit changes the behaviour to throw an `InvalidArgumentException` instead. …
> Common::getSniffCode(): add tests, more defensive coding and minor simplification

- .github/workflows/phpstan.yml
- .github/workflows/validate.yml
A number of reusable workflows have been introduced in the `PHPCSStandards/.github` repository for workflows used in multiple repos in this organisation, for which the steps are basically the same everywhere.
This will make maintenance of these workflows more straight-forward.
This commit switches the PHPStan workflow over to start using the reusable workflow.
_N/A_
> GH Actions/PHPStan: use reusable workflow

- src/Runner.php
- tests/Core/Util/Common/GetSniffCodeTest.php
Follow up to squizlabs/PHP_CodeSniffer#3716 and PR #524.
PR squizlabs/PHP_CodeSniffer#3716 improved the information provided in the error messages for `Internal.Exception`s with additional information about the source of the problem. This code uses the `Common::getSniffCode()` method to transform a sniff class name into a sniff code.
PR #524 changes how the `Common::getSniffCode()` method handles invalid input, i.e. it will now throw an exception when a class is passed which isn't a sniff (or sniff test).
In the context of this error handling, however, this new exception can easily be encountered when an `Abstract...Sniff` class contains the code which triggered the error - which would trigger the exception as it is not a sniff class.
This commit now adds some additional defensive coding …
> Runner::processFile()/error handling: add more defensive coding

- tests/Core/File/FindStartOfStatementTest.php
Follow up on #502
If a data set uses an associative array, the keys should match the test method parameter names exactly to prevent issues on PHPUnit 10/11 (name would be interpreted as named parameter and not match the actual parameter name).
_N/A_
> Tests/File::findStartOfStatement(): fix dataproviders

- .github/workflows/happy-new-year.yml
- .github/workflows/test.yml
Always quote variables to satisfy shellcheck rule SC2086: "Double quote to prevent globbing and word splitting".
Ref: https://www.shellcheck.net/wiki/SC2086
> GH Actions: always quote variables

- .remarkrc
- README.md
This partially reverts commit a57d5f9 after improvements upstream in the Remark no-dead-urls module.
Ref: remarkjs/remark-lint-no-dead-urls#54
This reverts commit c7a0f5a.
> Partially revert PR #621

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/PHP/DNFTypesTest.inc
- tests/Core/Tokenizer/PHP/DNFTypesTest.php
Follow up on #461, #507, #508
This commit intends to further improve the determination of whether tokens are part of a (return) type declaration which need special handling for the tokens or not.
It does more strenuous checking on any `T_COLON` encountered before the (potential) type, to try and determine with higher accuracy whether the colon indicates the start of a return type - in contrast to being a colon for a switch-case or a colon for an alternative syntax control structure.
The tests also include a test with `goto`. This would currently not trigger this code as the colon is tokenized as part of the goto label, but as the intention is to change that tokenization in PHPCS 4.0 (per issue #185), the test being there should safeguard that the PHPCS 4.0 change will not …
> Tokenizer/PHP: fix handling of "DNF look a likes" with switch/case and alternative control structure syntax

- src/Standards/Squiz/Docs/PHP/HeredocStandard.xml
Added documentation for the `Squiz.PHP.Heredoc` sniff
Related to #148
> Squiz/Heredoc: add XML doc

- src/Standards/Generic/Sniffs/WhiteSpace/HereNowdocIdentifierSpacingSniff.php
This commit adds metrics to the new `Generic.WhiteSpace.HereNowdocIdentifierSpacing` sniff to allow for collecting statistical information on how often spacing is found between the `<<<` and the doc ID.
_N/A_ covered by the changelog entry about the introduction of the sniff
Related #586
> Generic/HereNowdocIdentifierSpacing: add metrics

- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.1.inc
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.php
This PR improves code coverage for the `Generic.WhiteSpace.SpreadOperatorSpacingAfter` sniff.
Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/146
> Generic/SpreadOperatorSpacingAfter: improve code coverage

- src/Tokenizers/Tokenizer.php
- tests/Core/Tokenizers/Tokenizer/CreatePositionMapTabWidth0Test.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenMiscTest.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTabWidth1Test.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTabWidth2Test.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTabWidth4Test.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTabWidth5Test.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTest.inc
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTestCase.php
Add tests for the logic in the `Tokenizer::replaceTabsInToken()` method.
_N/A_
> Tokenizer::replaceTabsInToken(): add tests

- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/PHP/YieldTest.inc
- tests/Core/Tokenizers/PHP/YieldTest.php
.. to document and safeguard the existing behaviour.
Includes skipping one particular assertion on PHP 5.4.
This assertion would fail on PHP 5.4 with PHPUnit 4 as PHPUnit polyfills the `T_YIELD` token too, but with a different value, which causes the token 'type' to be set to `UNKNOWN`.
This issue _only_ occurs when running the tests, not when running PHPCS outside of a test situation, so this is not a real problem when running PHPCS on PHP 5.4.
For reference: the PHPUnit polyfilled token is declared in the PHP_CodeCoverage_Report_HTML_Renderer_File class in vendor/phpunit/php-code-coverage/src/CodeCoverage/Report/HTML/Renderer/File.php
By moving the check a `T_STRING` "yield" keyword up and always adjusting the token in the original token stream, we can remove a lot of duplicate code.
On …
> Tokenizer/PHP: add tests for tokenization of yield and yield from + minor bug fix

- tests/Core/Tokenizers/PHP/YieldTest.php
Improve the `YieldTest` by also verifying the _contents_ of the matched token. This is particularly needed for the `yield from` tests, where we need to verify that `yield` and `from` keywords are joined into one token on PHP 5.4-5.6.
_N/A_
> Tokenizers/YieldTest: improve tests

- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.3.inc
- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.4.inc
- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
This PR improves code coverage for the `Generic.PHP.DisallowShortOpenTag` sniff.
Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/146
> Generic/DisallowShortOpenTag: improve code coverage

- src/Standards/Generic/Sniffs/CodeAnalysis/RequireExplicitBooleanOperatorPrecedenceSniff.php
This PR reverts the changes to the `Generic.CodeAnalysis.RequireExplicitBooleanOperatorPrecedence` sniff introduced in https://github.com/PHPCSStandards/PHPCSExtra/pull/271/commits/7b38efb98c3383b84819a79f85828d517919f17d. The sniff's tests remain relevant, so they were preserved.
The original commit was added to fix false positives that the sniff was triggering when handling boolean operators inside a match (see https://github.com/PHPCSStandards/PHPCSExtra/pull/271#pullrequestreview -1634348864 and https://github.com/PHPCSStandards/PHPCSExtra/pull/271#issuecomment-1729104556 ). Example:
```php
match (true) {
$a || ($b && $c) => true,
};
```
I believe the false positive was actually caused by a bug in `File::findStartOfStatement()`. This bug was then fixed in …
> Generic/RequireExplicitBooleanOperatorPrecedence: remove unreachable condition

- src/Standards/Generic/Docs/Strings/UnnecessaryHeredocStandard.xml
- src/Standards/Generic/Sniffs/Strings/UnnecessaryHeredocSniff.php
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.1.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.2.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.2.inc.fixed
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.3.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.php
New `Generic.Strings.UnnecessaryHeredoc` sniff which encourages the use of nowdocs instead of heredocs, when there is no interpolation or expressions in the body text.
This sniff will hopefully help with the PERCS work as it intends to cover the following PER rule:
> A nowdoc SHOULD be used wherever possible. Heredoc MAY be used when a nowdoc does not satisfy requirements.
Includes fixer.
Includes XML docs.
Includes metrics.
New `Generic.Strings.UnnecessaryHeredoc` sniff which warns about heredocs without interpolation or expressions in the body text and can auto-fix these to nowdocs.
> :sparkles: New `Generic.Strings.UnnecessaryHeredoc` sniff

- src/Standards/Squiz/Sniffs/Commenting/PostStatementCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.php
As discussed in #560, this PR changes `Squiz.Commenting.PostStatementComment` to use a different error code when an annotation is found. This will allow ruleset maintainers to selectively exclude the flagging of trailing annotations from their ruleset. For example, for PHPCS itself, this will make it possible to use the `// @codeCoverageIgnore` annotation where needed.
An annotation is defined as any comment that starts with an optional space, followed by a `@` and any character, as long as it is not a whitespace. For now, only `//` comments are supported as this is the only type of comment supported by this sniff.
This change only applies to PHP code as support for JS will be dropped soon, and JS doesn't seem to follow the same convention of annotations starting with `@`. …
> Squiz/PostStatementComment: use a different error code for annotations

- phpcs.xml.dist
- src/Standards/Generic/Sniffs/ControlStructures/DisallowYodaConditionsSniff.php
- src/Standards/Generic/Sniffs/Strings/UnnecessaryHeredocSniff.php
- src/Util/Help.php
Includes adding a few PHPUnit annotations (as we now can after #627).
> PHPCS ruleset: allow for trailing annotations

- src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php
This PR fixes a minor bug in `Generic.NamingConventions .ConstructorName` when checking if a given class has a parent. The code was checking if the lowercase version of the value returned by `File::findExtendedClassName()` is `false`. The problem is that `strtolower()` never returns `false`. It always returns a `string`. Thus, the condition would never be evaluated as `true`, and the sniff would not bail at this point when a given class has no parent.
As far as I can check, this did not cause any issues to the sniff, even for invalid code, as there is not a scenario where a class method can have a `T_DOUBLE_COLON` token followed by a `T_STRING` token with an empty `content`. This is true even for empty strings as PHPCS includes the quotes in the `content`.
> Generic/ConstructorName: fix minor bug

- src/Standards/Generic/Docs/Arrays/ArrayIndentStandard.xml
This PR adds the XML documentation for the Generic.Arrays.ArrayIndent sniff.
I left some inline comments below highlighting decisions I made while creating this documentation that I'm not sure about.
Add XML documentation for the Generic.Arrays.ArrayIndent sniff.
Part of https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/148
> Generic/ArrayIndent: add XML documentation

- src/Util/Tokens.php
- tests/Core/Util/Tokens/GetHighestWeightedTokenTest.php
- tests/Core/Util/Tokens/TokenNameTest.php
Includes fixing the docs for the method as it didn't represent correctly the actual behaviour of the function.
_N/A_
> Util\Tokens: add tests

- src/Util/Timing.php
- tests/Core/Util/Timing/GetHumanReadableDurationTest.php
- tests/Core/Util/Timing/TimingTest.php
Includes minor fixes to the class documentation.
_N/A_
> Util\Timing: add tests

- src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/ConstructorNameUnitTest.inc
- src/Standards/Generic/Tests/NamingConventions/ConstructorNameUnitTest.php
When determining whether or not a "parent" constructor was being called using a call to a PHP4-style constructor, the sniff would only look at the _next_ token after a double colon, while the next token may be whitespace or a comment, which should be ignored.
Fixed now by making the sniff check for the _next non empty_ token instead.
When determining whether or not a "parent" constructor was being called using a call to a PHP4-style constructor, the sniff would only look at the _next_ token after a double colon, disregarding completely the class the method is being called on.
This would lead to false positives for method calls to other classes, which would just happen to have a method named the same as the class being extended.
This commit fixes this by verifying that the …
> Generic/ConstructorName: bug fix x 2

- src/Standards/Generic/Sniffs/Classes/DuplicateClassNameSniff.php
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.10.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.11.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.7.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.8.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.9.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.97.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.98.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.99.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.php
The `namespace` keyword can also be used as an operator, in which case, the sniff as it were would throw false positives.
The fix now applied for this incidentally also fixes a nasty bug which could throw the sniff into an eternal loop when an unfinished namespace statement was encountered during live coding.
**Note**: the unit test for the live coding situation has to be the last unit test file for this sniff so as to not influence the other tests. To that end, it has been numbered `99`.
A comment in a namespace declaration statement would throw the sniff off, leading to false positives and false negatives.
Fixed now.
Includes unit tests. Additionally, a unit test for classes declared within a scoped global namespace has also been added.
As things were, the sniff …
> Generic/DuplicateClassName: 4 bug fixes + performance improvement

- src/Util/Timing.php
- tests/Core/Util/Timing/GetHumanReadableDurationTest.php
This commit makes some tiny changes to how the run time is displayed:
* For "exactly 1 second", display `1 secs` instead of `1000ms`.
* For "exactly 1 minute", display `1 mins` instead of `60 secs`.
* When minutes are displayed, only display seconds when there are seconds to display (so no `# mins, 0 secs`).
Includes updating the tests to match.
Make the code more self-descriptive and use less "magic numbers" by declaring a couple of constants.
Minor improvements to the display of runtime information.
> Util\Timing::getHumanReadableDuration: improve time display

- phpcs.xml.dist
> PHPCS ruleset: make the file level `@author` tag optional

- src/Generators/Generator.php
As things were, the order in which sniff documentation was presented was dependent on the file system the sniffs were found on.
Fixed now by making the order logical and consistent.
* Documentation generated via the `--generator=...` feature will now be presented in natural order based on the sniff name(s).
This PR is a precursor to a series of PRs which will add a complete set of tests for the `Generator` feature.
> Generators: always present docs in alphabetical order

- src/Generators/HTML.php
No functional changes, just moving the CSS out of the function to a class constant.
_N/A_
This PR is a precursor to a series of PRs which will add a complete set of tests for the Generator feature.
> Generators/HTML: move static string to class constant

- src/Reports/Code.php
- src/Standards/Generic/Tests/WhiteSpace/HereNowdocIdentifierSpacingUnitTest.php
- tests/Core/Tokenizers/PHP/BackfillFnTokenTest.php
- tests/Core/Tokenizers/Tokenizer/CreateParenthesisNestingMapDNFTypesTest.php
Remove a few unused variables.
Minor fixes picked up along the way.
_N/A_
> CS/Docs: various small tweaks

- CHANGELOG.md
> Changelog for the 3.11.0 release

- .github/workflows/validate.yml
- src/Standards/Generic/Docs/WhiteSpace/HereNowdocIdentifierSpacingStandard.xml
- src/Standards/Generic/Docs/WhiteSpace/SpreadOperatorSpacingAfterStandard.xml
_Of course, found this issue when I'd already tagged the 3.11.0 release... oh well, guess I'll do another release later this week. At least with the new CI check, this won't be able to happen again._
Verify basic well-formedness of the XML docs.
* The `HereNowdocIdentifierSpacing` one contained unescaped special chars in an attribute (oops).
* The `SpreadOperatorSpacingAfter` line length did not conform (not found via the new CI check, but even so).
* Generic.WhiteSpace.HereNowdocIdentifierSpacing: fixed broken XML documentation 
Introduced in #586
> GH Actions/basics: add check for valid XML docs + fix two docs

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
Follow up on #663
Installing on PHP 5.4 with Composer on Windows runs into issues a lot of the time. Considering PHP 5.4 is ancient, let's just side-step this problem by using PHP 5.5.
Also see PHPCSStandards/composer-installer#213 for a little more context (yes, I've seen this issue before).
By default the `actions/checkout` runner uses the default git settings for line ending normalization, which is `true`.
For Windows, this means that `lf` line endings in files get converted to `crlf` on checkout.
In the case of PHPCS, this is problematic as this means that the integration test, which runs PHPCS over the code in PHPCS itself, would fail on hundreds of `End of line character is invalid; expected "\n" but found "\r\n"` CS errors.
Now, this line ending normalization can be undone via some …
> GH Actions: fiddle the PHP versions and line endings for Windows builds

- tests/Core/Util/Common/EscapeshellcmdTest.php
This adds tests for another method which has different behaviour between Windows and other OS-es.
_N/A_
> Common::escapeshellcmd(): add tests

- .github/CONTRIBUTING.md
- .github/workflows/test.yml
- src/Standards/Generic/Tests/Debug/CSSLintUnitTest.php
- tests/Core/Fixer/GenerateDiffTest.php
Follow up on #663
As part of PR #663, test runs on the Windows OS where introduced in CI/GH Actions.
While, generally speaking, all tests should run and pass on Windows too (and they do), for the purposes of CI, a specific test group named `Windows` was introduced to allow for selectively only running the tests which _may_ have a different outcome on Windows.
This group is used in the code coverage job to prevent the Windows builds taking forever.
While most PHPCS code is OS agnostic, there are a number of places in the code base where OS-based conditions are used.
This commit adds the `@group Windows` annotation to few more tests which hits these OS-based conditions to make sure those conditions are also hit in the code coverage builds.
This was in part already done in #663 and #677, but …
> Tests: add `@group Windows` to more tests + mention in CONTRIBUTING

- src/Util/Common.php
- tests/Core/Util/Common/GetSniffCodeTest.php
Sniff classes _should_ always follow the directory layout and naming conventions for sniffs as per the [Tutorial](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial).
However, before the change made in #524, when given a sniff class name for a sniff not following the naming conventions, the `Common::getSniffCode()` method would return a "sniff code" anyway. And even though the sniff code would be unconventional and not really valid, it would still _work_.
Since #524 this is no longer the case.
Given the above, the change from #524 breaks custom rulesets which use `<rule>` includes for individual sniff files not complying with the naming conventions. Breaking changes can only be made in majors, so this commit reverts the problematic part of the change from …
> Common::getSniffCode(): be more lenient about sniffs not following naming conventions

- tests/Core/Ruleset/RuleInclusionAbsoluteWindowsTest.php
Another follow up on #663
* Switching the test skipping from an inline condition to a PHPUnit annotation.
* Adding the `@group Windows` annotation to ensure this test will run for code coverage on Windows in CI.
_N/A_
> RuleInclusionAbsoluteWindowsTest: minor tweaks

- src/Generators/Generator.php
* Predefine the find/replace values as these don't change within the loop.
* Only call `str_replace()` once with arrays for find/replace.
_N/A_
This PR is part of a series of PRs which will add a complete set of tests for the Generator feature.
In this case, the code in this PR is covered by the tests added in #671.
> Generators/Generator: minor tweak

- tests/Core/Ruleset/RuleInclusionTest.php
- tests/Core/Ruleset/RuleInclusionTest.xml
Code executed during "before class" methods is not recorded for code coverage, while code executed in "before" methods is, but the "before" method is executed before _every_ test in the class, not just once before the tests in the class run.
So, to record code coverage, while still maintaining the performance benefits of only creating the Config and Ruleset objects once, the code still sets a static property and will only run if that static property has not been filled yet.
_N/A_
> RuleInclusionTest: record code coverage + one more test case

- CHANGELOG.md
> Changelog for the 3.11.1 release

- src/Generators/Markdown.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
As things were, the `Markdown` class changes the PHP error level (to prevent potentially getting a warning about the timezone not being set), but doesn't reset the error level back to the original error level once the "risky" code has been executed.
Fixed now.
This was previously already fixed for the `HTML` class in PR squizlabs/PHP_CodeSniffer#488
Includes adding a test to safeguard this for both classes. These tests need to be run in isolation so as not to get interference from the fact that the code is run in a test environment. I.e. without the `@runInSeparateProcess`, the test wouldn't fail when it should.
- Fixed: Markdown Generator could leave `error_reporting` in an incorrect state.
This PR is part of a series of PRs which will add a complete set of tests for the Generator …
> Generators/Markdown: reset error_reporting to original value

- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
Follow up on #688, which safeguarded/fixed that the `error_reporting` would be reset to its original value, this commit now adds tests to cover the original situation which caused the error silencing to be introduced in the first place.
_N/A_
This PR is part of a series of PRs which will add a complete set of tests for the Generator feature.
Also see: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/671.
> Generators HTML/Markdown: add extra test around error silencing

- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Ruleset/SetPropertyAllowedAsDeclaredTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaMagicMethodTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaStdClassTest.xml
- tests/Core/Ruleset/SetPropertyAppliesPropertyToMultipleSniffsInCategoryTest.xml
- tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForCategoryTest.xml
- tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForStandardTest.xml
- tests/Core/Ruleset/SetPropertyNotAllowedViaAttributeTest.xml
- tests/Core/Ruleset/SetPropertyThrowsErrorOnInvalidPropertyTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsEmptyDeprecationVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsEmptyRemovalVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidDeprecationMessageTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidDeprecationVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsInvalidRemovalVersionTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsOrderTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsReportWidthTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.xml
Small tweak to make sure the XML rulesets used for specific tests are directly linked to those tests via the XML ruleset name - this should make the tests more self-documenting.
_N/A_
This is a preliminary PR for a series of PRs expanding the tests for the `Ruleset` class.
> Tests/Ruleset/XML fixtures: add direct link between fixture and test using the fixture

- src/Generators/HTML.php
- tests/Core/Generators/Expectations/ExpectedOutputOneDoc.html
Makes no sense to me to have a "Table of Contents" in the HTML output when there is only one sniff with documentation.
- Changed: The Generator HTML output will now only contain a Table of Contents when there is more than one sniff with documentation.
Also see: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/671.
> Generators/HTML: only display a TOC when there is more than one doc

- src/Generators/Markdown.php
- tests/Core/Generators/Expectations/ExpectedOutputOneDoc.md
- tests/Core/Generators/Expectations/ExpectedOutputStructureDocs.md
- tests/Core/Generators/Fixtures/MarkdownDouble.php
- tests/Core/Generators/MarkdownTest.php
As things were, if the output of the Markdown doc generation would be used in a Markdown-friendly environment, the footer would not be interpreted as markdown and would not display correctly.
Fixed now by adding a blank line at the start of the footer.
Also see: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/671.
> Generators/Markdown: fix footer not parsing

- .github/CONTRIBUTING.md
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- phpunit.xml.dist
- tests/Core/Generators/GeneratorTest.php
- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
- tests/bootstrap.php
See the description of how this works in the `CONTRIBUTING` file for more information.
Includes adjustments to the GH Actions workflows to ensure the CBF specific tests are:
* Always run for the `quicktest` and "normal" test runs.
* Run for code coverage and that the code coverage reports are send in a way that they can be merged correctly.
Includes adding a "requires CS mode" condition to a few tests which would otherwise fail in CBF mode.
_N/A_
This is a preliminary PR for a series of PRs expanding the tests for the `Ruleset` class.
> Tests: set up mechanism to allow for testing CBF specific code

- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingInlineTest.xml
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
Add tests specifically aimed at testing the type handling of sniff properties set via a ruleset and via inline annotations.
The current tests document the existing behaviour, which contains some oddities, but fixing these could be considered a breaking change, so should wait until PHPCS 4.0.
_N/A_
> Ruleset: add tests for custom property type handling

- tests/Core/Ruleset/GetIgnorePatternsTest.php
- tests/Core/Ruleset/GetIgnorePatternsTest.xml
> Ruleset::getIgnorePatterns(): add tests

- tests/Core/Ruleset/GetIncludePatternsTest.php
- tests/Core/Ruleset/GetIncludePatternsTest.xml
> Ruleset::getIncludePatterns(): add tests

- .github/workflows/test.yml
The `concurrency` setting will cancel running workflows is a new push to the same branch is seen. This is useful to prevent unnecessary workflow runs (as the previous push was superseded, so the outcome is no longer relevant).
However, for the "main" branches (`master` and `4.0`), this workflow cancelling means that if multiple PRs are merged in succession, only the code coverage for the _last_ merge is recorded in Coveralls as the workflow runs on `master` for the previous merges will have been cancelled.
While in practice, it's not a biggie, it does make it more difficult to identify which commit/merge added or decreased code coverage.
With this in mind, I'm making a small change to the `concurrency` setting for the `test` workflow only to allow those to always finish when the workflow …
> GH Actions/test: allow concurrency for build against "main" branches

- tests/Core/Ruleset/AbstractRulesetTestCase.php
- tests/Core/Ruleset/RuleInclusionTest.php
- tests/Core/Ruleset/SetSniffPropertyTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
Introduce an abstract base TestCase with some helper methods specifically for tests testing aspects of the `Ruleset` class.
Start using the new `AbstractRulesetTestCase` in pre-existing `Ruleset` tests.
_N/A_
This is a preliminary PR for a series of PRs expanding the tests for the `Ruleset` class.
> Tests/Ruleset: introduce an abstract base TestCase and start using it

- tests/Core/Generators/AllValidDocsTest.xml
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleCase.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleCase.md
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleCase.txt
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleLength.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleLength.md
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleLength.txt
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/DocumentationTitleCaseStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/DocumentationTitleLengthStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/DocumentationTitleCaseSniff.php
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/DocumentationTitleLengthSniff.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
- tests/Core/Generators/TextTest.php
This adds dedicated tests for specific issues which can be encountered with the `title` attribute for `<documentation>` elements.
This initial set of tests for this documents the current behaviour. This behaviour may not always be the desired behaviour, in which case, this will be fixed in follow-up commits.
_N/A_
This PR is part of a series of PRs which will add a complete set of tests for the Generator feature.
> Generators: add tests for handling documentation titles

- src/Generators/HTML.php
- src/Generators/Markdown.php
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.txt
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.txt
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.txt
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.txt
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/StandardBlankLinesStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/StandardEncodingStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/StandardIndentStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/StandardLineWrappingStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/StandardBlankLinesSniff.php
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/StandardEncodingSniff.php
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/StandardIndentSniff.php
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/StandardLineWrappingSniff.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
- tests/Core/Generators/TextTest.php
This adds dedicated tests for specific issues which can be encountered in a `<standard>` XML element.
This initial set of tests for this documents the current behaviour. This behaviour may not always be the desired behaviour, in which case, this will be fixed in follow-up commits.
The default value for the `$flags` parameter of the `htmlspecialchars()` function changed in PHP 8.1.0.
Previously, the default was `ENT_COMPAT`. Now the default is `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401`.
The most notable differences are:
* Single quotes will be encoded.
* Invalid code unit sequences will be replace by a Unicode Replacement Character.
For consistent output cross-version PHP, it is advised to always explicitly pass the `$flags` parameter` and not rely on the default value.
Fixed now and …
> Generators: add tests for handling <standard> element + use consistent encoding cross-PHP 

- src/Util/Help.php
- tests/Core/Util/Help/HelpTest.php
Now PR #703 has unblocked testing of PHPCBF-only code, the `// @codeCoverageIgnore` annotation for this CBF-only code in the `Util\Help` class can be removed and this code can now be tested.
This commit adjusts the relevant test method to ensure that the CBF-only code is also tested.
_N/A_
> Util/HelpTest: test CBF-only code

- .github/workflows/build-phar.yml
This workflow is a safeguard to ensure that the PHAR files can be build against any of the supported PHP versions.
There are only a few files involved in building the PHAR files, so there isn't really any need to run this workflow for every PR and every merge. It only really needs to run when any of the involved files have changed.
Also, keep in mind that the PHAR which is distributed for releases is build on PHP 8.0 and will still be build in the `test` workflow for every PR and every merge, so the functionality of the distribution PHARs is still guaranteed either way.
_N/A_
> GH Actions: run phar building test more selectively

- .github/workflows/test.yml
Follow up on commit 755f0bc35a466e063f55fa7e7697a05e1289c644, which simplified the `custom_ini` setting for the code coverage builds, but did so incorrectly, meaning that code which needs the `short_open_tag=On` setting was no longer being recorded as covered.
Fixed now.
_N/A_
> GH Actions: fix snafu with code coverage

- .github/workflows/test.yml
Follow up on #710, which was added with the following reasoning:
> The `concurrency` setting will cancel running workflows if a new push to the same branch is seen. This is useful to prevent unnecessary workflow runs (as the previous push was superseded, so the outcome is no longer relevant).
>
> However, for the "main" branches (`master` and `4.0`), this workflow cancelling means that if multiple PRs are merged in succession, only the code coverage for the _last_ merge is recorded in Coveralls as the workflow runs on `master` for the previous merges will have been cancelled.
>
> While in practice, it's not a biggie, it does make it more difficult to identify which commit/merge added or decreased code coverage.
Let's try this again.
The previous attempt to prevent cancelling code coverage …
> GH Actions/test: allow concurrency for code coverage builds - take two

- src/Generators/Markdown.php
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonBlankLines.md
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonBlockLength.md
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonEncoding.md
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonLineLength.md
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleLineWrapping.md
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleWhitespace.md
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleCase.md
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleLength.md
- tests/Core/Generators/Expectations/ExpectedOutputOneDoc.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.md
- tests/Core/Generators/Expectations/ExpectedOutputStructureDocs.md
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedElementAtWrongLevel.md
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedOneElmAtWrongLevel.md
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedSuperfluousCodeElement.md
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedUnknownElement.md
As per the guidelines for cross-flavour markdown, it is best to always have a blank line below a header.
Ref:
* https://www.markdownguide.org/basic-syntax/#heading-best-practices
* Generators/Markdown: improved compatibility with the variety of available markdown parsers
Also see: #671 and #716.
> Generators/Markdown: add blank line after title

- src/Generators/HTML.php
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonLineLength.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.html
As things were, line breaks in a `<standard>` block were not respected for proper display in HTML.
This has now been fixed by:
* Recognizing a blank line after a text line as an indicator that the next line should be a new paragraph.
* In all other cases, a line break will be translated to an HTML line break.
* Generators/HTML: line breaks in `<standard>` blocks will now be respected when generating the HTML documentation.
Also see: #671 and #717.
> Generators/HTML: fix line break handling

- src/Generators/Text.php
Just removing some duplicate function calls.
_N/A_
> Generators/Text::printTitle(): minor tweaks

- src/Standards/Squiz/ruleset.xml
The Squiz ruleset was still using the deprecated property setting array format for the `Generic.Debug.ClosureLinter` sniff.
Fixed now.
_N/A_
Related to squizlabs/PHP_CodeSniffer#1665 and squizlabs/PHP_CodeSniffer#1983
> Squiz ruleset: update property format

- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.2.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.2.inc.fixed
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.php
Follow up on #707
When there are multiple tabs between the end of the function signature and the open brace, the "found: $length" part of the error message would refer to the number of tabs found.
This is inconsistent with other sniffs and confusing.
This commit fixes this, while still maintaining the previous behaviour - as introduced via https://github.com/squizlabs/PHP_CodeSniffer/commit/c4b9807cdb661635b71d5c1950e05c5189904a70 - of special casing the messaging for a single tab - independently of whether or not tab replacement is in effect.
Example for line 10 of test case file 2:
```
// Before:
Expected 1 space before opening brace; found 3
// After:
Expected 1 space before opening brace; found 11
```
Covered via pre-existing tests in both test case files + some additional new tests. …
> Generic/OpeningFunctionBraceKernighanRitchie: improve error message

- tests/Core/Ruleset/ProcessRulesetBrokenRulesetMultiErrorTest.xml
- tests/Core/Ruleset/ProcessRulesetBrokenRulesetSingleErrorTest.xml
- tests/Core/Ruleset/ProcessRulesetBrokenRulesetTest.php
> Ruleset::processRuleset(): add tests for handling of broken rulesets

- tests/Core/Ruleset/ProcessRuleInvalidTypeTest.php
- tests/Core/Ruleset/ProcessRuleInvalidTypeTest.xml
> Ruleset::processRule(): add test for handling of invalid `<type>` directives

- src/Generators/Markdown.php
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonLineLength.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.md
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.md
As things were, line breaks in a `<standard>` block were not respected for proper display in markdown.
As a side-effect of this, an indented text line in a `<standard>` block directly after a blank line, would unintentionally cause the markdown to display the line as a code block (via the indentation).
This has now been fixed by:
* Trimming indentation off each line.
* Adding two spaces to the end of each line as long as the line is not followed by a blank line or at the end of the standard block. The two spaces will ensure markdown will recognize the line break (in most markdown flavours).
Refs:
* https://www.markdownguide.org/basic-syntax/#paragraph-best-practices
* https://www.markdownguide.org/basic-syntax/#line-break-best-practices
* …
> Generators/Markdown: fix line break and indentation handling

- src/Generators/HTML.php
- src/Generators/Markdown.php
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleWhitespace.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleWhitespace.md
If there were multiple spaces next to each other in the title, this would be folded into one space for the display in HTML and Markdown.
This could mangle the code title, so fixed now.
Generators/HTML + Markdown: now better respect whitespace within a code sample title
Also see: #671 and #718.
> Generators HTML/Markdown: fix whitespace handling in code title

- tests/Core/Ruleset/ProcessRulesetShouldProcessElementTest.php
- tests/Core/Ruleset/ProcessRulesetShouldProcessElementTest.xml
Add tests specifically aimed at verifying `phpcs-only` and `phpcbf-only` attributes for elements within a `<ruleset>` are read and handled correctly.
_N/A_
> Ruleset: add tests for handling of `php[cs|cbf]-only` attributes within a `<ruleset>`

- tests/Core/Ruleset/ProcessRuleShouldProcessElementTest.php
- tests/Core/Ruleset/ProcessRuleShouldProcessElementTest.xml
Add tests specifically aimed at verifying `phpcs-only` and `phpcbf-only` attributes for elements within a `<rule>` are read and handled correctly.
_N/A_
> Ruleset: add tests for handling of `php[cs|cbf]-only` attributes within a `<rule>`

- tests/Core/Ruleset/ExpandSniffDirectoryTest.php
- tests/Core/Ruleset/ExpandSniffDirectoryTest.xml
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/.hidden/HiddenDirShouldBeIgnoredSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/AbstractSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/DummySniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/.hidden/HiddenDirShouldBeIgnoredSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/AbstractSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/.HiddenFileSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/.hidden/HiddenDirShouldBeIgnoredSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/DoNotFindMeSniff.txt
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/FindMeSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/IncorrectFileExtensionSniff.inc
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/MissingSniffSuffix.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryA/Subdir/IncorrectLevelShouldStillBeFoundSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryB/AnotherAbstractSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryB/FindMeSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/CategoryB/IncorrectFileExtensionSniff.php3
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Sniffs/IncorrectLevelShouldStillBeFoundSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Utils/NotInSniffsDirSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/Utils/SubDir/NotInSniffsDirSniff.php
- tests/Core/Ruleset/Fixtures/DirectoryExpansion/.hiddenAbove/src/MyStandard/ruleset.xml
> Ruleset::expandSniffDirectory(): add test

- tests/Core/Ruleset/SetSniffPropertyTest.php
I haven't been able to come up with a _real_ situation in which [this condition](https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/15db7232015d4fc1e023ef1eff0e65777a906f2c/src/Ruleset.php#L1476-L1479) could result in an early return - either via reading an XML ruleset or via inline `phpcs:set` annotation. Having said that, the method is `public` and is regularly used in test frameworks for external standards, so this code should remain in place.
This commit now safeguards the behaviour via a test.
_N/A_
> Ruleset::setSniffProperty(): add test for edge case / unused sniff

- tests/Core/Ruleset/Fixtures/InvalidNoSniffsDir/ruleset.xml
- tests/Core/Ruleset/ProcessRulesetAutoExpandSniffsDirectoryTest.xml
- tests/Core/Ruleset/ProcessRulesetExcludeSniffGroupTest.xml
- tests/Core/Ruleset/ProcessRulesetInvalidNoSniffsDirTest.xml
- tests/Core/Ruleset/ProcessRulesetMiscTest.xml
- tests/Core/Ruleset/ProcessRulesetTest.php
Mostly testing error handling and the handling of edge cases.
_N/A_
> Ruleset::processRuleset(): add various tests for things not already covered

- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.3.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.4.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.4.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.php
This PR fixes a false positive when handling a short list inside a `foreach` as reported in #527. I implemented the solution that @jrfnl described in this comment: https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/527#issuecomment-2189958063.
I included a separate commit with some tests that I wrote to improve test coverage for this sniff while I was familiarizing myself with its code. This is not a full code coverage commit. There are still some uncovered lines in this sniff, and those lines might be unreachable, but I have not investigated this at this time. There are also potentially some more relevant tests that could be added for lines that are already covered. This is also not addressed in this commit.
cc @VladaHejda in case you are available to test this PR and confirm if it …
> Squiz/ArrayDeclaration: fixes false positive when handling short lists inside `foreach`

- .github/workflows/build-phar.yml
- .github/workflows/reusable-build-phar.yml
- .github/workflows/test.yml
The workflows currently contain two jobs which build the PHAR files. In PHPCS 4.0, a third job will be added (in relation to 530), which will also need to build the PHAR files.
This means that any changes to the steps in these jobs would then have to be made in three places.
With this in mind, it makes sense to change the PHAR building to a reusable workflow, which can then be used by all three jobs. With this change, any changes to the steps of the job will only need to be made in one place.
This commit makes it so.
_N/A_
_Note: this PR should be merged just before the next release to verify that the attestation handling on tagging works correctly. This can't really be tested, other than when an actual tag is being created._
Closes #759
> GH Actions: change PHAR building to reusable workflow

- .github/release-checklist.md
- .github/workflows/verify-release.yml
- .remarkrc
While the actual releasing can not be fully automated (due to security concerns related to signing releases in a GHA workflow), there are a number of verification checks which are part of the release workflow, which _can_ be automated.
These checks were previously done as manual spot-checks. With the new workflow, they will now be executed structurally and automatically whenever a release is published on GitHub.
The checks which are automated via this workflow are as follows:
* For the PHAR files which can be downloaded from the GH "releases" page, the (unversioned) PHAR files published on the GH Pages website and the versioned PHAR files published on the GH Pages website for Phive (but which can also be downloaded manually), the following checks will now be run automatically:
- Is the …
> Publish release checklist and automate release verification

- tests/Core/Ruleset/RegisterSniffsTest.php
> Ruleset::registerSniffs(): add tests

- tests/Core/Config/GeneratorArgTest.php
In preparation for a PR to address #709, this PR adds tests to cover the current behavior of the code in the `Config` class that handles setting the `generator` property when the `--generator=` argument is passed in the command line.
Related to #709
> Config: add tests for the `--generator=` argument

- .github/workflows/verify-release.yml
Apparently, by default, the GH CLI doesn't show any output when run from a GH Actions step.
This can be confusing and it makes debugging the workflow harder as, in case of failure, it is unclear what the step failed on.
The `GH_FORCE_TTY` environment variable (set to any value) should enable the normal output for the GH CLI command, which should fix this.
Refs:
* https://github.com/cli/cli/issues/10047
* https://cli.github.com/manual/gh_help_environment
_N/A_
> GH Actions/verify-release: show output for release attestations

- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/InvalidSniffs/RegisterNoArraySniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/ValidSniffs/RegisterEmptyArraySniff.php
- tests/Core/Ruleset/PopulateTokenListenersRegisterNoArrayTest.xml
- tests/Core/Ruleset/PopulateTokenListenersTest.php
- tests/Core/Ruleset/PopulateTokenListenersTest.xml
- tests/Core/Ruleset/ProcessRulesetAutoExpandSniffsDirectoryTest.xml
- tests/Core/Ruleset/ProcessRulesetTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.xml
> Ruleset::populateTokenListeners(): add tests

- tests/Core/Ruleset/ConstructorNoSniffsTest.xml
- tests/Core/Ruleset/ConstructorTest.php
> Ruleset::__construct(): add tests

- tests/Core/Tokenizers/PHP/DNFTypesTest.inc
- tests/Core/Tokenizers/PHP/DNFTypesTest.php
Tests taken from https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/630#issuecomment-2418664762
Props @michalbundyra
Follow up on #630 / #632
> Tokenizer/PHP: add extra tests for DNF type tokenization

- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.php
While looking into a fixer conflict for the PSR12 standard regarding the `tests/Core/File/GetMethodParametersTest.inc` file, it was noted that there is a conflict between `Squiz.Functions.FunctionDeclarationArgumentSpacing` and `Squiz.WhiteSpace.SuperfluousWhitespace`.
To see this, run: `php bin/phpcbf --standard=PSR12 -v tests/Core/File/GetMethodParametersTest.inc`
With verbosity increased, we can see the conflict:
```
* fixed 1 violations, starting loop 47 *
Squiz.Functions.FunctionDeclarationArgumentSpacing:252 replaced token 1585 (T_FALSE on line 337) "false" => "false·"
=> Fixing file: 1/169 violations remaining [made 47 passes]...
* fixed 1 violations, starting loop 48 *
Squiz.WhiteSpace.SuperfluousWhitespace:212 replaced token 1586 (T_WHITESPACE on line 337) "·\n····" => "\n····" …
```
> Fix fixer conflict: `PSR12` / `Squiz.Functions.FunctionDeclarationArgumentSpacing`

- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/PHP/BackfillFnTokenParseErrorTest.inc
- tests/Core/Tokenizers/PHP/BackfillFnTokenParseErrorTest.php
During live coding or for code containing a parse error, it was possible for the tokenizer to run into an `Undefined array key "parenthesis_closer"` error when trying to verify arrow functions.
As this error happens during the tokenization, this resulted in PHPCS silently not scanning the file - without even showing the error notice.
Fixed now.
Tokenizer/PHP: prevent a potential error notice during live coding for unfinished arrow functions
> Tokenizer/PHP: prevent an "Undefined array key" notice during live coding

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.php
The fixer in Squiz.WhiteSpace.FunctionSpacing gets confused when there is a doc comment on the closing brace line:
Solves this fixer infinite loop
```php
/**
* foo.
*/
function a() {
}/**
* foo.
*/
function b() {
}
```
Squiz.WhiteSpace.FunctionSpacing: Fix the fixer when there is a doc comment on the function closing line.
https://www.drupal.org/project/coder/issues/3461139
> Squiz/FunctionSpacing: fixer is broken with doc comment on closing brace line

- tests/Core/AbstractMethodUnitTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/Tokenizers/AbstractTokenizerTestCase.php
- tests/Core/Tokenizers/PHP/OtherContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizers/PHP/OtherContextSensitiveKeywordsTest.php
This commit adds a test method to both the `AbstractMethodUnitTest` and the `AbstractTokenizerTestCase` classes to automatically verify that the case file in use by a child test class only contains unique test markers.
The actual logic for the test is in a custom, `static`, assertion `assertTestMarkersAreUnique()` to allow for calling the assertion directly if an additional test case file is tokenized for the test; and to prevent duplicating the logic in both test case classes.
Includes fixing a few test markers which this new test identified as duplicates straight off.
Changed: the `AbstractMethodUnitTest` and the `AbstractTokenizerTestCase` will now flag duplicate test case markers in a test case file.
Fixes #773
> Core tests: safeguard against duplicate test markers

- tests/Core/Ruleset/ProcessRulesetBrokenRulesetTest.php
I've updated the tests to support both `libxml < 2.12` and `>= 2.12`.
Fixes #767
> Tests: Fix libxml >= 2.12 compatibility

- .github/workflows/quicktest.yml
ℹ️ **PR title and description has been updated to reflect the latest state of the PR.**
--- 
GitHub has made Linux arm64 runners generally available and running tasks on these images instead of the traditional images can deliver up to a 40% performance boost.
Based on our testing with this, the performance benefit is minimal to non-existent in our test setup and as the code base contains no `arm64` specific code/conditions, there is also no _functional_ benefit to running the tests on `arm64`.
Having said that, having some test runs on `arm64` can serve as an early detection system in case code changes would be needed in the future.
With this in mind and after some discussion about this, this commit ONLY introduces `arm64` in the `quicktest` workflow which is run for branch pushes (with …
> GH Actions: speed up slow jobs by using Linux Arm64

- src/Standards/PEAR/Tests/Commenting/InlineCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/InlineCommentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Commenting/InlineCommentUnitTest.php
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.php
Based on some rumblings on the interwebs, I've done some investigating.
It was basically claimed that the emoji keycap sign for the hash character could be used for hash comments. Based on my investigation, this turns out to be **true**. Technical explanation: as the emoji keycap sign is a combined unicode character of which the first codepoint is the `#` character, the PHP tokenizer will see whatever comes after as a comment and tokenize it as such.
In a follow-up message, it was claimed that using the emoji keycap sign for the hash character could also be used for attributes. Based on my investigation, this (unsurprisingly) turns out to be **false**. Technical explanation: for attributes, the `#` sign and the `[` bracket need to be next to each without any characters between them for …
> PEAR/Squiz/InlineComment: document handling of emoji hash comments

- .github/workflows/test.yml
The `skip_tests` matrix condition is used to not duplicate test runs which are run in the code coverage jobs anyway. This condition was missing for the CBF mode test run, while that step is also run in the code coverage job.
Fixed now.
_N/A_
> GH Actions/test: add missing condition

- src/Standards/Squiz/Sniffs/WhiteSpace/ScopeKeywordSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.4.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
Done in a way to maintain the error line numbers for the rest of the file.
... as otherwise the test methods would be _unintentional_ parse errors.
Includes making the method names unique.
This commit adds a few of tests for syntaxes in which the target keywords could be used, which were so far not covered by tests:
* Tests with the `static` modifier keyword being used for closures.
* Tests with visibility keyword applied to class constants.
Bow out earlier when the sniff won't be able to action anything anyway (live coding/parse errors).
Squiz.WhiteSpace.ScopeKeywordSpacing: minor efficiency improvement
Follow up on https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/604#pullrequestreview-2274455160
> Squiz/ScopeKeywordSpacing: add additional tests

- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.php
This refactor has two purposes:
* Reduce code duplication.
* Prevent introducing even more code duplication when a new error code will be introduced in the next commit.
While incorrect spacing after a comma for constructor property promotion parameters would already be flagged and fixed by the sniff, the error message and code were incorrect/unclear.
Given the following test code:
```php
class PropertyPromotionSpacingAfterComma {
public function __construct(private string|int $propA, protected bool $correctSpace,  public MyClass $tooMuchSpace,readonly string $noSpace) {}
}
```
Previously the following would be reported:
```
198 | ERROR | [x] Expected 1 space between comma and type hint "MyClass"; 2 found
|       |     (Squiz.Functions.FunctionDeclarationArgumentSpacing.SpacingBeforeHint) …
```
> Squiz/FunctionDeclarationArgumentSpacing: handle constructor property promotion

- src/Standards/Squiz/Sniffs/Classes/ValidClassNameSniff.php
- src/Standards/Squiz/Tests/Classes/ValidClassNameUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ValidClassNameUnitTest.php
Noticed while working on something else.
If there would be a comment between the OO keyword and the declared name, the sniff could throw false positives with unhelpful error messages, like:
```
193 | ERROR | Class name "/*comment*/" is not in PascalCase format (Squiz.Classes.ValidClassName.NotCamelCaps)
194 | ERROR | Trait name "//comment" is not in PascalCase format (Squiz.Classes.ValidClassName.NotCamelCaps)
196 | ERROR | Interface name "// phpcs:ignore Stnd.Cat.SniffName -- just testing" is not in PascalCase format
|       | (Squiz.Classes.ValidClassName.NotCamelCaps)
199 | ERROR | Class name "CommentsShouldBeIgnoredValid/*comment*/" is not in PascalCase format (Squiz.Classes.ValidClassName.NotCamelCaps)
200 | ERROR | Interface name "annotations_should_be_ignored_InvalidName" is not in …
```
> Squiz/ValidClassName: bug fix - improve comment handling

- tests/Core/Ruleset/ProcessRuleShouldProcessElementTest.php
- tests/Core/Ruleset/ProcessRuleShouldProcessElementTest.xml
Safeguard that aspects of how `Internal` codes are processed can be changed and that these changes are applied correctly.
_N/A_
As requested via https://github.com/PHPCSStandards/PHP_CodeSniffer#801#discussion_r1954701449
> ProcessRuleShouldProcessElementTest: test changing `Internal` codes

- tests/Core/Ruleset/ExpandRulesetReferenceCaseMismatch1Test.xml
- tests/Core/Ruleset/ExpandRulesetReferenceCaseMismatch2Test.xml
- tests/Core/Ruleset/ExpandRulesetReferenceHomePathFailTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceHomePathTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceHomePathTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInternalIgnoreTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInternalStandardTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInternalTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceInvalidErrorCode1Test.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInvalidErrorCode2Test.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInvalidErrorCode3Test.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInvalidHomePathRefTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceMissingFileTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceUnknownCategoryTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceUnknownSniffTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceUnknownStandardTest.xml
- tests/Core/Ruleset/Fixtures/ExternalA/Sniffs/CheckSomething/ValidSniff.php
- tests/Core/Ruleset/Fixtures/ExternalA/ruleset.xml
- tests/Core/Ruleset/Fixtures/ExternalB/Sniffs/CheckMore/ValidSniff.php
- tests/Core/Ruleset/Fixtures/ExternalB/ruleset.xml
- tests/Core/Ruleset/Fixtures/FakeHomePath/src/MyStandard/Sniffs/Category/ValidSniff.php
- tests/Core/Ruleset/Fixtures/FakeHomePath/src/MyStandard/ruleset.xml
- tests/Core/Ruleset/Fixtures/Internal/Sniffs/Valid/ValidSniff.php
- tests/Core/Ruleset/Fixtures/Internal/ruleset.xml
Note: test coverage for the `Ruleset::expandRulesetReference()` method will still not be 100% even after the addition of these tests.
* There are some conditions which are specific to running PHPCS via a PHAR file. At this time, the tests are not run with a PHAR file, which means these lines cannot be covered via the tests.
* As for the other uncovered lines/branches: my fantasy ran out and I couldn't come up with a situation which would trigger that code. (_believe me, I've tried very very hard_)
Code archaeology (`git blame`) to find out why the code was introduced unfortunately didn't help.
This may indicate the code is redundant and can be removed, but this is not certain at this time and leaving the code in place is not harming anyone for now.
If over time, nobody can come up with a …
> Ruleset::expandRulesetReference(): add tests 

- src/Util/Help.php
Follow up on #447
I noticed while working on something else that some typical config options were missing from the list in the help text.
The difference between the previously listed ones and the additional options I'm now adding to the list, is that the original set of options are options which the `Config` class manages and for which it has a default value, while the additional options I'm now adding are used at runtime in various places by PHPCS, but do not have default value management in the `Config` class.
Whether default value handling of these options should be added to the `Config` class is up for debate, however, making it more discoverable that these options _exist_ and can be used, seems like an easy win for usability.
* `installed_paths` is probably the best known one and is …
> Help: update list of config options

- src/Generators/HTML.php
- src/Generators/Markdown.php
- src/Generators/Text.php
- tests/Core/Generators/Expectations/ExpectedOutputInvalidStandardNoContent.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidStandardNoContent.md
- tests/Core/Generators/Expectations/ExpectedOutputInvalidStandardNoContent.txt
No need to do any work on the `standard` text if there is no text. Nor is there a need to print an empty paragraph/extra blank lines in that case.
Generators: cleaner output based on the elements available
Also see: #671 and other PR with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) label.
> Generators: don't print standard when it's empty

- src/Generators/Generator.php
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitlePCREFallback.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitlePCREFallback.md
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitlePCREFallback.txt
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleEmpty.md
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleEmpty.txt
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleMissing.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleMissing.md
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleMissing.txt
- tests/Core/Generators/Fixtures/StandardWithDocs/Docs/Content/DocumentationTitlePCREFallbackStandard.xml
- tests/Core/Generators/Fixtures/StandardWithDocs/Sniffs/Content/DocumentationTitlePCREFallbackSniff.php
- tests/Core/Generators/GeneratorTest.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
- tests/Core/Generators/TextTest.php
When the documentation `title` attribute is missing, a title would still be included in the docs, but not contain any (useful) information.
Fixed now by falling back to the XML document file name and splitting the name into words.
Generators: gracefully handle missing title attribute
Also see: #671 and other PR with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) label.
> Generator::getTitle(): fall back to file name if title is missing

- src/Generators/HTML.php
- src/Generators/Markdown.php
The method in the parent class already contains the same code snippet, no need to duplicate.
_N/A_
Also see: #671 and other PR with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) label.
> Generators HTML/Markdown: remove some duplicate code

- src/Config.php
- tests/Core/Config/GeneratorArgTest.php
This PR improves how `Config::processLongArgument()` handles the `--generator` parameter to display a user-friendly message if an invalid generator name is passed. Before, an invalid generator name caused a fatal error.
I have checked, and it is not possible to add custom generators using third-party code (at least not without adding files to the PHPCS directory). This is because the `Runner` class only loads generators found in the `src/Generator/` directory:
https://github.com/PHPCSStandards/PHP_CodeSniffer/blob/3d14d004265ac6e38f3e161316cf51b7b4812414/src/Runner.php#L97-L98
So, it should be fine to limit the list of valid generators added in this PR to only the three generators provided by PHPCS.
Config: display a user-friendly message if an invalid generator name is passed in the …
> Config: display user-friendly message when invalid generator is passed

- src/Files/File.php
- tests/Core/File/GetDeclarationNameParseError1Test.inc
- tests/Core/File/GetDeclarationNameParseError1Test.php
- tests/Core/File/GetDeclarationNameParseError2Test.inc
- tests/Core/File/GetDeclarationNameParseError2Test.php
- tests/Core/File/GetDeclarationNameTest.inc
- tests/Core/File/GetDeclarationNameTest.php
The `function` keyword for a closure is normally tokenized as `T_CLOSURE`, but will be tokenized as `T_FUNCTION` in case of an unfinished closure declaration (no scope opener/closer).
For an unfinished closure with typed parameters, the `File::getDeclarationName()` method would incorrectly return the contents of the first `T_STRING` in the type declaration as if it were the name of the function.
Fixed now.
Includes test.
File::getDeclarationName(): prevent incorrect result for unfinished closures during live coding 
Loosely related to #152
> File::getDeclarationName(): prevent incorrect result during live coding 

- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.3.inc
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.4.inc
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.4.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.php
The `PEAR.Functions.FunctionDeclaration` sniff contained code to protect against a fixer conflict for unfinished closures, however, this code did not work correctly as an unfinished closure will generally also not have a function body, which "undoes" the protection via the scope opener check.
In other words, the fixer conflict still existed and would result in one part of the sniff trying to _add_ a space between the `function` keyword and the open parenthesis, while another part of the sniff would be removing that space again.
```
=> Fixing file: 1/1 violations remaining
PEAR.Functions.FunctionDeclaration:124 replaced token 11 (T_WHITESPACE on line 7) " (" => "("
=> Fixing file: 1/1 violations remaining [made 1 pass]...
* fixed 1 violations, starting loop 2 * …
```
> PEAR/FunctionDeclaration: prevent fixer conflict for unfinished closures/live coding

- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Readonly properties can be declared without visibility: https://3v4l.org/OS9hE The sniff did not take this into account.
Fixed now.
Squiz.WhiteSpace.MemberVarSpacing: allow for `readonly` properties
Loosely related to #152
> Squiz/MemberVarSpacing: allow for PHP 8.1+ readonly properties

- src/Generators/Text.php
No need for multiple calls to `str_replace()` when a single call will do.
There's absolutely no need for custom word-wrapping logic when PHP contains a function which can do this perfectly well.
_N/A_
Also see: #671 and other PR with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) label.
> Generators/Text: various minor code simplifications

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
This PR fixes a small typo in the EmbeddedPhpSniff::reportEmptyTagSet() docblock that I found while reviewing #833.
> Squiz/EmbeddedPhp: fix small typo in the reportEmptyTagSet() docblock

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.1.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.25.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.25.inc.fixed
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.php
For multi-line PHP snippets, the `Squiz.PHP.EmbeddedPhp` sniff expects the open and close tag to each be on their own line. For single-line PHP snippets, it does not.
Now, the sniff already handled a close tag of a previous multi-line snippet and the open tag of a next multi-line snippet being on the same line correctly and prevented a fixer conflict for that, but it did not correctly handle the open tag of a multi-line snippet being on the same line after a single-line PHP snippet.
In that case, it would not recognize that the open tag had to be moved to its own line and it would also calculate the expected indent for both the PHP open tag as well as the first line of the content within the multi-line snippet incorrectly, which in turn would lead to fixer conflicts with the …
> Squiz/EmbeddedPhp: bug fix - fixer conflict with itself

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.1.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.1.inc.fixed
The `Squiz.PHP.EmbeddedPhp` sniff expects no blank lines before the PHP close tag.
This rule can, however, conflict with sniffs enforcing blank lines after a class or function.
The sniff already contains protection against this conflict, but that protection did not take potential trailing comments after the close curly, like `//end class`, into account.
Fixed now.
Includes test.
Squiz.PHP.EmbeddedPhp: no new line before close tag was incorrectly enforced when a preceding OO construct or function had a trailing comment after the close curly
Related to #152
> Squiz/EmbeddedPhp: bug fix - prevent fixer conflict

- src/Reports/Cbf.php
Modifies the output of `phpcbf` when the exiting without fixing any errors to show a message indicating that the reasons was due to no coding standards violations in the code base.
The purpose is to make it clearer to developers running `phpcbf` that the reason no errors were fixed is because there were none to fix. 
I haven't been able to find tests for the `phpcbf` exit messages (searching for the phrase "No fixable errors were found") so I haven't added tests for this change. Please do point me to the relevant location if I have missed something.
_Edit: I've pushed a change to the message based on a discussion on the ticket. As/if further input arrives, I'll make any changes as required._
PHPCBF exits with the message `[INSERT FINAL MESSAGE HERE]` when no CS violations exist in the …
> PHPBCF: Show `no errors were found` when there are no errors to fix.

- src/Ruleset.php
- src/Runner.php
- tests/Core/Ruleset/ConstructorTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceHomePathTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceTest.php
- tests/Core/Ruleset/PopulateTokenListenersTest.php
- tests/Core/Ruleset/ProcessRuleInvalidTypeTest.php
- tests/Core/Ruleset/ProcessRulesetAutoloadTest.php
- tests/Core/Ruleset/ProcessRulesetBrokenRulesetTest.php
- tests/Core/Ruleset/SetSniffPropertyTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
As things are, the `Runner` class catches any exception thrown by the Ruleset, enhances the message with an `ERROR` prefix, adds new lines and short help usage info and then re-throws this as a `DeepExitException`.
In an upcoming PR, a new `MsgCollector` class will be introduced, which will allow for both errors, as well as warnings, notices and deprecations.
This means that the `ERROR` prefix won't always be appropriate anymore.
This commit moves the `ERROR` prefix addition from the `Runner` class to the individual messages for the Exceptions being thrown in the `Ruleset` class.
Additionally, it changes the "trailing new lines" handling as the `MsgCollector` may also add new lines at the end of a message, as messages will not necessarily always be displayed via an exception (think: …
> Runner: don't prefix Ruleset error notices

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapSwitchTokenScopeTest.inc
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapSwitchTokenScopeTest.php
This PR improves the switch keyword tokenizer tests by adding the tests suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887087504. It also adds another commit to improve the tests stability by ensuring that a marker is always used to get the scope opener and scope closer.
Part of the changes suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887087504
> Tests/Tokenizer: improve switch keyword tests

- .github/workflows/validate.yml
The intention is for there to be a dedicated action runner available at some point for XML code style checking, so let's move this to a separate job.
Also see: PHPCSStandards/PHPCSDevTools#145
Instead of doing all the installation steps for xmllint validation in the workflow, use the ✨ new dedicated `phpcsstandards/xmllint-validate` action runner instead.
Ref: https://github.com/marketplace/actions/xmllint-validate
* Check the docs against the schema from PHPCSDevTools.
* Check dev tool config files.
_N/A_
> GH Actions: use the xmllint-validate action runner and enhance checks

- tests/Core/Generators/GeneratorTest.php
The `testGeneratorWillShowEachStandardSeparately()` test uses a regex to verify the output, but that regex used the `s` modifier (`.` matches new lines), which made it less stable.
This commit makes some adjustments to the regex to get rid of the `s` modifier, which should make the test more stable.
_N/A_
Unblocks PR #842
> GeneratorTest: make a particular test more stable

- src/Standards/Squiz/Docs/Classes/ValidClassNameStandard.xml
This PR adds documentation for the `Squiz\Classes\ValidClassName` sniff.
Add documentation for the Squiz.Classes.ValidClassName sniff
Partial fix for #148
> [Docs] Add XML doc for Squiz.Classes.ValidClassName sniff

- src/Generators/HTML.php
- src/Generators/Markdown.php
- src/Generators/Text.php
These five commits basically apply the same changes to all three Generator classes (reduce code duplication), which is why I've combined them in one PR.
---
Move some duplicate code to dedicated `private` methods.
Move some duplicate code to dedicated `private` methods.
Move some duplicate code to dedicated `private` methods.
There's absolutely no need for custom word-wrapping logic when PHP contains a function which can do this perfectly well.
Move yet more duplicate code to a dedicated `private` method.
_N/A_
Also see: #671 and other PR with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) …
> Generators/[HTML|Markdown|Text]::getFormattedCodeComparisonBlock(): minor refactor 

- src/Generators/HTML.php
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonBlankLines.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonBlockLength.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonEncoding.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeComparisonLineLength.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleLineWrapping.html
- tests/Core/Generators/Expectations/ExpectedOutputCodeTitleWhitespace.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleCase.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitleLength.html
- tests/Core/Generators/Expectations/ExpectedOutputDocumentationTitlePCREFallback.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonMismatchedCodeElms.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonMissingCodeElm.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonNoCode.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonNoContent.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonOneEmptyCodeElm.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeComparisonTwoEmptyCodeElms.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeTitleEmpty.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidCodeTitleMissing.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleEmpty.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidDocumentationTitleMissing.html
- tests/Core/Generators/Expectations/ExpectedOutputInvalidStandardNoContent.html
- tests/Core/Generators/Expectations/ExpectedOutputOneDoc.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardBlankLines.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardEncoding.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardIndent.html
- tests/Core/Generators/Expectations/ExpectedOutputStandardLineWrapping.html
- tests/Core/Generators/Expectations/ExpectedOutputStructureDocs.html
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedOneElmAtWrongLevel.html
- tests/Core/Generators/Expectations/ExpectedOutputUnsupportedSuperfluousCodeElement.html
Mark the table headers as headers (and tweak the CSS a little for correct display).
Generators/HTML: improved display of code tables via semantic HTML
Also see: #671 and other PRs with the [Core Component: Generators](https://github.com/PHPCSStandards/PHP_CodeSniffer/labels/Core%20Component%3A%20Generators) label.
> Generators/HTML: improve code table semantics

- .github/workflows/test.yml
As @asispts hasn't been responding to the open feedback on PR #798 anymore **AND** the change proposed in #798 should go into the same release as PR #797 was merged in (to safeguard the changes from that PR) **AND** I haven't got permission to update the PR branch, I'm opening a new PR which supersedes PR #798.
I've cherrypicked and squashed the pertinent changes from #798. Props @asispts.
This commit updates the initial implementation for updating `libxml2` on the fly for select PHP versions.
Compared to the original implementation, the following changes were made:
* Use a `libxml_minor` flag in the matrix to indicate whether `libxml` should be updated for a particular job or not.
This `libxml_minor` flag also allows for specifying a specific minor to use for the update.
This flag is now …
> GH Actions/tests: run tests against multiple libxml versions

- .github/labeler.yml
I recently split the `Core Component: Config & Ruleset & CLI options` label into two, but this ruleset wasn't updated yet, so the label was being re-introduced by the workflow which auto-adds labels. Oops.
Fixed now.
_N/A_
> GH Action/Labeller: fix up outdated labels

- src/Standards/Squiz/Sniffs/Classes/ClassFileNameSniff.php
- src/Standards/Squiz/Tests/Classes/ClassFileName Spaces In FilenameUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileName-Dashes-In-FilenameUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameLiveCodingFailUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameLiveCodingPassUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameParseError1UnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameUnitTest.php
This commit adds some extra tests for the sniff.
* Document handling of unfinished OO declarations (which contain enough info to still action).
* Safeguard that comments in unexpected places doesn't cause problems.
As this sniff looks at the file name of the file containing the tests, we cannot use the _normal_ `SniffNameUnitTest.#.inc` naming conventions for extra tests files, so the `getTestFiles()` method from the `AbstractSniffUnitTest` class needs to be overloaded to retrieve the test case files in a slightly different way.
Use the predefined `Tokens::$ooScopeTokens` array to automatically benefit from new OO structures being added to that list.
As `STDIN` won't contain a usable file name, bow out and don't examine the input again.
_Note: the `process()` method should really end on a …
> Squiz/ClassFileName: various improvements

- .github/workflows/test.yml
* Fold two steps into one by using an inline condition.
* Show the inline annotations for PHP 8.4 (faster) instead of PHP 7.4.
* Improve step condition and reduce the need for bash scripting.
_N/A_
> GH Actions/test: minor simplifications

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
This PR fixes a bug in `RecurseScopeMapDefaultKeywordConditionsTest ::testSwitchDefault()`. Among other things, this method checks whether tokens within the scope of a `default` have `T_DEFAULT` set as the scope condition.
But the code would never check if the scope condition is set for the tokens within the scope of a `T_DEFAULT` token when `$conditionStop` is not `null`. `$conditionStop` is used when `T_DEFAULT` uses curlies to open and close the scope. In those cases, scope conditions are not set all the way until the scope closer. Instead, they are set only until just before a T_BREAK|T_RETURN|T_CONTINUE.
`simple_switch_default_with_curlies` test case is the only one that currently sets `$conditionStop` to something other than `null`. But it passes an offset value of the condition …
> Tests/Tokenizer: fix bug in the `default` keyword tests

- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
Add some extra tests to verify that extending a (new style) array property declaration works as expected.
While this is also tested via the `ProcessRuleShouldProcessElementTest`, some extra tests seemed warranted.
_N/A_
> Ruleset/PropertyTypeHandlingTest: add tests with extended arrays

- src/Standards/Squiz/Tests/WhiteSpace/FunctionClosingBraceSpaceUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionClosingBraceSpaceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionClosingBraceSpaceUnitTest.php
A significant part of this sniff (handling of nested functions) is only covered by JS tests, so let's make sure this functionality also has tests for PHP.
_N/A_
Loosely related to #146
> Squiz/FunctionClosingBraceSpace: add some more tests

- tests/Core/Standards/StandardRulesetsQATest.php
This adds a QA test to verify that the build-in rulesets do not throw any errors to prevent a change in the sniffs, which needs an update to a ruleset, from going unnoticed.
Ref:
* https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/58#issuecomment-2709028260
_N/A_
Fixes #58
> Add StandardRulesetsQATest

- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
While already handled correctly for inline properties set via `phpcs:set`, setting a property to an empty array from a ruleset file was not handled correctly until now.
As things were, when setting an array property from the ruleset to an empty array like so:
```xml
<rule ref="Standard.Category.SniffName">
<properties>
<property name="arrayProperty" type="array"/>
</properties>
</rule>
```
the property value would be set to:
```php
public $arrayProperty = [
0 => '',
];
```
... while the expected behaviour would be:
```php
public $arrayProperty = [];
```
While it is not expected that this type of property setting is encountered a lot in the wild, it should still work correctly.
Fixed now.
Includes test safeguarding the fix.
Setting an array property to an empty array from an XML ruleset …
> Ruleset: bug fix - correctly handle empty array property setting

- src/Ruleset.php
- src/Util/MessageCollector.php
- tests/Core/Ruleset/ConstructorTest.php
- tests/Core/Ruleset/DisplayCachedMessagesTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceHomePathTest.php
- tests/Core/Ruleset/ExpandRulesetReferenceTest.php
- tests/Core/Ruleset/PopulateTokenListenersRegisterNoArrayTest.xml
- tests/Core/Ruleset/PopulateTokenListenersTest.php
- tests/Core/Ruleset/ProcessRuleInvalidTypeTest.php
- tests/Core/Ruleset/SetSniffPropertyTest.php
- tests/Core/Util/MessageCollector/MessageCollectorTest.php
👉🏻  _This PR has been a while in the making. While I'm confident about the principle of it, I've been struggling to write up the implementation choices made, which normally means there is still something not completely "right".
So under the guise of "Perfect is the enemy of good", here goes anyway (as this PR is blocking everything else I'm working on, as well as blocking the 3.12.0 release)._
_So please consider this a first iteration. The actual implementation details can be iterated on both in this PR, as well as via future PRs._
---
This PR is intended to solve two problems for the `Ruleset` class and to allow for implementing the same kind of solution in other parts of the codebase at a later point in time.
Up to now, the `Ruleset` class only allowed for hard errors which would exit …
> Ruleset: improve error handling

- tests/Core/Tokenizers/PHP/AnonClassParenthesisOwnerTest.php
- tests/Core/Tokenizers/PHP/BackfillFnTokenTest.php
The `assertArrayHasKey()` and `assertArrayNotHasKey()` method can be used instead of "manually" doing an `array_key_exists()` with `assert[True|False]()`.
These methods were already available in PHPUnit 4.x and are already in use in other places in the test suite, so there is no reason not to use them in these tests too.
_N/A_
> Tests: use more specific assertions

- tests/Core/Autoloader/DetermineLoadedClassTest.php
- tests/Core/Filters/Filter/AcceptTest.php
- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
- tests/Core/Ruleset/RegisterSniffsTest.php
- tests/Core/Tokenizers/PHP/NamedFunctionCallArgumentsTest.php
> Tests: always use type strict assertions

- src/Config.php
- tests/Core/Config/ExtensionsArgTest.php
Includes minor bug fix to treat an empty value correctly.
Previously, passing `--extensions=` (without value) would result in the `Config::$extensions` property being set to:
```php
public $extensions = [
'' => 'PHP'
];
```
Now, an empty value will set the extensions array to an empty array.
```php
public $extensions = [];
```
Note: in practice, the above change will not make a difference in how files are filtered/scanned.
:point_right: The change to the `Config` class will be most straight-forward to review while ignoring whitespace changes.
_N/A_
> Config: add tests for setting `--extensions`

- .github/workflows/test.yml
The "coverage" job basically runs the tests in three different ways:
1. Normal test run on Linux.
2. CBF specific tests in CBF mode on Linux.
3. Windows specific tests on Windows.
For these three test runs, the script contained 6 steps as whether or not the coverage cache should be used depends on the PHPUnit version.
This commit condenses the 6 steps to 3 steps by using a command inline expression instead of step conditions.
_N/A_
> GH Actions/coverage: join some steps

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
This PR addresses an issue that I missed when working on #850. Among other things, the `RecurseScopeMapDefaultKeywordConditionsTest ::testSwitchDefault()` method checks if tokens within the scope of a `T_DEFAULT` token have `T_DEFAULT` set as one of its `conditions` array.
The test incorrectly checked token `conditions` due to an off-by-one error in the loop range when the `T_DEFAULT` uses curly braces.
For a `T_DEFAULT` with curly braces, the tokenizer adds `T_DEFAULT` to the `conditions` array of all the tokens within its scope up to the `T_BREAK|T_RETURN|T_CONTINUE`, but the test was checking only until the token before the `T_BREAK|T_RETURN|T_CONTINUE`. While for a `T_DEFAULT` without curly braces, it adds to all the tokens within the scope until the token before the scope closer. …
> Tests/Tokenizer: fix `conditions` checking range in `T_DEFAULT` test

- src/Standards/Squiz/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/Squiz/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/ClassDeclarationUnitTest.php
The `Squiz.Classes.ClassDeclaration` sniff checks the number of blank lines _after_ a class closing brace to be exactly one blank line.
To prevent conflicts with other sniffs checking blank lines before function declarations, it bows out when the next thing after the class declaration is a function declaration and defers to the function declaration sniff to handle the "blank lines before function" check. See squizlabs/PHP_CodeSniffer#2033 for historic context.
However, the above "bowing out" breaks when a function after a class has PHP 8.0+ attributes attached to it and the sniff would still throw the `NewlinesAfterCloseBrace` error.
Fixed now.
Note: the new "errors" caused by the new tests are for the `MultipleClasses` code, which is unrelated to this fix and valid. …
> Squiz/ClassDeclaration: allow for function attributes

- tests/Core/Util/Common/EscapeshellcmdTest.php
The array keys should match the names of the expected parameters of the test function.
_N/A_
> EscapeshellcmdTest: fix up data provider

- tests/Core/Generators/GeneratorTest.php
- tests/Core/Ruleset/ExplainTest.php
- tests/Core/Runner/AbstractRunnerTestCase.php
- tests/Core/Runner/RunPHPCSExplainTest.php
- tests/Core/Runner/RunPHPCSGeneratorTest.php
... for tests which directly invoke the `Runner` class.
... to their own test classes using the new `AbstractRunnerTestCase` base class.
_N/A_
> Tests: introduce AbstractRunnerTestCase base class and start using it

- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
Document that both the property names as well as the value get trimmed off surrounding whitespace before being passed to the sniff object.
Includes fixing two incorrect property docs in the test sniff.
_N/A_
> Ruleset: add tests to document trimming behaviour

- src/Files/File.php
- src/Standards/Generic/Tests/PHP/BacktickOperatorUnitTest.inc
- src/Standards/Generic/Tests/PHP/BacktickOperatorUnitTest.php
With the `MessageCollector` being used in the `Ruleset` class since PR #857, some guard code as introduced in #99 is no longer needed.
The guard code was in place to prevent the following situation:
* File under test contained an invalid `// phpcs:set` annotation which tried to set a non-existent property on a sniff.
* The  `File::process()` method would see this annotation and call the `Ruleset::setSniffProperty()` method to set the property.
* The `Ruleset::setSniffProperty()` method would throw an exception for the non-existent property.
* The exception would cause the `File` class to stop scanning the file, potentially leading to missing errors/warnings.
As the error for setting a non-existent property now no longer leads to an exception on a direct call to the …
> Remove some redundant code

- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/InvalidSniffError/NoImplementsNoProcessSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/InvalidSniffError/NoImplementsNoRegisterOrProcessSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/InvalidSniffError/NoImplementsNoRegisterSniff.php
- tests/Core/Ruleset/ProcessRulesetAutoExpandSniffsDirectoryTest.xml
- tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoProcessTest.xml
- tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoRegisterOrProcessTest.xml
- tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoRegisterTest.xml
- tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.xml
As things were, a ruleset loading an invalid sniff - a sniff which doesn't implement the `Sniff` interface and is missing either the `register()` or `process()` method, or both -, would result in fatal errors which are unfriendly to the end-user.
Now, while this will hopefully be a very rare occurrence and should no longer be possible as of PHPCS 4.0, which intends to remove support for sniffs not implementing the `Sniff` interface, I still believe it prudent to show more user-friendly and more informative error messages to the end-user until that time.
This commit implements this and executes step 2 to address issue #694.
Output of commands involving various invalid sniffs **before** this PR:
```
$ phpcs -ps . --standard=./tests/Core/Ruleset/RegisterSniffsRejectsInvalidSni …
```
> Ruleset: handle invalid sniffs more graciously

- src/Config.php
- src/Util/MessageCollector.php
- tests/Core/Standards/StandardRulesetsQATest.php
- tests/Core/Tokenizers/Tokenizer/CreateParenthesisNestingMapDNFTypesTest.php
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapCaseKeywordConditionsTest.php
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
- tests/Core/Util/MessageCollector/MessageCollectorTest.php
- tests/Core/Util/Tokens/GetHighestWeightedTokenTest.php
Various minor tweaks collected along the way.
_N/A_
> Docs: various minor tweaks

- CHANGELOG.md
> Changelog for the 3.12.0 release

- .remarkrc
... and retry other failing links to prevent having to rerun GHA jobs.
I suspect the PEAR website might see these checks as DDOS as when the GHA workflow runs, it will hit a few hundred URLs in quick succession, so let's not do this every time.
_N/A_
> Remark/dead URL check: skip flaky PEAR links

- src/Standards/Generic/Tests/PHP/DeprecatedFunctionsUnitTest.inc
- src/Standards/Generic/Tests/PHP/DeprecatedFunctionsUnitTest.php
Both functions used in the tests were removed in PHP 8.0, so when running the tests on PHP 8.0, nothing would be tested anymore.
_N/A_
> Generic/DeprecatedFunctions: add test which will work for PHP 8.0+

- .github/workflows/label-remove-outdated.yml
Hoping this works as it is difficult to test it, but the intention is to get the workflow to automatically remove the "Status: awaiting feedback" label when a (new) review is requested on a PR.
_N/A_
> GH Actions: auto-remove label on review request

- .github/workflows/label-remove-outdated.yml
PR #897 made a change to the "auto remove labels" workflow, but that change couldn't be tested until merged as it used the `pull_request_target` event, which always reads the workflows from the `master` branch and not from a PR branch.
I've now tested the change and while the _new_ addition looks to be correct, one of the pre-existing jobs _also_ ran, while it shouldn't have run.
This new commit attempts to fix that.
Again, we can't test this until merged, but will test once it has been merged.
_N/A_
> GH Actions: auto-remove label tweaks

- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
The `PropertyTypeHandlingTest` class tests the setting of property values from the ruleset as well as via inline `// phpcs:set ...`  annotations.
As both ways of setting the property value should be supported in the same manner, the tests used one data provider for both tests and the fixtures (`PropertyTypeHandlingTest.xml` ruleset and the `Fixtures/PropertyTypeHandlingInline.inc` file containing the inline annotations) mirrored the exact same test cases.
There is one feature, however, which is only supported when setting properties via the ruleset, not when setting them via inline annotations: array property extending.
Until now, the tests for that were also mirrored in the inline annotation tests, even though the feature isn't supported for inline annotations.
This commit now splits the …
> PropertyTypeHandlingTest: split data provider

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.inc
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
This PR adds two new tests to the tokenizer tests for the `default` keyword:
- Ensure that the `default` scope is set correctly when the scope closer is shared with a `switch`.
- Ensure that the `default` scope is set correctly when there is an inner if condition with and without braces.
Both tests were copied from similar tests for the `case` keyword that were added to protect against regressions (see b9809c7 and 61b9e9b). They were suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887061197 and https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887142654.
Tests suggested in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887061197 and https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/595#discussion_r1887 …
> Tests/Tokenizer: expand `default` keyword tests

- src/Ruleset.php
- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceBsdAllmanSniff.php
- src/Standards/PSR12/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR12/Sniffs/Files/DeclareStatementSniff.php
- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Util/Standards.php
- tests/Core/File/GetConditionTest.php
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapWithNamespaceOperatorTest.php
* Use the correct case for functions.
* Don't return result of a `void` function.
* A few type consistency fixes.
_N/A_
> CS/QA: various minor fixes

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
As discussed in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/813#pullrequestreview-2698949270, this PR appends the test marker's name to the end of each assertion's `$message`. This should make it easier to identify which test case caused a given test to fail.
_N/A_
Follow up to #813
> Tests/Tokenizer: make it easier to debug recurseScopeMap() `default` keyword tests

- tests/Core/Config/AbstractRealConfigTestCase.php
- tests/Core/Config/ReportWidthTest.php
- tests/Core/Runner/AbstractRunnerTestCase.php
As the `Config` class contains a number of `static` properties, it is important to avoid tests influencing each other if the tests would cause changes to the value of the static properties.
This was already handled correctly in the two places were the _real_ `Config` class is being used in the tests, but that meant those test classes now contain duplicate code.
This new `AbstractRealConfigTestCase` class removes that code duplication.
This test case should be used in the rare circumstances that the _real_ `Config` class needs to be used in the tests.
In most cases, using the `ConfigDouble` class is much preferred, but for select tests for the `Config` class itself + for tests involving the `Runner` class, using the real `Config` class cannot be avoided.
_N/A_
> Tests: introduce new `AbstractRealConfigTestCase`

- src/Standards/PSR12/Tests/Files/FileHeaderUnitTest.19.inc
Just safeguarding that the sniff doesn't trigger on closure `use`.
_N/A_
> PSR12/FileHeader: add extra test

- src/Standards/Generic/Tests/WhiteSpace/LanguageConstructSpacingUnitTest.1.inc
- src/Standards/Generic/Tests/WhiteSpace/LanguageConstructSpacingUnitTest.1.inc.fixed
Just safeguarding that the sniff doesn't trigger on closure `use`.
_N/A_
> Generic/LanguageConstructSpacing: add extra test

- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
Just safeguarding handling of closure use with parameters imported by reference.
_N/A_
> File::getMethodParameters(): add extra test

- src/Fixer.php
If an error/fixer conflict occurs while running the PHPCBF, additional information about the issue will be displayed in verbose mode, however, the code creating the debug info did not take into account that part of the fixer code may be in helper classes, instead of directly in the sniff class.
This should fix that and make the debug information more, well... informational ;-)
Fixed potential `InvalidArgumentException` when displaying verbose information about issues encountered while running the fixer.
Related to slevomat/coding-standard#1739
> Fixer: improve debug information

- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/PHP/NullableVsInlineThenTest.inc
- tests/Core/Tokenizers/PHP/NullableVsInlineThenTest.php
_Discovered while investigating something else._
The `?` in a type for a `readonly` property declared without visibility, would be tokenized as `T_INLINE_THEN`, not `T_NULLABLE`.
Fixed now.
Includes perfunctory test.
Realistically, a lot more tests are needed for the `T_NULLABLE` vs `T_INLINE_THEN` tokenization, but at least, this is a start and covers the current change.
Fixed tokenization of `?` in nullable types for readonly properties.
> PHP 8.1 | Tokenizer/PHP: fix nullable type tokenization for readonly properties

- src/Standards/Generic/Docs/CodeAnalysis/UselessOverridingMethodStandard.xml
This commit fixes two syntax errors in the PHP code examples in the sniff documentation.
Previously, the provided code would cause the following PHP error:
```
PHP Fatal error: Cannot use "parent" when current class scope has no parent
```
- `<documentation>` title now matches the sniff title.
- `<standard>` description uses 'discouraged' instead of 'should not' as this sniff raises a warning, not an error.
- Minor grammar fixes and small changes to hopefully improve the readability of the `<standard>` description and `<code>` titles.
Generic.CodeAnalysis.UselessOverridingMethod: minor fixes and improvements to the XML documentation
> Generic/UselessOverridingMethod: improve XML documentation

- src/Standards/Generic/Sniffs/WhiteSpace/HereNowdocIdentifierSpacingSniff.php
The sniff was set up to display the identifier including the incorrect spacing, but wasn't doing so.
Fixed now.
Generic.WhiteSpace.HereNowdocIdentifierSpacing: improved error message text
Related to #586
> Generic/HereNowdocIdentifierSpacing: minor tweak

- src/Standards/Generic/Docs/Functions/FunctionCallArgumentSpacingStandard.xml
The FunctionCallArgumentSpacing sniff used to check for spacing around the equal sign in the arguments of a function declaration. But this was removed in https://github.com/squizlabs/PHP_CodeSniffer/pull/2399
(commit https://github.com/PHPCSStandards/PHP_CodeSniffer/commit/feeda473f045825c1caa213c3b7ab6dc6a99b746).
This commit updates the sniff XML doc to reflect this change.
The code examples in the XML documentation of this sniff were incorrect, as the sniff does not check spacing in function argument definitions. It only checks spacing in function and method calls.
As far as I could check, this has always been the case, or at least it has been the case for a long time. Since tests were added for this sniff when it was part of the PEAR standard and called MethodCallArgumentSpacing, it …
> Generic/FunctionCallArgumentSpacing: improve XML documentation

- src/Standards/PSR12/Tests/Files/ImportStatementUnitTest.inc
- src/Standards/PSR12/Tests/Files/ImportStatementUnitTest.php
Looking at the tests, each type of import `use` should have at least one test with a leading namespace separator and one without to properly cover what the sniff is looking for.
Looks like adding the leading `\` was missed for the `use const` tests.
_N/A
> PSR12/ImportStatement: test tweak

- src/Standards/PSR12/Tests/Namespaces/CompoundNamespaceDepthUnitTest.inc
Properties overruled in tests should always be reset as `// phpcs:set` is not limited to the current file.
_N/A_
> PSR12/CompoundNamespaceDepth: test tweak

- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc.fixed
> Generic/[Lower|Upper]CaseConstant: minor test clean up

- tests/Core/Tokenizers/PHP/AttributesTest.php
* Replace hard-coded "length" values provided via data providers with a simple `count()` calculation to prevent having to manually keep the `length` in sync with the contents of the `tokenCodes` arrays.
* Replace magic numbers in the `testNestedAttributes()` test with the same calculations assigned to variables to make the test more descriptive.
_N/A_
> AttributesTest: simplify test code

- tests/Core/Ruleset/ProcessRulesetBrokenRulesetTest.php
Looks like there are some more libxml quirks to take into account with different message content on different OSes.
This updates the tests to allow for them to pass on PHP < 8.0 with libxml 2.9.x on Windows.
Also adds the `@group Windows` annotation to ensure these tests are also run on Windows in CI.
_N/A_
> ProcessRulesetBrokenRulesetTest: more tweaks for different libxml output

- tests/Core/Tokenizers/PHP/BackfillFnTokenTest.inc
Variable names were meant to be descriptive, but with copy/paste, they weren't. Fixed now.
_N/A_
> Tests/BackfillFnTokenTest: minor tweaks

- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
The `%` modulus token is included in the `Tokens::$operators` array. No need to add it separately.
The `$allowed` tokens array is joined after declaration with the `Tokens::$operators` array. This is only reliable if the keys in both arrays are unique (or intended to be overwritten).
However, with the `$allowed` array being numerically indexed and PHP native tokens also being integers, this was not the case and could lead to one of the tokens in the original array (unintentionally) being disregarded/overwritten by one of the tokens in the `Tokens::$operators` array.
Fixed now, by making setting the tokens constants both as the key as well as the value, making the entries in the array suitable for an array join operation.
_N/A_
> Squiz/OperatorBracket: stability tweak 

- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.inc
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
This PR improves the `RecurseScopeMapDefaultKeywordConditionsTest::testSwitchDefault()` test method by replacing offsets with markers. This helps stabilize the tests.
This PR is the last one in a series of PRs to improve the `RecurseScopeMapDefaultKeywordConditionsTest` tests. The other PRs in this series are #813, #850, #870, and #902.
> Tests/Tokenizer: use markers for the `testSwitchDefault()` test

- src/Standards/Generic/Docs/Functions/OpeningFunctionBraceKernighanRitchieStandard.xml
- `<documentation>` title matches the sniff name.
- Don't mention the Kernighan/Ritchie style in the `<standard>` description as, according to Wikipedia, this style uses the opening brace for functions on a separate line and not on the same line (https://en.wikipedia.org/wiki/Indentation_style#K&R).
- I believe it is more precise to say that the sniff checks if the opening brace is on the same line as the closing parenthesis and not the function declaration, as the function declaration can be multi-line.
- Mention in the `<standard>` description that there must be no content on the line after the opening brace.
- Improve the title of the `<code>` blocks.
Generic.Functions.OpeningFunctionBraceKernighanRitchie: minor fixes and improvements to the XML documentation
> Generic/OpeningFunctionBraceKernighanRitchie: improve XML documentation

- src/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
- src/Standards/Generic/Tests/PHP/ForbiddenFunctionsUnitTest.inc
- src/Standards/Generic/Tests/PHP/ForbiddenFunctionsUnitTest.php
Includes some updated tests to cover this change.
Generic.PHP.ForbiddenFunctions: prevent false positives/negatives for code interlaced with comments
> Generic/ForbiddenFunctions: improve comment tolerance

- src/Standards/Generic/Sniffs/PHP/LowerCaseConstantSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc.fixed
The `Generic.PHP.LowerCaseConstant` sniff is supposed to flag uppercase use of the `true`/`false`/`null` constants and its sister-sniff `UpperCaseConstant` flags the lowercase variants. Both sniffs, however, are supposed to **_ignore_** the use of these keywords in type declarations - which may have their own rules.
Some previous PRs already fixed most of the issues with that (#119, #330), but it looks like DNF-types in property declarations were not yet handled correctly.
Fixed now.
Generic.PHP.LowerCaseConstant and Generic.PHP.UpperCaseConstant will now correctly ignore DNF types for properties.
> PHP 8.2 | Generic/[Lower|Upper]CaseConstant: bug fix - ignore DNF property types

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.php
Turns out this sniff was never updated to deal with attributes potentially being between a function declaration and the docblock preceding it, which could lead to false negatives.
Fixed now.
Includes test.
Squiz.Commenting.FunctionCommentThrowTag : sniff would bow out when function has attributes attached leading to false negatives
> Squiz/FunctionCommentThrowTag: bug fix - jump over attributes

- .github/workflows/test.yml
- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF1Test.inc
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF1Test.php
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF2Test.inc
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF2Test.php
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF3Test.inc
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF3Test.php
Prior to PHP 7.4, a PHP open tag at the end of a file was not tokenized correctly in PHP itself.
From the PHP 7.4 changelog:
> `<?php` at the end of the file (without trailing newline) will now be
> interpreted as an opening PHP tag. Previously it was interpreted either as
> `<? php` and resulted in a syntax error (with short_open_tag=1) or was
> interpreted as a literal `<?php` string (with short_open_tag=0).
This commit makes the tokenization of PHP open tags at the end of a file consistent in all PHP versions.
Includes adding a few extra test builds which test with `short_open_tag=On` for various PHP versions.
Refs:
* https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.php-tag
* …
> PHP 7.4 | Tokenizer/PHP: handle PHP tag at end of file consistently

- .github/ISSUE_TEMPLATE/bug_report.md
Change square brackets to parentheses to avoid "undefined reference" markdown error.
Includes re-aligning the table.
_N/A_
Related to: https://github.com/remarkjs/remark-lint/releases/tag/remark-lint-no-undefined-references%405.0.2
> Issue template: minor tweak

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
If a doc comment contained an intersection type, `Squiz.Commenting.FunctionComment` would report `Doc comment for parameter "<param>" missing`. This PR fixes that. The updated regex was taken from a similar fix to `PEAR.Commenting.FunctionComment` in f797a35dafabd9dddab3029e47f550ba7c615280.
Squiz/FunctionComment: support intersection types
N/A
> Squiz/FunctionComment: support DNF types

- src/Standards/Generic/Docs/WhiteSpace/LanguageConstructSpacingStandard.xml
This PR fixes syntax errors in the XML doc code examples.
One of the invalid examples was removed because, besides containing a syntax error, it doesn't trigger the sniff (`yieldfrom` is tokenized as `T_STRING`, and this token is not watched by the sniff). The `<code>` title was updated to reflect the remaining examples.
Generic.WhiteSpace.LanguageConstructSpacing: minor fixes and improvements to the XML documentation
> Generic/LanguageConstructSpacing: fix syntax errors in the XML doc code examples

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.php
To determine whether there are the correct number of lines before the function declaration, the sniff skips over attributes and docblocks to find the first bit of code which doesn't belong with the function declaration.
While the change in PR #826 improved this for attributes _before_ the docblock, it didn't take multiple docblocks into account and would skip over more than just the first docblock.
Fixed now.
Fixed: Squiz.WhiteSpace.FunctionSpacing would get confused when there are two docblocks above a function declaration.
Fixes #826
Fixes #945
Closes #938
> Squiz/FunctionSpacing: fix regression - only look at first docblock

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.php
Includes test.
Squiz.Commenting.FunctionCommentThrowTag: prevent false positives/negatives for code interlaced with comments.
> Squiz/FunctionCommentThrowTag: improve comment tolerance

- src/Standards/Generic/Sniffs/PHP/LowerCaseConstantSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc
- src/Standards/Generic/Tests/PHP/LowerCaseConstantUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc
- src/Standards/Generic/Tests/PHP/UpperCaseConstantUnitTest.inc.fixed
The `Generic.PHP.LowerCaseConstant` sniff is supposed to flag uppercase use of the `true`/`false`/null` constants and its sister-sniff `UpperCaseConstant` flags the lowercase variants. Both sniffs, however, are supposed to **_ignore_** the use of these keywords in type declarations - which may have their own rules.
This commit adds support for skipping over the types in PHP 8.4 `final` property declarations.
Added support for PHP 8.4 final properties to the following sniffs:
- Generic.PHP.LowerCaseConstant
- Generic.PHP.UpperCaseConstant
> PHP 8.4 | Generic/[Lower|Upper]CaseConstant: add support for final properties

- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
If a property uses the `final` modifier keyword, the property docblock (providing there is one) would never be found, leading to false positives.
Fixed now.
Added support for PHP 8.4 final properties to the following sniffs:
- Squiz.Commenting.VariableComment
> PHP 8.4 | Squiz/VariableComment: add support for final properties

- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
If a class or property used the `final` keyword, the docblock would not be recognized as one which needed examining.
Fixed now.
* Added support for PHP 8.4 final properties to the following sniffs:
- Squiz.Commenting.DocCommentAlignment
* Squiz.Commenting.DocCommentAlignment will now examine docblocks for `final` classes.
> Squiz/DocCommentAlignment: add support for final classes and final properties

- src/Standards/Generic/Tests/CodeAnalysis/UnnecessaryFinalModifierUnitTest.1.inc
- src/Standards/Generic/Tests/CodeAnalysis/UnnecessaryFinalModifierUnitTest.php
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
> PHP 8.4 | Various sniffs: add tests with final properties

- src/Reports/Code.php
Okay, so this is an awkward one.
If both the `Code` + the `Diff` report were requested + caching was turned on + the _order_ of the requested reports was `Code,Diff` (i.e. first the code report), the following fatal error would occur:
```
Fatal error: Uncaught Error: Call to a member function getFixableCount() on null in path/to/PHP_CodeSniffer/src/Fixer.php:144
Stack trace:
#0 path/to/PHP_CodeSniffer/src/Reports/Diff.php(73): PHP_CodeSniffer\Fixer->fixFile()
#1 path/to/PHP_CodeSniffer/src/Reporter.php(285): PHP_CodeSniffer\Reports\Diff->generateFileReport(Array, Object(PHP_CodeSniffer\Files\LocalFile), true, 150)
#2 path/to/PHP_CodeSniffer/src/Runner.php(659): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile))
#3 …
```
> Report/Code: fix fatal potential fatal error when combined with Diff report

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
Prevent an "Undefined array index" PHP notice when running in debug mode when there are no scopes left.
Issue can be reproduced by running:
```bash
phpcs ./src/Runner.php --runtime-set scope_indent_debug 1
```
Fixed: Generic.WhiteSpace.ScopeIndent: undefined array index notice when running in debug mode
> Generic/ScopeIndent: bug fix for debug mode

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
Depending on whether verbose output is requested or not, the debug output from the `ScopeIndent` sniff _may_ or _may not_ start on a new line. When it doesn't, it makes the output harder to read.
Fixed now.
_N/A_
> Generic/ScopeIndent: start debug info on new line

- .github/CONTRIBUTING.md
Follow up on #881 and #909
_N/A_
> CONTRIBUTING: add some more info about writing tests

- src/Runner.php
- tests/Core/Runner/PrintProgressDotsTest.php
- tests/Core/Runner/PrintProgressTest.php
Reduce the complexity of the method somewhat and improve the readability.
_N/A_
Alongside of this PR, I've also added a section to the wiki about progress reporting with a legend of the status indicators used: https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Reporting#progress-reporting
> Runner::printProgress(): minor refactor 

- src/Standards/Generic/Docs/Functions/OpeningFunctionBraceBsdAllmanStandard.xml
- `<documentation>` title matches the sniff name.
- Mention in the `<standard>` description that there must be no content on the line after the opening brace and make some other minor adjustments to the description text.
- Improve the title of the `<code>` blocks.
Generic.Functions.OpeningFunctionBraceBsdAllman: minor fixes and improvements to the XML documentation
> Generic/OpeningFunctionBraceBsdAllman: improve XML documentation

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.php
The `PEAR.Commenting.FunctionComment` sniff intends to flag blank lines between a function docblock and the function declaration.
However, as things are, there are - IMO - two bugs in the logic for this:
Given a code block which looks like this:
```php
class HandleBlankLinesBetweenDocblockAndDeclarationWithAttributes
{
/**
* Blank line between docblock and attribute.
*
* @return mixed
*/
#[ReturnTypeWillChange]
#[
AnotherAttribute
]#[AndAThirdAsWell]
public function blankLineDetectionA()
{
}//end blankLineDetectionA()
}
```
There will be only one error and it will read:
```
[x] There must be no blank lines after the function comment (PEAR.Commenting.FunctionComment.SpacingAfter)
```
This is confusing as the blank line may not be after the function comment, but after an attribute instead. …
> PEAR/FunctionComment: bug fix - handling of blank lines in pre-amble

- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Add some extra tests to safeguard the current handling of some code variation not previously covered by tests.
_N/A_
> Squiz/MemberVarSpacing: add extra tests

- CHANGELOG.md
> Changelog for the 3.12.2 release

- tests/Core/Runner/PrintProgressDotsTest.php
> PrintProgressDotsTest: fix up param names in data sets

- src/Generators/HTML.php
- src/Generators/Markdown.php
- src/Generators/Text.php
- tests/Core/Generators/Fixtures/HTMLDouble.php
- tests/Core/Generators/Fixtures/MarkdownDouble.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
These methods were _soft_ deprecated in PHPCS 3.12.0 via PR #755 and will be removed in PHPCS 4.0.0.
This commit hard deprecates these in case extenders missed the changelog entry.
Includes perfunctory tests for the principle of the deprecation notices.
Added deprecation notices (hard deprecation) for:
- Deprecated Generator method which will be removed in PHPCS 4.0.
> Generators: show deprecation notice for deprecated methods

- src/Ruleset.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
This format was (soft) deprecated in PHPCS 3.3.0 (June 2018) and it is expected that most rulesets will have been updated.
With the new "error handling" functionality in the Ruleset class in place (PR #857), the old format can now be hard deprecated to make users who haven't updated their rulesets yet, aware of the upcoming removal of support for the old array format.
Refs:
* https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0
* squizlabs/PHP_CodeSniffer#1665
Added deprecation notices (hard deprecation) for:
- The old array property setting format (via comma separated strings),  which will be removed in PHPCS 4.0.
Closes #693
> Ruleset: hard deprecate use of the old property array format

- src/Ruleset.php
- tests/Core/Ruleset/ExpandRulesetReferenceInternalTest.php
Support for standards called `Internal` was soft deprecated in PHPCS 3.12.0
This PR adds a new Ruleset deprecation notice for when such a standard would be requested from a ruleset.
Support for sniffs not following the naming conventions will be removed in PHPCS 4.0.
Includes test.
Added deprecation notices (hard deprecation) for:
- Standards called `Internal`, which will no longer be supported in PHPCS 4.0.
Related to #799
> Ruleset: hard deprecate support for standards called "Internal"

- src/Ruleset.php
- tests/Core/Filters/Filter/AcceptTest.xml
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ImplementsDeprecatedInterfaceSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForCSSAndJSSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForCSSAndUnrecognizedSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForCSSSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForEmptySniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForJSSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForPHPAndCSSAndJSSniff.php
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SupportedTokenizers/ListensForUnrecognizedTokenizersSniff.php
- tests/Core/Ruleset/PopulateTokenListenersSupportedTokenizersTest.php
- tests/Core/Ruleset/PopulateTokenListenersSupportedTokenizersTest.xml
- tests/Core/Ruleset/PopulateTokenListenersTest.php
- tests/Core/Ruleset/PopulateTokenListenersTest.xml
- tests/Core/Ruleset/ProcessRulesetAutoExpandSniffsDirectoryTest.xml
- tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForStandardTest.xml
- tests/Core/Ruleset/ShowSniffDeprecationsTest.xml
⚠️ **_This PR needs for PR #888 to be merged first._** ⚠️ 
---
Support for the JS and CSS Tokenizers will be removed in PHPCS 4.0.
This was announced in squizlabs/PHP_CodeSniffer#2448 and has been formalized via a soft deprecation (documentation and changelog only) in the PHPCS 3.9.0 release (see #276).
This commit implements a deprecation notice to alert sniff maintainers and ruleset maintainers to sniffs which are exclusively aimed at CSS and/or JS files.
This deprecation notice will not be shown if the sniff is formally deprecated via an implementation of the `DeprecatedSniff` interface (to prevent duplicate notifications).
Refs:
* https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0
Includes an update to two tests in the `PopulateTokenListenersTest` to make these use …
> Ruleset: hard deprecate $supportedTokenizers set to CSS/JS only

- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
Includes handling the modifier order when `final` is used. This introduces a new `FinalAfterVisibility` error code.
Note: the modifier keyword order checks could probably do with some optimization, but that can be handled later.
* Added support for PHP 8.4 final properties to the following sniffs:
- PSR2.Classes.PropertyDeclaration
* The PSR2.Classes.PropertyDeclaration will now check that the `final` modifier keyword is placed before a visibility keyword. Errors will be reported via a new `FinalAfterVisibility` error code.
> PHP 8.4 | PSR2/PropertyDeclaration: add support for final properties

- .github/workflows/build-phar.yml
- .github/workflows/label-merge-conflicts.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
> GH Actions: run on new 4.x branch

- .github/workflows/test-requirements-check.yml
- bin/phpcbf
- bin/phpcs
- phpcs.xml.dist
- phpstan.neon.dist
- requirements.php
- scripts/BuildRequirementsCheckMatrix.php
- scripts/build-phar.php
- scripts/get-requirements-check-matrix.php
- src/Runner.php
The requirements check (minimum PHP version + extensions) needs to stay PHP cross-version compatible to allow it to work properly.
As things were, what with the autoloader being loaded before the requirements check was run and the requirements check being part of the `Runner` class, this would block any PHP modernizations from being made to these files.
It is my opinion that the requirements check:
1. Should be run before anything else.
2. Should involve as few files as possible to prevent the check blocking code modernizations and raising the cognitive load for contributors.
To this end, I'm introducing a new `requirements.php` file in the project root. This file will be loaded in the bootstrapping of PHPCS/PHPCBF, both when running via the plain files (Composer, git clone), as well as …
> Refactor the requirements check

- src/Sniffs/AbstractPatternSniff.php
PHPCS deprecated the `$ignoreComments` parameter of the `AbstractPatternSniff::__construct()` sniff in version 1.4.0.
> - AbstractPatternSniff now sets the ignoreComments option using a public var rather than through the constructor
>     - This allows the setting to be overwritten in ruleset.xml files
>     - Old method remains for backwards compatibility
Time to remove this dead code.
Related to #6
Removed: The `$ignoreComments` parameter for the `AbstractPatternSniff::__construct()` method.
> AbstractPatternSniff::__construct(): remove the $ignoreComments property

- src/Files/File.php
- src/Files/LocalFile.php
- src/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.1.inc
- src/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
- src/Standards/Squiz/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
- src/Tokenizers/Tokenizer.php
- tests/Core/ErrorSuppressionTest.php
This annotation syntax was deprecated in PHPCS 3.2.0, which also introduced the new `// phpcs:...` syntax as a replacement.
Removed:
- Support for the deprecated `@codingStandard` annotation syntax has been removed. 
- Use the `phpcs:` or `@phpcs:` syntax instead
- Replace `@codingStandardsIgnoreFile` with `phpcs:ignoreFile`
- Replace `@codingStandardsIgnoreStart` with `phpcs:disable`
- Replace `@codingStandardsIgnoreEnd` with `phpcs:enable`
- Replace `@codingStandardsIgnoreLine` with `phpcs:ignore`
- Replace `@codingStandardsChangeSetting` with `phpcs:set`
Fixes squizlabs/PHP_CodeSniffer#1954
Related to #6
> Tokenizer: remove support for the deprecated @codingStandard annotation syntax

- src/Ruleset.php
- src/Runner.php
- src/Util/Common.php
- tests/Core/Ruleset/PopulateTokenListenersNamingConventionsTest.php
- tests/Core/Util/Common/GetSniffCodeTest.php
This reverts commit 71b4524.
Includes further enhancements to strictly apply the naming conventions by:
1. Making sure that the FQN contains a `Sniffs` or `Tests` sub-namespace in the correct position.
2. Making sure that the category is not called `Sniffs`.
3. Making sure that a class ends on `Sniff` or `UnitTest`, and that that is a suffix, not the sole name of the class.
Includes updating the tests.
Related to #689
Related to #6
The [About Standards for PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/About-Standards-for-PHP_CodeSniffer) wiki page outlines exactly what the naming conventions are.
This PR changes the previously added Ruleset deprecation notice to an error and starts rejecting sniffs which do not comply with the naming conventions.
Includes updated …
> Ruleset: remove support for sniffs not following the naming conventions 

- src/Ruleset.php
- tests/Core/Ruleset/ExpandRulesetReferenceInternalStandardTest.xml
- tests/Core/Ruleset/ExpandRulesetReferenceInternalTest.php
Standards called "Internal" were never really supported anyhow. This is now formalized.
Fixes #799
Related to #6
Removed:
* Support for external standards called "Internal".
> Ruleset: remove support for standards called "Internal"

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Sniffs/Strings/UnnecessaryStringConcatSniff.php
- src/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.1.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.php
- src/Standards/Squiz/ruleset.xml
Fixes squizlabs/PHP_CodeSniffer#2823
Related to #186
Removed:
- Removed `error` property of sniff `Generic.Strings.UnnecessaryStringConcat`
- This sniff now always produces errors
- To make this sniff produce warnings, include the following in a `ruleset.xml` or `[.]phpcs.xml[.dist]` file:
```xml
<rule ref="Generic.Strings.UnnecessaryStringConcat">
<type>warning</type>
</rule>
```
- Removed `error` property of sniff `Generic.Formatting.MultipleStatementAlignment`.
- This sniff now always produces warnings
- The `Generic.Formatting.MultipleStatementAlignment.IncorrectWarning` error code has been removed.
- Refer to the `Generic.Formatting.MultipleStatementAlignment.Incorrect` error code instead.
- The `Generic.Formatting.MultipleStatementAlignment.NotSameWarning` error code has been …
> Remove public error properties of sniffs that don't need them

- src/Runner.php
This ini setting has been deprecated by PHP itself.
Ref:
* squizlabs/PHP_CodeSniffer#3394
Removed:
- Removed use of the deprecated `auto_detect_line_endings` ini setting.
- This removes support for files with `\r` line endings.
> Runner: removed use of deprecated auto_detect_line_endings ini setting

- .gitattributes
Tests are no longer included in zip packages, but the test _framework_ files will be.
This is set up in this way to prevent external standards having to use `--prefer-source` when their (sniff) tests are using the PHPCS test framework.
Changed:
- Composer installs no longer include any test files.
- The test framework files will still be included to allow for use by external standards.
Fixes squizlabs/PHP_CodeSniffer#1908
Fixes squizlabs/PHP_CodeSniffer#3158
Closes #73
Fixes #636
> .gitattributes: tests are no longer included in zip packages

- .gitignore
- src/Ruleset.php
- tests/Core/Generators/GeneratorTest.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
- tests/Core/Generators/TextTest.php
- tests/Core/Ruleset/RegisterSniffsTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
- tests/Standards/AbstractSniffUnitTest.php
The PHPCS 2.7.1 release introduced a change to how sniff tests are run.
Originally, sniff tests would be run in the context of their ruleset. This could lead to parts of the sniff being untestable, like if the ruleset would exclude a error code or contained custom property settings.
As of PHPCS 2.7.1, sniff tests are run in isolation and no longer take the ruleset of the standard they belong to into account, which solves the above problem.
This change was introduced via commit 3df85dc.
Unfortunately, the way this change was made was via a change to the `Ruleset` class, not by changing the test framework.
It basically meant that the `Ruleset` class would now behave differently when the following two conditions were met:
1. It was being used in a test context (`PHP_CODESNIFFER_IN_TESTS` …
> Ruleset: remove test specific code 

- tests/Standards/AbstractSniffTestCase.php
Previously, sniff tests without case files would silently pass.
Changed:
- Tests which extend the `AbstractSniffTestCase` for which no test case files (`.inc` files) can be found, will now be marked as "incomplete".
- Previously, those tests would silently pass.
> AbstractSniffTestCase: mark sniff tests without test case files as incomplete

- tests/Standards/AbstractSniffTestCase.php
As per issue #300, the PHPCS native `AbstractSniffUnitTest` test case should flag sniff test case files which would lead to fixes, but for which no `.fixed` file is available to verify the fixes against.
It should also fail a test run when this occurs.
This commit makes it so.
Changed:
All test case files (`inc`) which would be changed by the sniff under test if running the fixer, are now required to be accompanied by a `*.fixed` file.
Fixes #300
> AbstractSniffTestCase: flag missing `.fixed` files

- CodeSniffer.conf.dist
- README.md
- src/Config.php
Changed:
The default coding standard has changed from `PEAR` to `PSR12`.
> Change default standard from PEAR to PSR12

- src/Config.php
Changed:
The `Config::setSettings()` method is now a `void` method.
> Config::setSettings(): void method should not return

- src/Config.php
- src/Ruleset.php
- tests/ConfigDouble.php
- tests/Core/Config/AbstractRealConfigTestCase.php
- tests/Core/Config/IssueSquiz2675Test.php
- The `Config::setConfigData()` method is no longer static.
- The associated (`private`) `Config::$overriddenDefaults` property is also no longer static.
Fixes squizlabs/PHP_CodeSniffer#2675
> Config::setConfigData() is no longer static

- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesATest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesBTest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesIncludeATest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesIncludeBTest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesSubIncludeATest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetConfigDirectivesTest/ProcessRulesetConfigDirectivesSubIncludeBTest.xml
- tests/Core/Ruleset/ProcessRulesetConfigDirectivesTest.php
This is a completely different solution to issue squizlabs/PHP_CodeSniffer#2197, compared to the original solution which was previously committed to the old 4.0 branch.
The "old' solution was to process rulesets "top to bottom", i.e. every directive is processed when "read" while recursing through the rulesets. I've evaluated that solution carefully and found it counter-intuitive, which means that I expect that it would raise lots of support questions. I also expect that solution to break way more rulesets than is justified to solve issue squizlabs/PHP_CodeSniffer#2197.
The original solution would require ruleset maintainers to have a high awareness of what configs are being set in included rulesets. Included rulesets are often PHPCS native standards or external standards, which are both …
> Ruleset: configs in higher level ruleset(s) overrule configs set in included ruleset(s)

- tests/Core/Ruleset/Fixtures/ProcessRulesetIniDirectivesTest/ProcessRulesetIniDirectivesIncludeATest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetIniDirectivesTest/ProcessRulesetIniDirectivesIncludeBTest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetIniDirectivesTest/ProcessRulesetIniDirectivesSubIncludeATest.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetIniDirectivesTest/ProcessRulesetIniDirectivesTest.xml
- tests/Core/Ruleset/ProcessRulesetIniDirectivesTest.php
Looks like setting ini values from rulesets already behaves as desired, so this commit just adds tests documenting and safeguarding this behaviour.
_N/A_
> Ruleset: document ini overruling behaviour via tests

- src/Config.php
- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/.phpcs.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/config/phpcs/include-overrules.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/phpcs.xml.dist
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/vendor/OrgName/ExtStandard/bootstrap.php
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/vendor/OrgName/ExtStandard/ruleset.xml
- tests/Core/Ruleset/ProcessRulesetCliArgsTest.php
Again, this is a completely different solution to issues squizlabs/PHP_CodeSniffer#2395, squizlabs/PHP_CodeSniffer#2597, squizlabs/PHP_CodeSniffer#2602, compared to the original solution which was previously committed to the old 4.0 branch in response to issue squizlabs/PHP_CodeSniffer#2197.
The "old' solution was to process rulesets "top to bottom", i.e. every directive is processed when "read" while recursing through the rulesets. I've evaluated that solution carefully and found it counter-intuitive, which means that I expect that it would raise lots of support questions. I also expect that solution to break way more rulesets than is justified to solve these issues.
The original solution would require ruleset maintainers to have a high awareness of what CLI args are being set in …
> Ruleset: (CLI) `<arg>` settings in higher level ruleset(s) overrule args set in included ruleset(s)

- src/Ruleset.php
- src/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
Consistently cast all variation of `'true'`, `'false'` and `'null'` to respectively `true`, `false` and `null`. Including when these values are used as values in an array property value.
Includes minor simplification now possible for the `Generic.PHP.ForbiddenFunctions` sniff.
Changed:
- Type casting for sniff property values set from within a ruleset has been made more consistent. [#708]
- `true` and `false` will now always be set to a boolean value, independently of the case in which the value was provided.
- `null` will now be set to an actual `null` value. Previously, the sniff property would have been set to string `'null'`.
- Array element values will now also get the type casting treatment. Previously, array values would always be strings.
Fixes #708
> Ruleset: improve type handling of user-set properties

- src/Standards/Squiz/Sniffs/PHP/HeredocSniff.php
Until now, the sniff would blindly forbid both heredoc and nowdoc syntax.
With the change as proposed in this PR, the sniff still does so, but now uses different error codes for encountered heredocs vs nowdocs, which allows for selectively ignoring one or the other, either from the ruleset or inline.
Includes updating the error message to be more specific for each error code as well.
- The error code `Squiz.PHP.Heredoc.NotAllowed` has been replaced by `Squiz.PHP.Heredoc.HeredocNotAllowed` and `Squiz.PHP.Heredoc.NowdocNotAllowed`.
- This allows for forbidding either heredocs or nowdocs without forbidding both.
Fixes squizlabs/PHP_CodeSniffer#2318
> Squiz/Heredoc: make sniff more modular

- src/Files/File.php
- src/Standards/Generic/Tests/Files/ByteOrderMarkUnitTest.php
- src/Standards/Generic/Tests/PHP/DisallowAlternativePHPTagsUnitTest.php
- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.php
- tests/Core/ErrorSuppressionTest.php
- tests/Core/File/AddMessageSelectiveInternalHandlingTest.php
- tests/Core/File/AddMessageSelectiveInternalHandlingTest.xml
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3915 + rebased against the 4.0 branch:
> ### ErrorSuppressionTest: prevent Internal errors
> 
> ... about a mismatch in line endings when the code "template" is defined using a heredoc with Linux line endings, while the code snippets being inserted into the code "template" were using line endings matching the OS on which the tests were being run.
> 
> ### File::addMessage(): do not ignore Internal errors when scanning selectively
> 
> When either the `--sniffs=...` CLI parameter is used, or the `--exclude=...` CLI parameter, the `File::addMessage()` method bows out when an error is passed which is not for one of the selected sniffs/is for one of the excluded sniffs.
> 
> Unfortunately, this "bowing out" did not …
> 4.0 | File::addMessage(): do not ignore Internal errors when scanning selectively

- .github/CONTRIBUTING.md
- requirements.php
- src/Files/File.php
- src/Files/LocalFile.php
- src/Fixer.php
- src/Reports/Cbf.php
- src/Reports/Code.php
- src/Reports/Diff.php
- src/Ruleset.php
- src/Runner.php
- src/Sniffs/AbstractPatternSniff.php
- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php
- src/Tokenizers/Comment.php
- src/Tokenizers/PHP.php
- src/Tokenizers/Tokenizer.php
- src/Util/Cache.php
- src/Util/MessageCollector.php
- src/Util/Timing.php
- src/Util/Writers/StatusWriter.php
- tests/Core/AbstractWriterTestCase.php
- tests/Core/Ruleset/DisplayCachedMessagesTest.php
- tests/Core/Ruleset/ShowSniffDeprecationsTest.php
- tests/Core/Runner/PrintProgressDotsTest.php
- tests/Core/Runner/PrintProgressTest.php
- tests/Core/StatusWriterTestHelper.php
- tests/Core/Util/MessageCollector/MessageCollectorTest.php
- tests/Core/Util/Timing/TimingTest.php
- tests/Core/Util/Writers/StatusWriterTest.php
This is a different implementation of the principle for writing to `stdErr` as originally committed in 2020.
In the original implementation:
* The methods for writing to `stdErr` were added to the `Common` utility method class.
As this is a group of methods which belong closely together, moving them to a separate class seems more appropriate.
* The `[force]write()` method(s) had a (bool) `$suppressNewline` parameter with a default value of `false`.
This has been changed to a (int) `$newlines` parameter with a default value of `1`, which provides more flexibility.
* Writing to `STDERR` was hard-coded in the `forcePrint()` method.
As PHPUnit has no facility for capturing output send to `stdErr`, this made testing output send to `stdErr` impossible.
The stream to write to has now been set up …
> (Nearly) All status, debug, and progress output is now sent to STDERR instead of STDOUT

- src/Reports/Cbf.php
- src/Reports/Code.php
- src/Reports/Full.php
- src/Reports/Info.php
- src/Reports/Source.php
- src/Reports/Summary.php
- src/Reports/VersionControl.php
- src/Runner.php
~~**⚠️ This PR depends on PR #1010, which needs to be merged first. ⚠️**~~
---
What with the Timing output now going to `STDERR`, we no longer need to be concerned about the Timing output ending up in `json`, `csv` or `xml` reports (to name a few).
In effect, this means, we can now always display Timing and memory usage info at the end of the run.
I'm making one exception though: timing will not be displayed when running in `quiet` mode.
Add to changelog entry for STDERR change:
- With this change in place, timing and memory consumption stats will now be displayed more often as it won't interfere with reports.
> Always display timing after run, except when in quiet mode

- src/Tokenizers/Tokenizer.php
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.inc
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.php
~~**⚠️ This PR depends on PR #1010, which needs to be merged first. ⚠️**~~
---
While some specific situations related to the array keyword were already tested, this adds a more comprehensive set of tests, though I have no doubt a lot more edge cases should probably be added. Even so, this is a good start.
_I didn't dare to make this change while JS/CSS were still supported, but this should be a safe change now._
For all PHP parenthesis owners, the open parenthesis MUST be the next non-empty token.
There is only one exception to this rule and that is the `T_FUNCTION` keyword where a `T_STRING` function name and potentially a `&` for return by reference are also allowed between.
If the parenthesis owner is not the next valid token, the token should not be marked as a parenthesis owner, not …
> Tokenizer::createTokenMap(): stabilize code for parenthesis owners 

- src/Util/Tokens.php
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.inc
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.php
~~**⚠️ This PR depends on PR #1010 + #1012, which need to be merged first. ⚠️**~~
---
- T_ISSET, T_UNSET, T_EMPTY, T_EVAL and T_EXIT tokens now contain parenthesis information.
- Previously, you had to find the opening and closing parenthesis by looking forward through the token stack.
- Now, you can use the `parenthesis_owner`, `parenthesis_opener` and `parenthesis_closer` array indexes.
Fixes #23
> Tokenizer: isset/unset/empty/eval/exit/die now contain parenthesis information

- src/Sniffs/AbstractPatternSniff.php
- src/Standards/Generic/Sniffs/CodeAnalysis/EmptyPHPStatementSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.2.inc
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.2.inc.fixed
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.php
- src/Standards/PSR12/Sniffs/Files/OpenTagSniff.php
- src/Standards/PSR12/Tests/Files/OpenTagUnitTest.2.inc.fixed
- src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php
- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Tokenizers/PHP.php
- tests/Core/File/FindStartOfStatementTest.php
- tests/Core/Tokenizers/PHP/PHPOpenTagEOF1Test.php
- tests/Core/Tokenizers/PHP/PHPOpenTagTest.inc
- tests/Core/Tokenizers/PHP/PHPOpenTagTest.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenMiscTest.php
~~**⚠️ UPDATED: This PR depends on PR #1010, which needs to be merged first. ⚠️**~~ 
---
Change tokenization of long PHP open tags to no longer include whitespace (single space/new line).
This ensures the tokenization of all PHP open tags - long open tags `<?php`, short open tags `<?` and short open echo tags `<?=` - is consistent and should simplify handling of open tag tokens in sniffs and lower the cognitive load of sniff developers.
As per the detailed proposal in ticket #593.
Includes extensive unit tests, both ensuring the correct tokenization, as well as safeguarding consistency across the different open tags.
Includes the following additional updates to maintain the pre-existing behaviour:
* `AbstractPatternSniff` The `AbstractPatternSniff` tokenizes an arbitrary code pattern to …
> Tokenizer/PHP: change tokenization of long PHP open tags

- src/Tokenizers/Comment.php
- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/Comment/CommentTestCase.php
Previously, only tokens of type `T_DOC_COMMENT_OPEN_TAG ` would receive a `comment_closer` index and tokens of type `T_DOC_COMMENT_CLOSE_TAG ` would receive a `comment_opener` index (asymmetrically).
This commit changes this to set both the `comment_opener` as well as the `comment_closer` indexes on all docblock tokens. This should allow for more flexibility for sniffs examining docblocks.
Includes updated tests to safeguard this change.
Changed:
All `T_DOC_COMMENT_*` tokens will now have the `comment_opener` and `comment_closer` indexes set.
Fixes #484
> Tokenizer/Comment: add docblock open + close ptr to all docblock tokens

- phpcs.xml.dist
- src/Filters/Filter.php
- tests/Core/Filters/Filter/ShouldProcessFileWithoutExtensionTest.php
Added:
Files without extension can now be scanned if the path is passed in directly.
- Previously, files without extension would always be ignored.
- Now, files with no extension are checked if explicitly passed on the command line or specified in a ruleset.
- Files without extension will still be ignored when scanning directories recursively.
Fixes squizlabs/PHP_CodeSniffer#2916
> Filter: files without extension are no longer ignored if the path is passed in directly

- src/Runner.php
- tests/Core/Runner/Fixtures/AllFilesExcludedSetA/placeholder.inc
- tests/Core/Runner/Fixtures/AllFilesExcludedSetA/placeholder.phpt
- tests/Core/Runner/Fixtures/AllFilesExcludedSetB/placeholderA.php
- tests/Core/Runner/Fixtures/AllFilesExcludedSetB/placeholderB.php
- tests/Core/Runner/Fixtures/AllFilesExcludedSetB/placeholderC.php
- tests/Core/Runner/Fixtures/AllFilesExcludedSetB/placeholderD.php
- tests/Core/Runner/RunAllFilesExcludedErrorTest.php
Show error message if no files were checked during a run and exit with a non-zero exit code.
Note: the tests only cover the new error message and not the situation where this message would _not_ be shown (outside the scope of this change).
Added:
An error message is now displayed if no files were checked during a run.
- This occurs when all of the specified files matched exclusion rules, or none matched filtering rules.
Fixes squizlabs/PHP_CodeSniffer#1595
> Runner: error message if no files were checked during a run

- .github/workflows/test.yml
- src/Config.php
- tests/Core/Config/IniSetTest.php
- tests/Core/Ruleset/IniSetFailIniOnlyTest.xml
- tests/Core/Ruleset/IniSetFailIniPerDirTest.xml
- tests/Core/Ruleset/IniSetFailIniSystemTest.xml
- tests/Core/Ruleset/IniSetSuccessTest.xml
- tests/Core/Ruleset/ProcessRulesetIniSetTest.php
Inspired by discussion #415.
Previously, when a PHP ini option which cannot be changed at runtime was passed to PHPCS, it would be silently ignored (by PHP, PHPCS would still try to handle it, but would not report that PHP did not change the value).
This commit changes that behaviour by adding a new "ERROR: Ini option %s cannot be set at runtime" error to alert the end-user to the fact that they are passing a PHP ini option which PHPCS cannot change.
The new error will be thrown both when the user passes the invalid ini setting via the command line, as well as when it is passed via a custom ruleset.
The behaviour when trying to change an ini setting which _doesn't exist_ (typo, extension not available) is unchanged. In that case, the ini directive will still be silently ignored.
Includes …
> Config: show user friendly error message when ini change failed

- src/Standards/Generic/Docs/WhiteSpace/GotoTargetSpacingStandard.xml
- src/Standards/Generic/Sniffs/WhiteSpace/GotoTargetSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/GotoTargetSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/GotoTargetSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/GotoTargetSpacingUnitTest.php
What with the colon for a goto target label no longer being tokenized to be included in the label token, let's allow for people to enforce no space between the label and the colon.
This commit introduces a new sniff to do just that.
Includes documentation.
Added:
New sniff `Generic.WhiteSpace.GotoTargetSpacing` to enforce no space between the label of a `goto` target and the colon following it.
Related to #185
> :sparkles: New Generic.WhiteSpace.GotoTargetSpacing sniff

- src/Ruleset.php
- src/Util/Standards.php
- tests/Core/Filters/AbstractFilterTestCase.php
- tests/Core/Ruleset/ConstructorTest.php
- tests/Core/Ruleset/RegisterSniffsTest.php
- tests/Core/Ruleset/RuleInclusionAbsoluteLinuxTest.php
- tests/Core/Ruleset/RuleInclusionAbsoluteWindowsTest.php
- tests/Core/Ruleset/RuleInclusionTest.php
- tests/Core/Standards/StandardRulesetsQATest.php
> Modernize: use `$levels` parameter for `dirname()`

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
- src/Standards/PEAR/Tests/WhiteSpace/ScopeIndentUnitTest.php
The `Generic.WhiteSpace.ScopeIndent` sniff includes a `private` boolean `$debug` property which can be toggled to enable/disable showing sniff specific debug information. By default, debug information is not shown.
Showing of debug information can be enabled in the following manner:
1. By explicitly changing the default value of the property to `true` in the sniff file (without committing as the default should not change in the committed code).
2. By running with the `--runtime-set scope_indent_debug 1` flag set.
3. By setting the `scope_indent_debug` config setting to `true` from a custom ruleset.
4. By setting a system-wide default for the `scope_indent_debug` config setting by running `--config-set scope_indent_debug 1`.
The `Generic.WhiteSpace.ScopeIndent` sniff includes a condition …
> Generic/ScopeIndent: remove check for test constant from src code

- src/Util/Tokens.php
* The `@var` tags should be first in a property docblock according to the PHPCS rules for this codebase (but this wasn't flagged due to an exception being applied - and yes, I will be removing that exception soon).
* Use full version number in the `@deprecated` tags, i.e. `4.0.0` instead of `4.0`.
_N/A_
> Tokens: fix docblocks

- src/Standards/PSR1/Docs/Files/SideEffectsStandard.xml
Fix syntax error in `PSR1.Files.SideEffects` XML documentation code example.
PSR1.Files.SideEffects: fix syntax error in the XML documentation
> PSR1/SideEffects: fix syntax error in XML documentation code example

- src/Standards/PSR2/Docs/Namespaces/NamespaceDeclarationStandard.xml
PSR2.Namespaces.NamespaceDeclaration: minor fixes to the XML documentation
> PSR2/NamespaceDeclaration: improve XML documentation

- src/Standards/Generic/Sniffs/Strings/UnnecessaryHeredocSniff.php
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.1.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.2.inc
- src/Standards/Generic/Tests/Strings/UnnecessaryHeredocUnitTest.2.inc.fixed
If the original heredoc contained an escaped variable or an escaped backslash (neither of which need heredoc), the nowdoc version of the text string would contain stray backslashes as these escapes are not needed in nowdocs, so would be interpreted as literals.
Fixed now.
If the original heredoc contained an escape sequence, but no variable interpolation or expressions, it would be flagged as unnecessary and fixed to nowdoc, even though escape sequences are not supported in nowdocs.
Fixed now.
Fixed: Generic.Strings.UnnecessaryHeredoc - false positive for heredocs containing escape sequences
Fixed: Generic.Strings.UnnecessaryHeredoc - fixer would not clean up escape sequences which aren't needed in nowdocs
Follow up on #633
> Generic/UnnecessaryHeredoc: 2 bug fixes involving escape sequences

- src/Runner.php
Follow up on #1010 and #1011.
PR #1011 moved the Timing display to the `Runner` class, but didn't take the change to PR #1010, introducing the `writeNewline()` method into account. Fixed up now.
_N/A_
> Runner: use StatusWriter::writeNewline()

- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
- src/Standards/PEAR/Tests/WhiteSpace/ScopeIndentUnitTest.php
Follow up on #1036.
The `Config::setConfigData()` expects a `string` for the config value, even though in this case, it will still be cast back to boolean in the ScopeIndent sniff itself.
_N/A_
> Generic/ScopeIndent: fix passed param type

- .github/workflows/test.yml
- .github/workflows/validate.yml
As things are, the CS check for the PHPCS codebase is run in the `test` workflow as an integration test and will show inline annotations about code style issues in PRs. These annotations are intended to help contributors identify issues with their PR.
As the `test` workflow is run against a large range of PHP versions and OSes, this showing of the annotations was limited to PHP 8.4 + Ubuntu to prevent the contributor seeing a wall of duplicate annotations when issues would be found (one for each test build).
However, the `test` workflow also uses the "fail-fast" option, cancelling the builds on the first failure, which means the PHP 8.4/Ubuntu build may have been cancelled before it was run, in which case, the inline CS annotations don't show at all.
This means the current setup is …
> GH Actions: fix cs annotations not showing

- src/Fixer.php
- tests/Core/Fixer/FixFileReturnValueAllGoodTest.xml
- tests/Core/Fixer/FixFileReturnValueConflictTest.xml
- tests/Core/Fixer/FixFileReturnValueNotEnoughLoopsTest.xml
- tests/Core/Fixer/FixFileReturnValueTest.php
- tests/Core/Fixer/Fixtures/TestStandard/Sniffs/FixFileReturnValue/AllGoodSniff.php
- tests/Core/Fixer/Fixtures/TestStandard/Sniffs/FixFileReturnValue/ConflictSniff.php
- tests/Core/Fixer/Fixtures/TestStandard/Sniffs/FixFileReturnValue/NotEnoughLoopsSniff.php
- tests/Core/Fixer/Fixtures/TestStandard/ruleset.xml
- tests/Core/Fixer/Fixtures/test.inc
Over the years, I'd noticed on numerous occasions that `phpcbf` could update the file under scan, even when the end-result of the run was a "FAILED TO FIX".
In my opinion, if the fixer didn't manage to fix the file completely, the file should not be updated as the end-result may be worse than before.
The trouble was that this didn't _always_ happen, but only some of the time, so this needed some debugging to figure out under what exact conditions the file write would happen (and when it wouldn't happen).
To demonstrate the issue, run the following commands with the branch for this PR checked out and the change in the `Fixer` file reverted:
```bash
phpcbf --suffix=.fixed ./tests/Core/Fixer/Fixtures/test.inc --standard=./tests/Core/Fixer/FixFileReturnValueNotEnoughLoopsTest.xml
```
Now …
> Fixer::fixFile(): bug fix for incorrect return value

- phpcs.xml.dist
- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.php
As things are, the `VariableComment` sniff only allows `@see` tags and `@var` tags in property docblocks.
This practice feels dated to me, as commonly used tags, such as `@link`, `@deprecated` etc are not allowed.
This commit replaces the generic `TagNotAllowed` error code in the sniff with a more modular `[TagName]TagNotAllowed` error code.
This allows for rulesets to selectively ignore the `TagNotAllowed` error code for specific tags the ruleset maintainer wants to allow for the code base under scan.
... for this codebase.
Changed:
- The error code `Squiz.Commenting.VariableComment.TagNotAllowed` has been replaced by a dynamic `Squiz.Commenting.VariableComment.[TagName]TagNotAllowed` error code.
- This allows for selectively allowing specific tags by excluding the error …
> Squiz/VariableComment: make errorcode for "TagNotAllowed" warning modular

- src/Sniffs/AbstractVariableSniff.php
- src/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php
- src/Standards/Generic/Sniffs/Files/InlineHTMLSniff.php
- src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- src/Standards/Generic/Sniffs/PHP/CharacterBeforePHPOpeningTagSniff.php
- src/Standards/Generic/Sniffs/VersionControl/SubversionPropertiesSniff.php
- src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- src/Standards/PSR1/Sniffs/Methods/CamelCapsMethodNameSniff.php
- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Squiz/Sniffs/PHP/DisallowSizeFunctionsInLoopsSniff.php
- src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Tokenizers/PHP.php
- src/Util/Common.php
- tests/Core/Util/Common/SuggestTypeTest.php
~~:warning: This PR depends on PR #1039, which needs to be merged first. ⚠️~~
---
This PR modernizes various usages of constant arrays in the public API to use class constants instead of properties.
The properties still exist, but are now deprecated and will be removed in PHPCS 5.0.
In a separate PR, which will be pulled at a later point in time (but before the 4.0.0 release), the same will be done for additional usages of constant arrays, which are **_not_** in the public API.
---
As the property was in the public API, the class constant is also public and the property has been deprecated, to be removed in PHPCS 5.0.
Includes changing the array format from a list of strings to an associative array with the key and value for each entry holding the same string to allow for using `isset()` …
> Modernize: use class constants for constant arrays (public API)

- phpcs.xml.dist
- src/Config.php
- src/Generators/HTML.php
- src/Util/Help.php
- src/Util/MessageCollector.php
- src/Util/Timing.php
- tests/Core/Ruleset/AbstractRulesetTestCase.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
Constant visibility is available in PHP since PHP 7.1. This commit adds the visibility to all class constants currently in the codebase and starts enforcing constant visibility being required.
In most cases, the visibility remains the same as before, i.e. `public`, however, there are a couple of exceptions, which could be considered a breaking change:
* `PHP_CodeSniffer\Generators\HTML::STYLESHEET` (was `public`, now `private`)
- Even though the class is not `final`, the `Config` only allows for requesting a PHPCS native `Generator` class, so the chances of the class being extended are very slim.
- On top of that, this was a function local variable until a few months ago, so chances of any external access to the constant being active are also slim based on the timing.
* …
> Modernize: add constant visibility

- src/Files/File.php
- src/Fixer.php
- src/Reports/Cbf.php
- src/Reports/Diff.php
Now debug output is written to STDERR instead of STDOUT and the StatusWriter is paused while the Fixer is running, the output buffering during fixing can be removed.
_N/A_ (internal implementation detail)
> Fixer: remove output buffering

- src/Config.php
- src/Runner.php
- src/Util/Standards.php
This commit introduces a new `Standards::prepareInstalledStandardsForDisplay()` method. This new method only prepares the "list" into displayable phrases. It doesn't include output formatting with new lines, that's up to the actual display.
This new method allows for getting rid of some output buffering calls in select places.
Includes improving the readability of the "coding standard is not installed" error.
Includes deprecating the `Standards::printInstalledStandards()` method, which is now no longer used by PHPCS itself.
Deprecated:
* `Standards::printInstalledStandards()`. Use `echo Standards::prepareInstalledStandardsForDisplay()` instead.
This is the readability improvement I mention above:
> Standards: introduce `prepareInstalledStandardsForDisplay()` method

- src/Config.php
I don't see why output buffering is needed here.
The `DeepExitException` accepts/allows an empty string as the "message", so there is no reason to collect the screen output via buffering first, only to echo it out again as soon as the exception is caught (by the `Runner` class).
_N/A_
> Config: remove some more output buffering

- src/Runner.php
- tests/Core/Runner/RunAllFilesExcludedErrorTest.php
Errors should go to `STDERR`. This was mostly handled in PR #1010.
However, the `Runner` class contains two `catch (DeepExitException $e)` blocks which are used to exit "early", both for legitimate requests (`--version`, `-i` etc), as well as for error output.
This commit changes how the output is handled in these catch blocks, to differentiate between legitimate requests (exit code `0`) and error output, sending legitimate output to `STDOUT` and sending error output to `STDERR`.
Includes updating a unit test to reflect the change.
_N/A_ This change is covered by the changelog entry for #1010.
Related to squizlabs/PHP_CodeSniffer#1612
> Runner: use StatusWriter for caught errors

- src/Reporter.php
This property was introduced in commit 9eaaccd58ed4ffa7d28bb3a1d501a77205c363ed (March 2014) and made redundant in commit f61025c5617a493b655a5f572a3e13749b3a51f8 (March 2015) by the introduction of the `Util\Timing` class. It hasn't been used since.
Time to remove this dead wood.
Removed:
* Unused static `PHP_CodeSniffer\Reporter::$startTime` property.
> Reporter: remove redundant property

- tests/Core/Standards/StandardRulesetsQATest.php
With the change to the `StatusWriter` for writing error output to `STDERR`, this test was no longer working correctly as the output bufffering was only catching output send to `STDOUT`, which means the protection this test was supposed to give was no undone.
Fixed now. And this includes removing yet some more output buffering.
_N/A_
> StandardRulesetsQATest: fix the test

- tests/Core/Tokenizers/PHP/ArrayKeywordTest.php
- tests/Core/Tokenizers/PHP/AttributesTest.php
- tests/Core/Tokenizers/PHP/BackfillFnTokenTest.php
- tests/Core/Tokenizers/PHP/DNFTypesTest.php
- tests/Core/Tokenizers/Tokenizer/CreateParenthesisNestingMapDNFTypesTest.php
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapArrayParenthesesTest.php
These alignment issues were, for some unknown reason, not picking up by the PHPCS native sniffs. This may need investigating, but as it involves the `Squiz.Arrays.ArrayDeclaration` sniff, this is not really worth the time.
Fixed now anyway by locally using a few outside sniffs.
_N/A_
> CS: various array formatting fixes

- src/Standards/PSR2/Docs/ControlStructures/SwitchDeclarationStandard.xml
The sniff no longer checks `case` keyword indentation as of commit https://github.com/PHPCSStandards/PHP_CodeSniffer/commit/4a39005f5a9314984f814f2237ed94dbe9619117, but the corresponding XML documentation was not updated. This commit aligns the documentation with the current sniff behavior by removing mentions of `case` indentation checks.
This commit updates the valid and invalid code examples in a `<code_comparison>` block, as the `There must be a comment when fall-through is intentional in a non-empty case body` error is only triggered for non-empty `case` bodies. It also fixes the positioning of the `<em>` tags in the modified code examples.
- Documentation title should match the sniff name.
- Use different `<standard>` blocks for each error triggered by the
sniff.
- Minor changes to …
> PSR2/SwitchDeclaration: improve XML documentation

- .remarkrc
While I'm loath to add even more URLs to the ignore list, StackOverflow is currently causing the builds to fail by returning a `403`, while manually visiting the URL, works absolutely fine (`200`).
_N/A_
> Remark/dead URL check: skip stack overflow link

- src/Config.php
The `--cache` option could not be tested as the `Config` class did not allow for it to be set in a test situation.
This "conditional ignore" was introduced in commit 24c7a7f7a30b38fffcaf0aecedc6882e97f5ad4e around the same time the caching feature was introduced. The commit message doesn't give a reason for introducing the conditional ignore. I can only guess why and my guess would be that it was to prevent test runs being influence by dev-user specific system-wide defaults from a `CodeSniffer.conf` file.
In my opinion, that is not a good reason for keeping the "conditional ignore".
* First of all, the default setting is for the cache to be _off_, so by default, tests wouldn't use the cache anyhow.
* Second of all, the problem of interference from dev-user specific system-wide defaults …
> Config: remove more test specific conditions

- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/.phpcs.xml
- tests/Core/Ruleset/Fixtures/ProcessRulesetCliArgsTest/phpcs.xml.dist
- tests/Core/Ruleset/ProcessRulesetCliArgsTest.php
Follow up on #1005
Was previously blocked by the `Config` class not allowing for the `cache` setting to be changed from within the tests, which was fixed via #1068. Also see #966
_N/A_
> ProcessRulesetCliArgsTest: add tests for `cache` arg

- src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.php
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.php
- src/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.inc
- src/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.php
- src/Util/Tokens.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3636 + rebase for the 4.0 branch:
> The function call spacing for anonymous class instantiations was so far not checked by these ~~or any other PHPCS native~~ sniffs.
> 
> In my opinion, object instantiations of anonymous classes should be treated the same an object instantiations of non-anonymous classes.
> 
> The `PEAR.Functions.FunctionCallSignature` and the `PSR2.Methods.FunctionCallSignature` sniffs check the object instantiation spacing for non-anonymous classes, so seem like the logical place to also check the spacing for anonymous class object instantiations.
> 
> To add this support, the `T_ANON_CLASS` token has been added to the `Tokens::$functionNameTokens` array.
> 
> Notes:
> * As PSR12 does not …
> 4.0 | PEAR/PSR2/FunctionCallSignature: support anonymous classes

- .github/workflows/test.yml
- tests/Core/Config/GeneratorArgTest.php
- tests/Core/Config/SniffsExcludeArgsTest.php
- tests/Core/Ruleset/DisplayCachedMessagesTest.php
Some tests had sneaked in which would pass in CS mode, but not in CBF mode - at least, not without some tweaks.
CBF specific tests were already being run in CBF mode and run against every supported PHP version.
This commit now adds a test run of the complete test suite in CBF mode against one (high) PHP version to ensure that (new) tests always take both modes into account and no new issues like this can sneak in.
_N/A_
> Tests should pass in CBF mode

- src/Config.php
- tests/Core/Config/ReportArgsTest.php
There are three CLI arguments related to the reporting:
* `--report=[comma separated list]`
* `--report-file=[path to file]`
* `--report-<type>=[path to file]`
The `--report-file...` option is ignored when in CBF mode. Whether that is the correct behaviour or not, is outside the scope of the current bug fix.
In the `Config::processLongArgument()` method, the `--report-file` option is handled _before_ the `--report-<type>` option to ensure that `--report-file` is handled correctly, as the handling of the `--report-<type>` argument is based on seeing the prefix `--report-`, which overlaps with `--report-file`.
However, this logic was broken in CBF mode, as in that case, the `--report-file` CLI arg would still fall through to the `--report-<type>` handling, which would break the setting of …
> Config: bug fix - "reports" could get set incorrectly when in CBF mode

- src/Util/Help.php
The help info did not mention that multiple reports can be requested in one go. Fixed now.
Improved the help information about "reports".
> Help: improve information about requesting reports

- src/Exceptions/GeneratorException.php
- src/Generators/Generator.php
- src/Generators/HTML.php
- src/Generators/Markdown.php
- tests/Core/Generators/GeneratorTest.php
- tests/Core/Generators/HTMLTest.php
- tests/Core/Generators/MarkdownTest.php
Make errors encountered when processing XML documentation more informative by providing more specific error messages via a dedicated `GeneratorException`, which extends the PHP native `DomainException`.
Ref:
* https://www.php.net/class.domainexception
The `Generator` classes will now throw a `PHP_CodeSniffer\Exceptions\GeneratorException` when encountering errors in the documentation XML.
> 4.0 | Generators/Generator: improve error messages

- .github/workflows/test.yml
This commit fixes two issues:
1. The PHPUnit coverage cache warming step was not being run for PHPUnit 10 or 11, while it should be.
2. The code coverage build against PHP 8.1 started failing after the merge of PR #871, which started polyfilling the tokens for PHP 8.4 asymmetric visibility. This failure was caused by the following error:
```
Message:  Token T_PUBLIC_SET has ID of type string, should be int. You may be using a library with broken token emulation
Location: /home/runner/work/PHP_CodeSniffer/PHP_CodeSniffer/vendor/nikic/php-parser/lib/PhpParser/compatibility_tokens.php:35
```
All in all, this is the umpteenth time that PHP Parser is being a pain in the neck for us, but it is what it is.
Either way, this commit should fix it (again).
_N/A_
> GH Actions/test: fix coverage runs

- tests/Core/Util/Timing/TimingTest.php
This should probably get a better test to ensure that the method actually returns microseconds, but time is difficult to test, which makes these assertions flaky and that's even worse.
For now, let's remove the flaky assertions.
_N/A_
> TimingTest: remove flaky assertions

- .github/workflows/test.yml
This was already correctly done for the `quicktest` and the `coverage` jobs, but apparently, changing the `runs-on` was missed for the `test` job.
Oops.
Fixed now.
_N/A_
> GH Actions: actually run tests against Windows

- .github/workflows/verify-release.yml
Adds a workflow job to send out a GH API request whenever a new release is tagged. The API request will trigger a workflow in the https://github.com/PHPCSStandards/schema.phpcodesniffer.com repository, which will update the schema.phpcodesniffer.com website.
As this is a cross-repo request, the standard GH secret is not sufficient. A Personal Access Token has been created on the PHPCSStandards organisation to facilitate workflow dispatches. This PAT has been added to the repo actions secrets, so it can be safely used in this workflow.
The PAT token is a fine-grained one and needs the following permissions for this dispatch to succeed:
- contents: read & write
- metadata: read only (automatically selected when selecting the contents permission)
Note: The Personal Access Token needs to be …
> GH Actions: auto-trigger update of schema website

- src/Standards/PEAR/Docs/Classes/ClassDeclarationStandard.xml
While reviewing PR #844 for the Squiz version of this sniff, @jrfnl discovered that the PEAR sniff's documentation did not cover all error conditions.
This adds code examples for all missing errors that should be caught by this sniff:
* OpenBraceWrongLine
* OpenBraceNotAlone
* SpaceBeforeBrace
Once approved & merged, we need to update the `PSR2\Classes\ClassDeclaration` documentation to include these cases, as well, since that sniff inherits this sniff but the docs do not currently cover the PEAR cases.
Add documentation to cover all errors caught by the PEAR.Classes.ClassDeclaration sniff.
Requested in PR #844
> [Doc] Cover all errors of PEAR ClassDeclaration

- tests/Core/Ruleset/ProcessRulesetShouldProcessElementTest.php
While running the test suite for this repository within a limited environment, several tests were failing without the `bcmath` PHP extension. This change skips these tests when the `bcmath` extension is not loaded. Elsewhere, we use this same syntax to skip tests which depend on the `bcmath` extension.
*None required*
> Declare dependency on bcmath extension

- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
While running the test suite for this repository within a limited environment, several tests were failing without the `git` command-line tool available. This change skips these tests when the `git` command is not found.
To reproduce the "no `git` available" scenario, check out a copy of this repository, and run: `docker run --rm -it -w /work -v "$PWD:/work" php:8.4-cli-alpine vendor/bin/phpunit --no-coverage --testdox --filter=Git`
*None required*
> Skip tests when 'git' command is not available

- README.md
Looks like the version badge via Packagist does not respect the default setting of not including pre-releases.
Fixed now by letting the badge retrieve the version via the GitHub API.
The bug has been reported to shields.io: badges/shields#11127
README: fixed stable version badge
> README: fix version badge

- src/Standards/PEAR/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/PEAR/Tests/NamingConventions/ValidVariableNameUnitTest.inc
- src/Standards/PEAR/Tests/NamingConventions/ValidVariableNameUnitTest.php
The PEAR sniff does not enforce the naming conventions when no visibility is specified, but for asymmetric visibility, visibility **_is_** specified, even though the "read" visibility may be implied, so in my opinion, the sniff should enforce the naming conventions like normal.
- PEAR.NamingConventions.ValidVariableName
> PEAR/ValidVariableName: update for properties with asymmetric visibility

- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
Per the FIG PSR-PER updates (next version), the "properties must have visibility declared" rule is also satisfied if only write visibility is declared.
> The `public` keyword MAY be omitted when using a set-visibility on a public-read property.
Includes updated test expectations (on the tests previously added in #871).
Per the FIG PSR-PER updates (next version), the "set-visibility MUST be _after_ the (read-)visibility".
This commit implements this, but as there may be two visibility modifiers, a minor refactor of the code involved in the wrong order checks for the `final` keyword and the `static` and `readonly` keywords is also needed as we can no longer presume that we can use the visibility keyword found with a search backwards to re-position other keywords.
Includes plenty of tests. …
> PSR2/PropertyDeclaration: update for properties with asymmetric visibility

- src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
These commits all update commenting sniffs to allow them to correctly find a docblock when asym visbility is used.
Prevent false positives for the "block comments must start with ..." error.
Prevent false negatives for the "incorrect space before star" error.
Prevent false positives for the "no docblock found" error.
- Squiz.Commenting.BlockComment
- Squiz.Commenting.DocCommentAlignment
- Squiz.Commenting.VariableComment
> Squiz/Commenting sniffs: update for properties with asymmetric visibility 

- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.php
This commit adds handling of the spacing after asymmetric visibility modifiers used for constructor property promotion to this sniff.
The spacing requirements are aligned with the spacing expectations of the `Squiz.WhiteSpace.ScopeKeywordSpacing` sniff, so the sniffs should not conflict with each other.
Additionally, the new check has a dedicated error code, which means that - if there would be a conflict anywhere - the asym visibility spacing check within this sniff can easily be turned off.
- Squiz.Functions.FunctionDeclarationArgumentSpacing
> Squiz/FunctionDeclarationArgumentSpacing: handle asym modifiers for constructor property promotion

- src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
Do still flag when the "get" (read) scope is not specified, but do so with a different error code to allow for rulesets to ignore that error.
- Squiz.Scope.MemberVarScope
> Squiz/MemberVarScope: update for properties with asymmetric visibility

- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Allow for the sniff to calculate the "lines before" correctly when asym visibility is used
- Squiz.WhiteSpace.MemberVarSpacing
> Squiz/MemberVarSpacing: update for properties with asymmetric visibility

- src/Tokenizers/PHP.php
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.inc
- tests/Core/Tokenizers/Tokenizer/CreateTokenMapParenthesesTest.php
When a function is named "fn", the `function` keyword should be set as the parenthesis owner.
While this works on PHPCS 3.x, I found while making PHPCSUtils compatible with 4.x, that this was broken on PHPCS 4.x for PHP 7.2 and 7.3 since commit da0d2247ec80bfb89a363dff905251fbaa754505.
This was due to token being seen as a `T_FN` token after the initial tokenization fixing round, so the `Tokenizer::createTokenMap()` would receive the `T_FN` token and not set the parenthesis owner index. The additional token processing run after that, would realize this is not in actual fact an arrow function and undo the retokenization (from `T_FN` back to `T_STRING`), which leaves the parentheses for this function declaration without an owner.
Fixed now by preventing the initial `T_STRING` to `T_FN` …
> Tokenizer/PHP: bug fix for missing parenthesis owner for method named "fn"

- src/Filters/Filter.php
This PR removes an if condition to maintain backwards compatibility that is no longer needed. It was added via https://github.com/squizlabs/PHP_CodeSniffer/commit/4982619b53bf7cea6255bc1dac57b89096c046f4 to preserve backwards compatibility back in a time when it was possible to programmatically set ignore patterns using `CodeSniffer::setIgnorePatterns()` (see https://pear.php.net/bugs/bug.php?id=19859). This method was removed a long time ago via https://github.com/PHPCSStandards/PHP_CodeSniffer/commit/f61025c5617a493b655a5f572a3e13749b3a51f8#diff-c36ecedca179eab0b3cd245e872a96ab26fa08e567437e167f4eda1779c15c89L431-L435, and since then, there is no way for users to set the ignore pattern array with numeric indices.
_N/A_
> Filter/Filter: remove outdated code that is no longer needed

- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
Follow up on #792, related to #1135
The `SpacingAfterVis[i]bility` error code was introduced in v 3.12.0 (March this year) for constructor property promotion. The `SpacingAfterSetVis[i]bility` error code was introduced in v 3.13.1 (this month) for constructor property promotion with asym visibility.
Both contained the same typo.
PR #1135 fixes the asym error code and will be included in PHPCS 3.13.2.
This commit now fixes the non-asym error code and will be included in PHPCS 4.0.0.
Changed: Squiz.Functions.FunctionDeclarationArgumentSpacing: the `SpacingAfterVisbility` error code to `SpacingAfterVisibility`
> Squiz/FunctionDeclarationArgumentSpacing: fix typo in `SpacingAfterVis[i]bility` error code

- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.php
As discussed in https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/482#pullrequestreview-2062765716 (see "Commit 6" and "Commit 7" sections), `Generic.ControlStructures.InlineControlStructure` now consistently handles all control structures without a body by bailing early. This PR extends the existing behavior for `while` and `for` to also include `do while`, `else`, `elseif`, `if`, and `foreach`. Note that in #482, I did not include `do while`, but I believe it should be included, and it is now part of this PR.
Previously, the sniff would incorrectly flag these empty control structures as inline control structures that needed curly braces. This change makes the behavior consistent across all control structures. For `else`, `elseif`, `if`, and `foreach`, the fixer would remove the …
> Generic/InlineControlStructure: bail early for control structures without body

- CHANGELOG.md
> Changelog for the 3.13.2 release

- CHANGELOG.md
- src/Config.php
Includes updating the Config::STABILITY constant.
_N/A_
> Changelog for the 4.0.0RC1 release

- .github/CONTRIBUTING.md
PHPCS convention is to define data providers below the test method and to name them using the "data" prefix. This PR is an attempt to document this convention in the CONTRIBUTING.md guide.
_N/A_
> Add a note about using data providers to the CONTRIBUTING.md guide

- CHANGELOG.md
- README.md
This PR updates a GitHub URL in the CHANGELOG.md and README.md files. GitHub changed the URL and the old one started redirecting to a new address causing `remark` to fail the CI build with an "Unexpected redirecting URL" warning.
Example:
```
CHANGELOG.md
656:1-656:166 warning Unexpected redirecting URL `https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds`, expected final URL `https://docs.github.com/en/actions/how-tos/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds` no-dead-urls remark-lint
```
(https://github.com/PHPCSStandards/PHP_CodeSniffer/actions/runs/15910535915/job/44876452363?pr=1151#step:7:11)
_N/A_
> Remark/URL redirection check: update GitHub URL

- .cspell.json
- src/Util/Common.php
- tests/Core/Util/Common/IsCamelCapsTest.php
I've refactored the existing tests to use data providers and added more tests to document the existing behaviour. See https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/846
n/a
Fixes #846
> Refactor IsCamelCapsTest to use data providers and add more tests

- src/Files/FileList.php
- tests/Core/Files/FileList/AbstractFileListTestCase.php
- tests/Core/Files/FileList/AddFileTest.php
- tests/Core/Files/FileList/ConstructTest.php
- tests/Core/Files/FileList/FilterDouble.php
- tests/Core/Files/FileList/Fixtures/file1.php
- tests/Core/Files/FileList/Fixtures/file2.php
This PR fixes the `FileList::__construct()` and `FileList::addFile()` methods to ensure that, when there is an attempt to add the same file twice, the `FileList::$numFiles` variable is not incremented. This behavior was causing a fatal error when using the `--parallel` option and passing the same file twice (see #1113).
The code was already handling duplicates correctly in the sense that duplicated files were not added to `FileList::$files`. However, `FileList::$numFiles` was being incorrectly incremented.
This PR also includes some basic tests for `FileList::__construct()` and `FileList::addFile()` in separate commits.
Fixed: fatal error when using the `--parallel` option and passing the same file twice
Fixes #1113
There is some duplicated logic in `FileList::__construct()` and …
> Files/FileList: adding the same file twice should not increment `FileList::$numFiles`

- .github/workflows/verify-release.yml
As of now, the Wiki is publicly editable via PRs to the [PHPCSStandards/PHP_CodeSniffer-documentation](https://github.com/PHPCSStandards/PHP_CodeSniffer-documentation) repository.
The editable version of the Wiki includes some automation, like automatically updating various output examples displayed in the Wiki.
The resulting output may change between PHPCS versions, so this commit adds a job to the "verify release" workflow to automatically trigger a rebuild of the Wiki for each new PHPCS release.
Other:
The Wiki documentation is now publicly editable via PRs to the [PHPCSStandards/PHP_CodeSniffer-documentation](https://github.com/PHPCSStandards/PHP_CodeSniffer-documentation) repository. Contributions welcome ;-)
> GH Actions/verify release: auto-trigger Wiki update on new release

- .github/pull_request_template.md
Typically, the wiki needs to be updated when:
* A new `public` property is added to a sniff ([Customisable Sniff Properties page](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties)).
* A new ruleset option is added ([Annotated Ruleset](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Annotated-Ruleset)).
* Support for a new configuration option is added ([Configuration Options](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Configuration-Options)).
* A new report type is added ([Reporting](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Reporting)).
etc etc
_N/A_
> Pull request template: add reminder to update wiki documentation

- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.php
The PHP 8.5 deprecations RFC contains a proposal to deprecate the use of semicolons as scope openers for `switch` `case` and `default` statements.
The `PSR2.ControlStructures.SwitchDeclaration` sniff already detects and flags this issue under the `WrongOpenercase` and `WrongOpenerdefault` error codes, but as the same error code is also used for `case`/`default` statements using the `: { ... }` syntax, the error code was non-fixable.
With an eye on the PHP 8.5 deprecation, it seems prudent to ensure that a semi-colon `case`/`default` scope opener can be auto-fixed to a colon.
Making the `: { ... }` syntax auto-fixable may be more complex, so is left as future scope.
Note: if this were a new sniff, I would probably have introduced new error code(s), so the fixable and the …
> PSR2/SwitchDeclaration: make "wrong opener" fixable if opener is a semi-colon

- .github/workflows/happy-new-year.yml
- .github/workflows/validate.yml
Remove the condition containing a hard-coded repository name in favour of a more generic condition which should safeguard that the cron job doesn't run on forks just the same.
_N/A_
> GH Actions: improve "don't run on forks" condition

- .github/dependabot.yml
Since PR #1156 was merged, the `gh-pages` branch contains a GH Actions workflow to deploy the site and it would be nice if dependencies in that workflow would be kept up to date.
The above solution was found via reading up on various discussions about this topic and hopefully _should_ work.
There is one caveat though, adding the `target_branch` to each section, means that the configuration in the `dependabot.yml` file will no longer be used for security updates. I'm not too concerned about that as I've yet to see the first security related PR from Dependabot in any of the projects I'm involved with.
Ref: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#target-branch-
_N/A_
> Dependabot: attempt to enable for orphan `gh-pages` branch

- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/PropertyTypeHandlingInline.inc
- tests/Core/Ruleset/Fixtures/TestStandard/Sniffs/SetProperty/PropertyTypeHandlingSniff.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.php
- tests/Core/Ruleset/PropertyTypeHandlingTest.xml
When array properties are set inline to one of the "special" values, i.e. `true`, `false` or `null`, this would not be handled correctly and always result in an empty array.
While it is highly debatable that this is something which will ever occur in real-life, as setting an array property like that would not give a sniff any usable information - basically the property should not have been an array property in that case -, it should still be handled correctly by the ruleset class.
Fixed now.
Includes additional tests.
Props to @rodrigoprimo for coming up with this scenario.
_N/A_ This is basically already covered by the changelog entry for #1006
> 4.0 | Ruleset: minor tweak to property type handling for arrays

- .github/workflows/verify-release.yml
The `verify-release` workflow triggers two other workflows, however, this should only be done for actual releases, not when the workflow is run as a dry-run for PRs changing the workflow.
_N/A_
> GH Actions/verify-release: fine tune update trigger conditions

- tests/ConfigDouble.php
- tests/Core/Config/AbstractRealConfigTestCase.php
- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
- tests/Core/Ruleset/DisplayCachedMessagesTest.php
- tests/Core/Ruleset/PopulateTokenListenersTest.php
- tests/Core/Tokenizers/AbstractTokenizerTestCase.php
- tests/Core/Util/Help/HelpTest.php
Since PHP 8.1, calling the `Reflection*::setAccessible()` methods is no longer necessary as reflected properties/methods/etc will always be accessible. However, the method calls are still needed for PHP < 8.1.
As of PHP 8.5, calling the `Reflection*::setAccessible()` methods is now formally deprecated and will yield a deprecation notice, which will fail test runs. As of PHP 9.0, the `setAccessible()` method(s) will be removed.
With the latter in mind, this commit prevents the deprecation notice by making the calls to `setAccessible()` conditional.
Silencing the deprecation would mean, this would need to be "fixed" again come PHP 9.0, while the current solution should be stable, including for PHP 9.0.
Ref: https://wiki.php.net/rfc/deprecations_php_8_5#extreflection_deprecations
_N/A_: test …
> PHP 8.5 | Tests: prevent deprecation notice for Reflection*::setAccessible()

- composer.json
There is a problem with the latest PHPUnit 11 releases, which cause the test runs to hang and time out in CI after six hours.
Limiting the builds to use a PHPUnit 11 version below the problematic ones should unblock contributing for now.
The timing is a bit unfortunate, what with the PHP 8.5 deprecations being merged and the latest PHPUnit versions containing related fixes, but it will be a while still before PHP 8.5 is released, so I'm not too concerned about that and I expect a new PHPUnit release fixing the "hanging" well before that time.
Related upstream issue: sebastianbergmann/phpunit#6304
_N/A_
> 4.0 | Composer: temporarily limit the supported PHPUnit 11 versions

- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
If a property uses the `abstract` modifier keyword, the spacing between properties would not be determined, leading to false negatives.
Fixed now.
Added support for PHP 8.4 abstract properties to the following sniffs:
- Squiz.WhiteSpace.MemberVarSpacing
> PHP 8.4 | Squiz/MemberVarSpacing: add support for abstract properties

- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
⚠️ Depends on PR #1184 ⚠️ 
---
Includes handling the modifier order when `abstract` is used. This introduces a new `AbstractAfterVisibility` error code.
Note: the modifier keyword order checks could probably do with some optimization, but that can be handled later.
Added support for PHP 8.4 abstract properties to the following sniffs:
- PSR2.Classes.PropertyDeclaration
- The PSR2.Classes.PropertyDeclaration will now check that the `abstract` modifier keyword is placed before a visibility keyword. 
- Errors will be reported via a new `AbstractAfterVisibility` error code.
> PHP 8.4 | PSR2/PropertyDeclaration: add support for abstract properties 

- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
> PHP 8.4 | Various sniffs: add tests with abstract properties

- .github/workflows/test.yml
Currently every single `composer install` on PHP 8.5 fails due to a deprecation notice coming from a Composer dependency during the reading of the `composer.json` file.
While it is expected that this will be fixed soonish (fix is already available in the dependency, we're just waiting for a new release of both the dependency as well as of Composer), I rather not have the red crosses on every single PR while working on getting PHPCS 4.0 released.
So, this commit adds a temporary work-around which should allow the tests to run against PHP 8.5 again. This should also allow us to monitor if any of the other deprecation PRs which have gone into PHP 8.5 cause issues for PHPCS.
Once a new version of Composer has been released, we should be able to revert this commit.
_N/A_
> GH Actions: apply work-around for testing against PHP 8.5

- .github/workflows/validate.yml
In the 4.x branch, only the `Tokens::...` constants should be used. The use of the properties from the `Tokens` class is deprecated.
This workflow job is intended to catch any accidental/force-of-habit usages of the `Tokens` properties.
_N/A_
> 4.0 | GH Actions: add automated check for usage of `Tokens::$...` properties

- tests/Core/AbstractMethodTestCase.php
- tests/Core/Tokenizers/AbstractTokenizerTestCase.php
Should work just the same and just as well.
Historical context: looks like the use of `DummyFile` is a left over from a time long, long ago, when the "test case code" was included in the same file as the unit test class. This was changed in 2016 for PHPCS 2.x via PR squizlabs/PHP_CodeSniffer#1193, but then the merge up into PHPCS 3.x (which introduced `DummyFile`) did not change the object instantiation.
_N/A_
> AbstractMethodTestCase/AbstractTokenizerTestCase: use LocalFile instead of DummyFile

- src/Files/File.php
- src/Tokenizers/PHP.php
If a variable in the global scope is passed to `File::getMemberProperties()`, the token may not have any "conditions".
This would result in `array_keys()` returning an empty array, which will cause `array_pop()` to return `null`, leading to the deprecation notice.
Fixed now via some extra defensive coding.
This change is already covered via the existing tests.
If an attribute is unclosed (missing the closing `]` bracket), the `PHP::findCloser()` returns `null`, which will lead to the PHP 8.5 deprecation notice.
This can only occur during live coding or when a file has a parse error, but PHPCS should handle that situation gracefully.
Fixed now.
This change is already covered via the existing tests.
When running the `NullsafeObjectOperatorTest`, the "Using null as an array offset" …
> PHP 8.5 | Fix runtime "Using null as an array offset" deprecations

- src/Files/FileList.php
- src/Filters/Filter.php
- src/Fixer.php
- src/Ruleset.php
- src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
- tests/ConfigDouble.php
- tests/Core/AbstractMethodTestCase.php
- tests/Core/Config/AbstractRealConfigTestCase.php
- tests/Core/Config/ExtensionsArgTest.php
- tests/Core/Config/GeneratorArgTest.php
- tests/Core/Config/SniffsExcludeArgsTest.php
- tests/Core/Filters/GitModifiedTest.php
- tests/Core/Filters/GitStagedTest.php
- tests/Core/Ruleset/AbstractRulesetTestCase.php
- tests/Core/Tokenizers/AbstractTokenizerTestCase.php
- tests/Core/Tokenizers/Tokenizer/ReplaceTabsInTokenTestCase.php
- tests/Core/Util/Common/GetSniffCodeTest.php
- tests/Core/Util/Help/HelpTest.php
- tests/Core/Util/MessageCollector/MessageCollectorTest.php
- tests/Standards/AbstractSniffTestCase.php
... which is a PHP 5.5+ syntax and can now be used what with support for PHP < 7.2 having been dropped.
Note: I have not applied this change to test expectations in data providers.
> 4.0 | Modernize: use `::class` resolution

- src/Config.php
- src/Tokenizers/Tokenizer.php
_This PR is part of a series._
These commits change a number of either `private` properties or inline variables to `private` class constants.
This wasn't previously possible as support for constant arrays was only added in PHP 5.6.
> Modernize: use class constant for constant array [1]

- src/Config.php
- src/Util/Help.php
- tests/Core/Util/Help/HelpTest.php
This changes the format/type of a `public` constant, but as the class is `final` and marked as `@internal`, i.e. not in the public API, this should not be regarded as a BC-break.
> Modernize: Util\Help: use constant array in class constant

- src/Tokenizers/PHP.php
Follow up on #1225 
This fixes yet another "Using null as an array offset" deprecation notice on PHP 8.5. This one only occurred on PHPCS 4.0, not on 3.x.
The tests for this fix have been pulled in #1225 (to safeguard that the issue doesn't exist in 3.x) and merged up into the 4.x branch.
Note: as the `if` condition was pretty complex, I've done a small refactor to make the code more readable and understandable.
Fixed PHP 8.5 "Using null as an array offset" deprecation notice.
Loosely related to https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/1215 and https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/1216, but yet another instance of this.
> PHP 8.5 | Fix another runtime deprecation notice

- src/Standards/PEAR/Sniffs/WhiteSpace/ObjectOperatorIndentSniff.php
- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR12/Sniffs/ControlStructures/BooleanOperatorPlacementSniff.php
- src/Standards/PSR12/Sniffs/Functions/NullableTypeDeclarationSniff.php
- src/Standards/PSR12/Sniffs/Properties/ConstantVisibilitySniff.php
- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
_This PR is part of a series._
These commits change a number of either `private` properties or inline variables to `private` class constants.
This wasn't previously possible as support for constant arrays was only added in PHP 5.6.
> Modernize: use class constants for constant arrays [4]

- src/Standards/Squiz/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/LongConditionClosingCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/PostStatementCommentSniff.php
- src/Standards/Squiz/Sniffs/Operators/ComparisonOperatorUsageSniff.php
- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php
_This PR is part of a series._
These commits change a number of either `private` properties or inline variables to `private` class constants.
This wasn't previously possible as support for constant arrays was only added in PHP 5.6.
> Modernize: use class constant for constant array [5]

- tests/Core/Tokenizers/PHP/NullsafeObjectOperatorTest.php
- tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
_This PR is part of a series._
These commits change a number of either `private` properties or inline variables to `private` class constants.
This wasn't previously possible as support for constant arrays was only added in PHP 5.6.
> Modernize: use class constant for constant array [6]

- src/Reports/Junit.php
- src/Standards/Generic/Sniffs/ControlStructures/DisallowYodaConditionsSniff.php
- src/Standards/PEAR/Sniffs/Formatting/MultiLineAssignmentSniff.php
- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PSR12/Sniffs/Functions/ReturnTypeDeclarationSniff.php
- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
The condition in the `if` already takes everything that's not an array, so if we reach the `elseif` we can be sure it's a `T_ARRAY` token.
The `isset()`'s in the same condition block already take care of this.
The `isset()`'s in the same condition block already take care of this.
`$commentEnd` is retrieved by walking backwards (since the sniffs allows for attributes), so will never be `false`
The `isset()`'s in the same condition block already take care of this.
_N/A_ These fixes should have no functional impact.
> Assorted minor fixes

- src/Generators/HTML.php
- src/Generators/Markdown.php
- src/Generators/Text.php
Follow up on #1237 and the PRs from the refactor of the Generator classes.
These were missed in commit 14ff8698f2b74cb51b5e2bd187de2054590b2bd0 as these methods were changed in the earlier refactor.
_N/A_ (falls under the original changelog entry)
> Generators: update a few more type declarations
