README.md
This just makes it more clear and prevents confusion when reading IMO.
N/A
N/A
=> Update wording in the note about the original project

.gitattributes
... as well as adding documentation to make it more straight-forward to understand what the file does and why.
=> .gitattributes: various readability improvements

README.md
Verified exhaustiveness thanks to:
```bash
grep -r '```'
```
Fixes #
=> Add Bash syntax highlighting to `README.md`

src/Files/File.php
... to remove unnecessary use of "whitelist" terminology.
_N/A_
Loosely related to #198
=> File: update inline comment

tests/Core/File/GetClassPropertiesTest.php
* Add parameter names as indexes in the data sets in data providers.
* Improve type specificity in the docblocks.
_N/A_
=> Tests/GetClassPropertiesTest: minor improvements

src/Standards/PSR12/ruleset.xml
Noticed this reference was missing while reviewing #233.
_N/A_
=> PSR12 ruleset: minor documentation tweak

.github/workflows/test.yml
Always run the `test` workflow for tags to ensure the PHAR files for the tag are generated.
_N/A_
=> GH Actions/test: always run the workflow for tags

tests/Core/File/FindImplementedInterfaceNamesTest.php, tests/Core/File/GetMethodParametersTest.php, tests/Core/Filters/GitModifiedTest.php, tests/Core/Filters/GitStagedTest.php
Normalize data provider arrays to improve scannability of the test cases covered.
See #225
_N/A_
=> Tests/various: normalize data provider arrays

src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.6.inc, src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.7.inc, src/Standards/Generic/Tests/PHP/CharacterBeforePHPOpeningTagUnitTest.3.inc
Follow up on squizlabs/PHP_CodeSniffer#2183 which added these test files.
This commit makes it clear within the test case file what is being tested by each.
_N/A_
=> Tests/Generic: make some tests a little more descriptive

.github/CONTRIBUTING.md
* Fix some typos.
* Add some extra information about how to handle tests related to parse errors/live coding.
* Add some additional information about git best practices.
* Add words of warning about copyright violations and AI generated PRs.
_N/A_
=> CONTRIBUTING: iterate on the guidelines

tests/Core/File/GetMethodPropertiesTest.inc, tests/Core/File/GetMethodPropertiesTest.php
=> File::getMethodProperties(): add extra test with nullable static return type

CHANGELOG.md
If there are no problems reported/no objections, the 3.9.0 release will go out tomorrow.
=> Changelog for the 3.9.0 release

tests/Core/Ruleset/RuleInclusionTest.xml
=> Tests/RulesetInclusion: fix reference to old repo

tests/Core/Tokenizer/OtherContextSensitiveKeywordsTest.inc
=> Tests/OtherContextSensitiveKeywordsTest: fix unintentional parse error

CHANGELOG.md
=> Changelog for the 3.9.1 release

autoload.php, src/Fixer.php, src/Standards/Generic/Sniffs/CodeAnalysis/JumbledIncrementerSniff.php, src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php, src/Standards/Generic/Sniffs/Debug/ESLintSniff.php, src/Standards/Generic/Sniffs/Debug/JSHintSniff.php, src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php, src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php, src/Tokenizers/CSS.php, src/Tokenizers/JS.php, src/Tokenizers/PHP.php, src/Tokenizers/Tokenizer.php, tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php, tests/Core/Tokenizer/TypedConstantsTest.php, tests/Core/Util/HelpTest.php, tests/Core/Util/SuggestTypeTest.php, tests/TestSuite7.php
Various minor doc fixes picked up along the way.
_N/A_
=> Various minor doc fixes

src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.1.inc, src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.18.inc
Move parse error test to its own test case file.
Update comment to indicate that this is an intentional parse error. This was
implied by the original comment instructing that it must be the last line
in the test case file.
N/A
See #143
=> PSR2/UseDeclaration: move parse error test case to its own file

CHANGELOG.md
=> Changelog for the 3.10.2 release

autoload.php, src/Tokenizers/PHP.php, src/Util/Common.php
Various minor doc fixes picked up along the way.
=> Docs: various minor fixes

.github/workflows/label-remove-outdated.yml
Just reducing some more manual clicks...
=> GH Actions/remove labels: update lists of labels to auto-remove

.github/labeler.yml
* Handle the new `Core Component: Generators` label.
* Improve regex to identify documentation changes (prevent confusion over tests).
_N/A_
=> GH Actions: tweak auto-label configuration

.github/workflows/build-phar.yml, .github/workflows/quicktest.yml, .github/workflows/test.yml
=> GH Actions: add the 4.0 branch to various selection criteria

tests/Core/Util/MessageCollector/MessageCollectorTest.php
=> MessageCollectorTest: data providers should be static

.github/workflows/test.yml
=> GH Actions: only ignore upper bound for PHP platform reqs

CHANGELOG.md, src/Standards/Generic/Sniffs/Functions/CallTimePassByReferenceSniff.php
=> Changelog for the 3.12.1 release

tests/Core/Tokenizers/PHP/BackfillFnTokenTest.inc, tests/Core/Tokenizers/PHP/BackfillFnTokenTest.php
Rename two test cases to be more descriptive.
_N/A_
=> BackfillFnTokenTest: rename two test cases

tests/Core/Tokenizers/Tokenizer/RecurseScopeMapDefaultKeywordConditionsTest.php
=> RecurseScopeMapDefaultKeywordConditionsTest: fix parameter name

tests/Core/Ruleset/ExpandRulesetReferenceInternalIgnoreTest.xml, tests/Core/Ruleset/PopulateTokenListenersRegisterNoArrayTest.xml, tests/Core/Ruleset/ProcessRulesetAutoloadFileNotFoundTest.xml, tests/Core/Ruleset/ProcessRulesetAutoloadTest.xml, tests/Core/Ruleset/ProcessRulesetInvalidNoSniffsDirTest.xml, tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoProcessTest.xml, tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoRegisterOrProcessTest.xml, tests/Core/Ruleset/RegisterSniffsRejectsInvalidSniffNoImplementsNoRegisterTest.xml
=> Tests: fix a typo in some test fixtures

src/Tokenizers/PHP.php
Recreation of upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/3344.
_N/A_
=> 4.0 | Tokenizer/PHP: defer to predefined regex

src/Util/Tokens.php
Follow up on #1021, which addressed #500.
Oops... missed one ;-)
_N/A_ (covered via the original entry)
=> Tokens: fix last use of property vs constant

src/Util/MessageCollector.php
Note: there will likely be more places in the codebase where this modernization could be applied. For now, just applying to some code I recently wrote.
_N/A_
=> Modernize: use list in foreach

autoload.php, src/Reports/Summary.php, src/Util/Cache.php
=> Modernize: static closures should be static

tests/Core/Tokenizers/PHP/BitwiseOrTest.php
Fix up some test descriptions to more accurately describe what is being tested.
_N/A
=> BitwiseOrTest: fix up some test descriptions

scripts/build-phar.php
=> build-phar script: minor readability tweak

CHANGELOG.md
=> Changelog for the 3.13.0 release

CHANGELOG.md, src/Config.php
=> Changelog for the 4.0.0beta1 release

src/Standards/Squiz/Docs/WhiteSpace/FunctionOpeningBraceSpaceStandard.xml
This PR updates the XML documentation of the `Squiz.WhiteSpace.FunctionOpeningBraceSpace` sniff to address the following:
- Update the sniff description and remove a code example for something that the sniff doesn't check. The sniff only checks for blank lines after the opening brace of a function, and not if the opening brace is on its own line.
- Ensure the <documentation> title matches the sniff name.
Squiz.WhiteSpace.FunctionOpeningBraceSpace: improvements to the XML documentation
=> Squiz/FunctionOpeningBraceSpace: update XML doc

.github/workflows/validate.yml, .shellcheckrc
Follow up after #1126
As this repo now contains bash scripts for the end-to-end tests, let's also run a minimal QA check on the code of the shell scripts.
Refs:
* https://github.com/koalaman/shellcheck
* https://github.com/koalaman/shellcheck/wiki
_N/A_
=> GH Actions/validate: add shellcheck job

.github/workflows/end-to-end-tests.yml, .github/workflows/quicktest.yml, .github/workflows/reusable-build-phar.yml, .github/workflows/test.yml, .github/workflows/verify-release.yml
Add `display_startup_errors=On` as per the current recommendation from PHPUnit.
Ref: https://github.com/sebastianbergmann/phpunit-documentation-english/commit/b3b159cbe9bd7eb5656dd381fc6f028549601dce
_N/A_
=> GH Actions: update PHP ini configuration
